export const autocompleteData = {
  jobTitles: [
    'Software Engineer',
    'Senior Software Engineer',
    'Staff Software Engineer',
    'Principal Software Engineer',
    'Lead Software Engineer',
    'Software Developer',
    'Senior Software Developer',
    'Full Stack Developer',
    'Frontend Developer',
    'Backend Developer',
    'Mobile Developer',
    'iOS Developer',
    'Android Developer',
    'DevOps Engineer',
    'Site Reliability Engineer',
    'Data Scientist',
    'Senior Data Scientist',
    'Machine Learning Engineer',
    'Data Analyst',
    'Business Analyst',
    'Product Manager',
    'Senior Product Manager',
    'Project Manager',
    'Scrum Master',
    'Product Owner',
    'UX Designer',
    'UI Designer',
    'Senior UX Designer',
    'Graphic Designer',
    'Web Designer',
    'Marketing Manager',
    'Digital Marketing Manager',
    'Content Marketing Manager',
    'SEO Specialist',
    'Social Media Manager',
    'Sales Representative',
    'Account Executive',
    'Sales Manager',
    'Accountant',
    'Senior Accountant',
    'Financial Analyst',
    'HR Manager',
    'HR Business Partner',
    'Recruiter',
    'Technical Recruiter',
    'Executive Assistant',
    'CEO',
    'CTO',
    'CFO',
    'COO',
    'VP of Engineering',
    'VP of Product',
    'Director of Engineering',
    'Director of Marketing',
    'Professor',
    'Teacher',
    'Teaching Assistant',
    'Researcher',
    'Research Scientist',
    'Attorney',
    'Lawyer',
    'Paralegal',
    'Consultant',
    'Management Consultant',
    'Strategy Consultant',
    'Nurse',
    'Registered Nurse',
    'Chief Nurse',
    'Civil Engineer',
    'Mechanical Engineer',
    'Electrical Engineer',
    'Structural Engineer',
    'IT Support Specialist',
    'System Administrator',
    'Network Administrator',
    'Security Analyst',
    'IT Manager',
  ],

  companies: [
    'Google',
    'Microsoft',
    'Amazon',
    'Apple',
    'Meta',
    'Facebook',
    'Netflix',
    'Tesla',
    'SpaceX',
    'Twitter',
    'LinkedIn',
    'Adobe',
    'Salesforce',
    'Oracle',
    'IBM',
    'Intel',
    'NVIDIA',
    'AMD',
    'Cisco',
    'Dell',
    'HP',
    'Samsung',
    'Sony',
    'Accenture',
    'Deloitte',
    'PwC',
    'EY',
    'KPMG',
    'McKinsey & Company',
    'Boston Consulting Group',
    'Bain & Company',
    'Goldman Sachs',
    'JP Morgan',
    'Morgan Stanley',
    'Bank of America',
    'Wells Fargo',
    'Citi',
    'United Nations',
    'World Bank',
    'NASA',
    'NIH',
    'CDC',
    'Mayo Clinic',
    'Johns Hopkins Hospital',
    'Stanford University',
    'MIT',
    'Harvard University',
    'Yale',
    'Princeton',
    'Columbia University',
    'University of California',
    'UCLA',
    'UC Berkeley',
    'University of Michigan',
    'University of Texas',
    'Tech Startup Inc',
    'Innovation Labs',
    'Digital Agency',
    'Creative Studio',
    'Consulting Corp',
    'Enterprise Solutions',
    'GlobalTech',
  ],

  universities: [
    'Stanford University',
    'MIT',
    'Harvard University',
    'Yale University',
    'Princeton University',
    'Columbia University',
    'University of Pennsylvania',
    'Cornell University',
    'University of Chicago',
    'University of California, Berkeley',
    'UCLA',
    'University of Michigan',
    'University of Washington',
    'University of Texas at Austin',
    'Northwestern University',
    'Duke University',
    'Johns Hopkins University',
    'Carnegie Mellon University',
    'University of California, Los Angeles',
    'New York University',
    'Boston University',
    'Georgia Institute of Technology',
    'University of Illinois at Urbana-Champaign',
    'University of Wisconsin-Madison',
    'Ohio State University',
    'University of Minnesota',
    'University of North Carolina at Chapel Hill',
    'University of Virginia',
    'University of Florida',
    'University of Colorado Boulder',
    'University of Arizona',
    'University of Utah',
    'Boston College',
    'University of Notre Dame',
    'University of Miami',
    'Emory University',
    'Georgetown University',
    'Washington University in St. Louis',
    'Vanderbilt University',
    'Rice University',
    'Purdue University',
    'Michigan State University',
    'Arizona State University',
    'University of Maryland',
    'University of Pittsburgh',
  ],

  degrees: [
    'Bachelor of Arts',
    'Bachelor of Science',
    'Bachelor of Business Administration',
    'Bachelor of Fine Arts',
    'Bachelor of Engineering',
    'Bachelor of Computer Science',
    'Master of Arts',
    'Master of Science',
    'Master of Business Administration',
    'Master of Fine Arts',
    'Master of Engineering',
    'Master of Computer Science',
    'Juris Doctor',
    'Doctor of Philosophy',
    'Doctor of Medicine',
    'Associate of Arts',
    'Associate of Science',
    'Certificate',
    'Diploma',
  ],

  fieldsOfStudy: [
    'Computer Science',
    'Software Engineering',
    'Information Technology',
    'Data Science',
    'Machine Learning',
    'Artificial Intelligence',
    'Business Administration',
    'Marketing',
    'Finance',
    'Economics',
    'Accounting',
    'Psychology',
    'Sociology',
    'Political Science',
    'Communications',
    'Graphic Design',
    'Industrial Design',
    'Architecture',
    'Engineering',
    'Civil Engineering',
    'Mechanical Engineering',
    'Electrical Engineering',
    'Chemical Engineering',
    'Biomedical Engineering',
    'Physics',
    'Mathematics',
    'Chemistry',
    'Biology',
    'Nursing',
    'Medicine',
    'Law',
    'Education',
    'English Literature',
    'History',
    'Philosophy',
    'Theology',
    'Human Resources',
    'International Relations',
    'Public Policy',
    'Environmental Science',
    'Statistics',
    'Information Systems',
    'Cybersecurity',
    'Network Engineering',
    'Cloud Computing',
    'Game Development',
    'Human-Computer Interaction',
    'Cognitive Science',
    'Linguistics',
    'Journalism',
    'Film Production',
    'Music',
    'Theater',
  ],

  skills: {
    programming: [
      'JavaScript',
      'TypeScript',
      'Python',
      'Java',
      'C++',
      'C#',
      'Go',
      'Rust',
      'Ruby',
      'PHP',
      'Swift',
      'Kotlin',
      'Scala',
      'R',
      'MATLAB',
      'SQL',
      'NoSQL',
      'GraphQL',
      'REST API',
      'JSON',
      'XML',
    ],
    frontend: [
      'React',
      'Vue.js',
      'Angular',
      'Next.js',
      'Nuxt.js',
      'Svelte',
      'HTML',
      'CSS',
      'Sass',
      'Tailwind CSS',
      'Bootstrap',
      'Material-UI',
      'Framer Motion',
      'Redux',
      'Zustand',
      'GraphQL',
      'Webpack',
      'Vite',
    ],
    backend: [
      'Node.js',
      'Express.js',
      'Django',
      'Flask',
      'Spring Boot',
      'Ruby on Rails',
      'Laravel',
      'ASP.NET',
      'ASP.NET Core',
      'FastAPI',
      'GraphQL',
      'gRPC',
      'Microservices',
      'REST API',
      'WebSockets',
      'NestJS',
    ],
    databases: [
      'PostgreSQL',
      'MySQL',
      'MongoDB',
      'Redis',
      'Elasticsearch',
      'SQLite',
      'Oracle',
      'Microsoft SQL Server',
      'DynamoDB',
      'Cassandra',
      'Neo4j',
      'Firebase',
      'Supabase',
    ],
    cloud: [
      'AWS',
      'Amazon Web Services',
      'Google Cloud Platform',
      'GCP',
      'Microsoft Azure',
      'Azure',
      'Docker',
      'Kubernetes',
      'Helm',
      'Terraform',
      'CloudFormation',
      'Serverless',
      'Lambda',
      'Cloud Functions',
    ],
    devops: [
      'Docker',
      'Kubernetes',
      'Jenkins',
      'GitLab CI',
      'GitHub Actions',
      'CircleCI',
      'Travis CI',
      'Ansible',
      'Chef',
      'Puppet',
      'Terraform',
      'Prometheus',
      'Grafana',
      'ELK Stack',
      'Datadog',
      'Splunk',
    ],
    tools: [
      'Git',
      'GitHub',
      'GitLab',
      'Bitbucket',
      'Jira',
      'Confluence',
      'Slack',
      'Zoom',
      'Figma',
      'Sketch',
      'Adobe XD',
      'Photoshop',
      'Illustrator',
      'Visual Studio Code',
      'IntelliJ IDEA',
      'Eclipse',
      'Postman',
      'Insomnia',
      'Docker Desktop',
    ],
    frameworks: [
      'React',
      'Angular',
      'Vue.js',
      'Next.js',
      'Nuxt.js',
      'Svelte',
      'Express.js',
      'Django',
      'Flask',
      'Spring Boot',
      'Ruby on Rails',
      'Laravel',
      'ASP.NET Core',
      'FastAPI',
      'NestJS',
    ],
    methodologies: [
      'Agile',
      'Scrum',
      'Kanban',
      'Waterfall',
      'Lean',
      'Six Sigma',
      'DevOps',
      'CI/CD',
      'TDD',
      'BDD',
      'Pair Programming',
      'Code Review',
      'Microservices',
      'SOA',
    ],
    softSkills: [
      'Leadership',
      'Team Management',
      'Project Management',
      'Communication',
      'Problem Solving',
      'Critical Thinking',
      'Time Management',
      'Adaptability',
      'Collaboration',
      'Mentoring',
      'Presentation',
      'Negotiation',
      'Conflict Resolution',
      'Customer Service',
      'Stakeholder Management',
    ],
  },

  certifications: [
    'AWS Solutions Architect',
    'AWS Developer Associate',
    'AWS SysOps Administrator',
    'Google Cloud Professional',
    'Microsoft Azure Administrator',
    'CompTIA A+',
    'CompTIA Network+',
    'CompTIA Security+',
    'CompTIA Cloud+',
    'PMP',
    'CAPM',
    'CSM',
    'CSPO',
    'SAFe Agilist',
    'Six Sigma Green Belt',
    'Six Sigma Black Belt',
    'Lean Six Sigma',
    'ITIL Foundation',
    'CCNA',
    'CCNP',
    'CCIE',
    'Oracle Certified Professional',
    'MongoDB Certified Developer',
    'Red Hat Certified Engineer',
    'Kubernetes Administrator',
    'Certified Kubernetes Developer',
    'Docker Certified Associate',
    'Google UX Design Certificate',
    'Meta Front-End Developer',
    'Meta Back-End Developer',
    'IBM Data Science Professional',
    'TensorFlow Developer Certificate',
    'Microsoft Certified: Azure Developer Associate',
    'Apple Certified iOS App Developer',
    'Certified Scrum Master',
    'Certified Product Owner',
    'Certified Scrum Professional',
    'CPA',
    'CFA',
    'FRM',
  ],

  certificationIssuers: [
    'Amazon Web Services',
    'Google',
    'Microsoft',
    'CompTIA',
    'Project Management Institute',
    'Scrum Alliance',
    'Scaled Agile',
    'Six Sigma',
    'ITIL',
    'Cisco',
    'Oracle',
    'MongoDB',
    'Red Hat',
    'Kubernetes',
    'Docker',
    'Apple',
    'IBM',
    'TensorFlow',
    'Meta',
    'CPA',
    'CFA Institute',
    'American Institute of Certified Public Accountants',
  ],

  locations: {
    usCities: [
      'New York, NY',
      'Los Angeles, CA',
      'Chicago, IL',
      'Houston, TX',
      'Phoenix, AZ',
      'Philadelphia, PA',
      'San Antonio, TX',
      'San Diego, CA',
      'Dallas, TX',
      'San Jose, CA',
      'Austin, TX',
      'Jacksonville, FL',
      'Fort Worth, TX',
      'Columbus, OH',
      'Charlotte, NC',
      'Indianapolis, IN',
      'Seattle, WA',
      'Denver, CO',
      'Washington, DC',
      'Boston, MA',
      'Nashville, TN',
      'Baltimore, MD',
      'Oklahoma City, OK',
      'Louisville, KY',
      'Portland, OR',
      'Las Vegas, NV',
      'Milwaukee, WI',
      'Albuquerque, NM',
      'Tucson, AZ',
      'Fresno, CA',
      'Sacramento, CA',
      'Kansas City, MO',
      'Mesa, AZ',
      'Atlanta, GA',
      'Miami, FL',
      'Raleigh, NC',
      'Omaha, NE',
      'Colorado Springs, CO',
      'Virginia Beach, VA',
      'Oakland, CA',
      'Minneapolis, MN',
      'Tampa, FL',
      'Arlington, TX',
      'New Orleans, LA',
      'Wichita, KS',
      'Cleveland, OH',
    ],
    states: [
      'Alabama',
      'Alaska',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'Florida',
      'Georgia',
      'Hawaii',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Kentucky',
      'Louisiana',
      'Maine',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'Nevada',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'New York',
      'North Carolina',
      'North Dakota',
      'Ohio',
      'Oklahoma',
      'Oregon',
      'Pennsylvania',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'Utah',
      'Vermont',
      'Virginia',
      'Washington',
      'West Virginia',
      'Wisconsin',
      'Wyoming',
    ],
    countries: [
      'United States',
      'Canada',
      'United Kingdom',
      'Germany',
      'France',
      'Spain',
      'Italy',
      'Netherlands',
      'Sweden',
      'Norway',
      'Denmark',
      'Finland',
      'Switzerland',
      'Austria',
      'Belgium',
      'Ireland',
      'Australia',
      'New Zealand',
      'Japan',
      'South Korea',
      'Singapore',
      'Hong Kong',
      'China',
      'India',
      'Brazil',
      'Mexico',
      'Argentina',
      'Chile',
      'South Africa',
      'Israel',
      'UAE',
      'Saudi Arabia',
    ],
  },

  languages: [
    'English',
    'Spanish',
    'Mandarin Chinese',
    'Cantonese',
    'French',
    'German',
    'Italian',
    'Portuguese',
    'Russian',
    'Japanese',
    'Korean',
    'Arabic',
    'Hindi',
    'Bengali',
    'Turkish',
    'Vietnamese',
    'Thai',
    'Dutch',
    'Swedish',
    'Polish',
    'Greek',
    'Hebrew',
    'Indonesian',
    'Malay',
    'Urdu',
    'Punjabi',
    'Tamil',
    'Telugu',
    'Marathi',
    'Czech',
    'Romanian',
    'Hungarian',
    'Ukrainian',
  ],

  proficiencyLevels: [
    'Beginner',
    'Elementary',
    'Intermediate',
    'Upper Intermediate',
    'Advanced',
    'Fluent',
    'Native',
  ],

  skillLevels: ['beginner', 'intermediate', 'advanced', 'expert'],
};

export const getAutocompleteSuggestions = (
  field: keyof typeof autocompleteData,
  query: string
): string[] => {
  const normalizedQuery = query.toLowerCase().trim();
  if (!normalizedQuery) return [];

  const data = autocompleteData[field];
  if (!data) return [];

  if (typeof data === 'object' && !Array.isArray(data)) {
    const suggestions: string[] = [];
    for (const category of Object.values(data as Record<string, string[]>)) {
      if (Array.isArray(category)) {
        suggestions.push(
          ...category.filter(
            (item): item is string =>
              typeof item === 'string' && item.toLowerCase().includes(normalizedQuery)
          )
        );
      }
    }
    return [...new Set(suggestions)].slice(0, 10);
  }

  if (Array.isArray(data)) {
    return data
      .filter(
        (item): item is string =>
          typeof item === 'string' && item.toLowerCase().includes(normalizedQuery)
      )
      .slice(0, 10);
  }

  return [];
};

export const getFieldSuggestions = (fieldType: string, query: string): string[] => {
  switch (fieldType) {
    case 'jobTitle':
      return getAutocompleteSuggestions('jobTitles', query);
    case 'company':
      return getAutocompleteSuggestions('companies', query);
    case 'university':
      return getAutocompleteSuggestions('universities', query);
    case 'degree':
      return getAutocompleteSuggestions('degrees', query);
    case 'field':
      return getAutocompleteSuggestions('fieldsOfStudy', query);
    case 'skill':
      const allSkills = [
        ...autocompleteData.skills.programming,
        ...autocompleteData.skills.frontend,
        ...autocompleteData.skills.backend,
        ...autocompleteData.skills.databases,
        ...autocompleteData.skills.cloud,
        ...autocompleteData.skills.devops,
        ...autocompleteData.skills.tools,
        ...autocompleteData.skills.methodologies,
        ...autocompleteData.skills.softSkills,
      ];
      return [
        ...new Set(allSkills.filter((s) => s.toLowerCase().includes(query.toLowerCase()))),
      ].slice(0, 10);
    case 'certification':
      return getAutocompleteSuggestions('certifications', query);
    case 'certificationIssuer':
      return getAutocompleteSuggestions('certificationIssuers', query);
    case 'city':
      return autocompleteData.locations.usCities
        .filter((c) => c.toLowerCase().includes(query.toLowerCase()))
        .slice(0, 10);
    case 'state':
      return autocompleteData.locations.states
        .filter((s) => s.toLowerCase().includes(query.toLowerCase()))
        .slice(0, 10);
    case 'country':
      return autocompleteData.locations.countries
        .filter((c) => c.toLowerCase().includes(query.toLowerCase()))
        .slice(0, 10);
    case 'language':
      return autocompleteData.languages
        .filter((l) => l.toLowerCase().includes(query.toLowerCase()))
        .slice(0, 10);
    case 'skillLevel':
      return autocompleteData.skillLevels.filter((l) =>
        l.toLowerCase().includes(query.toLowerCase())
      );
    case 'languageProficiency':
      return autocompleteData.proficiencyLevels.filter((p) =>
        p.toLowerCase().includes(query.toLowerCase())
      );
    default:
      return [];
  }
};
