import type { AutocompleteData } from './types';

export const de: Partial<AutocompleteData> = {
  jobTitles: [
    'Softwareentwickler',
    'Senior Softwareentwickler',
    'Softwareingenieur',
    'Senior Softwareingenieur',
    'Full Stack Entwickler',
    'Frontend Entwickler',
    'Backend Entwickler',
    'Mobile Entwickler',
    'iOS Entwickler',
    'Android Entwickler',
    'DevOps Ingenieur',
    'Datenwissenschaftler',
    'Senior Datenwissenschaftler',
    'Machine Learning Ingenieur',
    'Datenanalyst',
    'Business Analyst',
    'Produktmanager',
    'Senior Produktmanager',
    'Projektmanager',
    'Scrum Master',
    'UX Designer',
    'UI Designer',
    'Grafikdesigner',
    'Webdesigner',
    'Marketingmanager',
    'Social Media Manager',
    'Vertriebsmitarbeiter',
    'Verkaufsleiter',
    'Buchhalter',
    'Senior Buchhalter',
    'Finanzanalyst',
    'HR Manager',
    'Personalreferent',
    'Recruiter',
    'Assistent der Geschäftsführung',
    'Geschäftsführer',
    'CTO',
    'CFO',
    'Professor',
    'Lehrer',
    'Wissenschaftlicher Mitarbeiter',
    'Forscher',
    'Rechtsanwalt',
    'Berater',
    'Unternehmensberater',
    'Krankenpfleger',
    'Gesundheits- und Krankenpfleger',
    'Bauingenieur',
    'Maschinenbauingenieur',
    'Elektroingenieur',
    'IT Support Specialist',
    'Systemadministrator',
    'Netzwerkadministrator',
    'Sicherheitsanalyst',
    'IT Manager',
  ],

  degrees: [
    'Bachelor of Arts',
    'Bachelor of Science',
    'Bachelor of Business Administration',
    'Bachelor of Engineering',
    'Master of Arts',
    'Master of Science',
    'Master of Business Administration (MBA)',
    'Master of Engineering',
    'Doktortitel',
    'Promotion',
    'Associate Degree',
    'Fachhochschulreife',
    'Abitur',
    'Ausbildung',
    'Zertifikat',
  ],

  fieldsOfStudy: [
    'Informatik',
    'Software Engineering',
    'Informationstechnologie',
    'Datenwissenschaft',
    'Maschinelles Lernen',
    'Künstliche Intelligenz',
    'Betriebswirtschaftslehre',
    'Marketing',
    'Finanzen',
    'Volkswirtschaftslehre',
    'Buchhaltung',
    'Psychologie',
    'Soziologie',
    'Politikwissenschaft',
    'Kommunikation',
    'Design',
    'Architektur',
    'Ingenieurwesen',
    'Maschinenbau',
    'Elektrotechnik',
    'Bauingenieurwesen',
    'Physik',
    'Mathematik',
    'Chemie',
    'Biologie',
    'Krankenpflege',
    'Medizin',
    'Jura',
    'Bildungswesen',
    'Geschichte',
    'Philosophie',
    'Personalwesen',
    'Umweltwissenschaften',
    'Statistik',
    'Cybersicherheit',
  ],

  languages: [
    'Deutsch',
    'Englisch',
    'Spanisch',
    'Französisch',
    'Italienisch',
    'Portugiesisch',
    'Russisch',
    'Japanisch',
    'Koreanisch',
    'Chinesisch',
    'Arabisch',
    'Niederländisch',
    'Schwedisch',
    'Polnisch',
    'Türkisch',
    'Griechisch',
  ],

  proficiencyLevels: [
    'Anfänger',
    'Grundkenntnisse',
    'Mittelstufe',
    'Gute Kenntnisse',
    'Fortgeschritten',
    'Fließend',
    'Muttersprache',
  ],

  skillLevels: ['anfänger', 'mittelstufe', 'fortgeschritten', 'experte'],

  relationships: [
    'Ehemaliger Vorgesetzter',
    'Ehemaliger Kollege',
    'Direkter Mitarbeiter',
    'Ehemaliger Angestellter',
    'Professor',
    'Akademischer Berater',
    'Mentor',
    'Kunde',
    'Geschäftspartner',
    'Kooperationspartner',
  ],

  coreCompetencies: [
    'Strategische Planung',
    'Teamführung',
    'Projektmanagement',
    'Abteilungsübergreifende Zusammenarbeit',
    'Leistungsmanagement',
    'Budgetverwaltung',
    'Prozessoptimierung',
    'Risikomanagement',
    'Change Management',
    'Stakeholder-Management',
    'Talententwicklung',
    'Geschäftsentwicklung',
    'Datenanalyse',
    'Qualitätssicherung',
    'Vertragsverhandlung',
    'Lieferantenmanagement',
  ],
};
