import type { AutocompleteData } from './types';

export const en: AutocompleteData = {
  jobTitles: [
    '3D Animator',
    '3D Artist',
    '3D Generalist',
    'Academic Advisor',
    'Academic Dean',
    'Account Executive',
    'Account Manager',
    'Accountant',
    'Accounting Manager',
    'Accounts Payable Specialist',
    'Accounts Receivable Specialist',
    'Actor',
    'Actuary',
    'Acupuncturist',
    'Adjunct Professor',
    'Administrative Assistant',
    'Administrator',
    'Admissions Counselor',
    'Admissions Director',
    'Advisor',
    'Advocate',
    'Agile Coach',
    'Agricultural Technician',
    'AI Engineer',
    'AI Research Scientist',
    'Alumni Relations Coordinator',
    'Analyst',
    'Analytical Chemist',
    'Analytics Engineer',
    'Android Developer',
    'Anesthesiologist',
    'Animator',
    'Application Support Engineer',
    'Applications Developer',
    'Apprentice Electrician',
    'Apprentice Plumber',
    'Arbitrator',
    'Architect',
    'Archivist',
    'Art Director',
    'Art Instructor',
    'Art Teacher',
    'Art Therapist',
    'Assembly Technician',
    'Assistant Manager',
    'Assistant Principal',
    'Assistant Professor',
    'Assistant Store Manager',
    'Assistant Teacher',
    'Associate Attorney',
    'Associate Brand Manager',
    'Associate Editor',
    'Associate General Counsel',
    'Associate Producer',
    'Associate Professor',
    'Astronomer',
    'Athletic Director',
    'Athletic Trainer',
    'Attorney',
    'Audio Engineer',
    'Audiologist',
    'Audiology Assistant',
    'Auditor',
    'Author',
    'Automation Engineer',
    'Automotive Technician',
    'Back End Developer',
    'Backend Developer',
    'Bacteriologist',
    'Baker',
    'Bank Teller',
    'Banker',
    'Banquet Manager',
    'Barista',
    'Bartender',
    'BCBA',
    'Behavior Analyst',
    'Benefits Specialist',
    'Bid Manager',
    'Billing Clerk',
    'Biochemist',
    'Biologist',
    'Biomedical Engineer',
    'Biostatistician',
    'Bookkeeper',
    'Border Patrol Agent',
    'Brand Manager',
    'Broadcaster',
    'Budget Analyst',
    'Building Inspector',
    'Business Analyst',
    'Business Development Manager',
    'Business Development Representative',
    'Buyer',
    'Cabinetmaker',
    'Cable Technician',
    'Camera Operator',
    'Camp Director',
    'Cardiac Sonographer',
    'Cardiologist',
    'Career Counselor',
    'Carpenter',
    'Case Manager',
    'Cashier',
    'Category Manager',
    'Catering Coordinator',
    'Catering Manager',
    'CEO',
    'Certified Nursing Assistant',
    'CFO',
    'Chancellor',
    'Channel Partner Manager',
    'Character Artist',
    'Charge Nurse',
    'Chef',
    'Chemical Engineer',
    'Chemist',
    'Chief Executive Officer',
    'Chief Financial Officer',
    'Chief Human Resources Officer',
    'Chief Information Officer',
    'Chief Information Security Officer',
    'Chief Legal Officer',
    'Chief Marketing Officer',
    'Chief Medical Officer',
    'Chief Nurse',
    'Chief Operating Officer',
    'Chief Product Officer',
    'Chief Security Officer',
    'Chief Technology Officer',
    'Chiropractic Assistant',
    'Chiropractor',
    'Cinematographer',
    'City Manager',
    'City Planner',
    'Civil Engineer',
    'Claims Adjuster',
    'Clerk',
    'Clinical Director',
    'Clinical Investigator',
    'Clinical Operations Manager',
    'Clinical Psychologist',
    'Clinical Research Associate',
    'Clinical Research Coordinator',
    'Clinical Research Manager',
    'Cloud Architect',
    'Cloud Engineer',
    'Cloud Security Engineer',
    'CNA',
    'CNC Operator',
    'CNC Programmer',
    'Coach',
    'Columnist',
    'Commercial Pilot',
    'Communications Manager',
    'Community Manager',
    'Community Outreach Coordinator',
    'Compensation and Benefits Manager',
    'Compliance Analyst',
    'Compliance Manager',
    'Compliance Officer',
    'Compliance Specialist',
    'Composer',
    'Concept Artist',
    'Concierge',
    'Construction Manager',
    'Construction Superintendent',
    'Consultant',
    'Content Designer',
    'Content Marketing Manager',
    'Content Writer',
    'Contract Administrator',
    'Contract Specialist',
    'Contracts Manager',
    'Controller',
    'Controls Engineer',
    'COO',
    'Cook',
    'Copywriter',
    'Corporate Counsel',
    'Corporate Trainer',
    'Counselor',
    'Court Reporter',
    'Creative Director',
    'Creative Producer',
    'Creative Services Manager',
    'Credit Analyst',
    'Critical Care Nurse',
    'CTO',
    'Curator',
    'Curriculum Developer',
    'Customer Experience Manager',
    'Customer Service Lead',
    'Customer Service Representative',
    'Customer Success Manager',
    'Customer Success Specialist',
    'Customer Support Engineer',
    'Customer Support Specialist',
    'Customs Broker',
    'Customs Officer',
    'Cybersecurity Analyst',
    'Cybersecurity Engineer',
    'Data Analyst',
    'Data Engineer',
    'Data Entry Clerk',
    'Data Governance Analyst',
    'Data Quality Analyst',
    'Data Scientist',
    'Database Administrator',
    'Database Engineer',
    'Dean',
    'Dean of Students',
    'Delivery Driver',
    'Dental Assistant',
    'Dental Hygienist',
    'Dentist',
    'Design Director',
    'Designer',
    'Developer',
    'DevOps Engineer',
    'DevSecOps Engineer',
    'Dietitian',
    'Digital Marketing Manager',
    'Digital Marketing Specialist',
    'Digital Merchandiser',
    'Director',
    'Director of Admissions',
    'Director of Brand Marketing',
    'Director of Clinical Operations',
    'Director of Communications',
    'Director of Engineering',
    'Director of Finance',
    'Director of Legal',
    'Director of Logistics',
    'Director of Marketing',
    'Director of Nursing',
    'Director of Operations',
    'Director of Photography',
    'Director of Product',
    'Director of Sales',
    'Director of Supply Chain',
    'Dispatcher',
    'District Manager',
    'Diversity and Inclusion Manager',
    'Doctor',
    'Documentation Specialist',
    'Donor Relations Specialist',
    'Driver',
    'Drywall Installer',
    'E-commerce Manager',
    'E-commerce Specialist',
    'Ecologist',
    'Economist',
    'Editor',
    'Education Administrator',
    'EHS Specialist',
    'Electrical Engineer',
    'Electrician',
    'Embedded Systems Engineer',
    'Emergency Medical Technician',
    'Emergency Medical Technician (EMT)',
    'Emergency Room Nurse',
    'Employee Relations Specialist',
    'Energy Manager',
    'Engineer',
    'Engineering Manager',
    'English Teacher',
    'Enterprise Account Executive',
    'Enterprise Architect',
    'Environmental Analyst',
    'Environmental Engineer',
    'Environmental Scientist',
    'Epidemiologist',
    'ESL Coordinator',
    'ESL Instructor',
    'Estimator',
    'Event Coordinator',
    'Event Planner',
    'Executive Assistant',
    'Executive Creative Director',
    'Executive Director',
    'Executive Housekeeper',
    'Executive Producer',
    'Facilities Coordinator',
    'Facilities Engineer',
    'Facilities Manager',
    'Family Therapist',
    'Farmer',
    'Fashion Designer',
    'File Clerk',
    'Finance Manager',
    'Financial Advisor',
    'Financial Aid Counselor',
    'Financial Aid Director',
    'Financial Analyst',
    'Financial Controller',
    'Financial Planner',
    'Firefighter',
    'Firmware Engineer',
    'First Grade Teacher',
    'Fitness Instructor',
    'Fitness Trainer',
    'Fleet Manager',
    'Flight Attendant',
    'Florist',
    'Foley Artist',
    'Food and Beverage Director',
    'Foreign Language Teacher',
    'Foreign Service Officer',
    'Foreman',
    'Forensic Accountant',
    'Forester',
    'Forklift Operator',
    'Front Desk Agent',
    'Front Office Manager',
    'Frontend Developer',
    'Full Stack Developer',
    'Full Stack Engineer',
    'Fundraising Coordinator',
    'Fundraising Manager',
    'Gaffer',
    'Game Designer',
    'Game Producer',
    'General Contractor',
    'General Counsel',
    'General Manager',
    'Genetic Counselor',
    'Geologist',
    'Glazier',
    'Grants Administrator',
    'Graphic Designer',
    'Growth Marketing Manager',
    'Gynecologist',
    'Hair Stylist',
    'Hardware Engineer',
    'Health Information Manager',
    'Health Inspector',
    'Healthcare Administrator',
    'Healthcare Consultant',
    'Heavy Equipment Operator',
    'Help Desk Technician',
    'High School Teacher',
    'History Teacher',
    'Home Health Aide',
    'Home Health Nurse',
    'Hospice Nurse',
    'Hospital Administrator',
    'Host',
    'Host/Hostess',
    'Hostess',
    'Hotel Manager',
    'Housekeeper',
    'Housekeeping Supervisor',
    'HR Business Partner',
    'HR Director',
    'HR Generalist',
    'HR Manager',
    'HR Specialist',
    'Human Resources Manager',
    'HVAC Technician',
    'ICU Nurse',
    'Illustrator',
    'Industrial Designer',
    'Industrial Engineer',
    'Infection Control Nurse',
    'Information Architect',
    'Information Security Manager',
    'Instructional Designer',
    'Insurance Agent',
    'Insurance Broker',
    'Intelligence Analyst',
    'Interaction Designer',
    'Interior Designer',
    'Inventory Analyst',
    'Inventory Controller',
    'Inventory Manager',
    'Inventory Planner',
    'Inventory Specialist',
    'Investment Banker',
    'iOS Developer',
    'Ironworker',
    'IT Manager',
    'IT Project Manager',
    'IT Support Specialist',
    'Journalist',
    'Journeyman Electrician',
    'Judge',
    'Junior Back End Developer',
    'Junior Buyer',
    'Junior Front End Developer',
    'Junior Full Stack Engineer',
    'Junior Graphic Designer',
    'Junior Product Designer',
    'Junior Software Engineer',
    'Key Grip',
    'Keyholder',
    'Kindergarten Teacher',
    'Laboratory Manager',
    'Laboratory Technician',
    'Landscape Architect',
    'Landscaper',
    'Lawyer',
    'Lead Back End Developer',
    'Lead DevOps Engineer',
    'Lead Front End Developer',
    'Lead Game Designer',
    'Lead Graphic Designer',
    'Lead Platform Engineer',
    'Lead Product Designer',
    'Lead Software Engineer',
    'Lecturer',
    'Legal Assistant',
    'Legal Counsel',
    'Legal Operations Specialist',
    'Legal Secretary',
    'Level Designer',
    'Librarian',
    'Library Assistant',
    'Line Cook',
    'Loan Officer',
    'Localization Manager',
    'Locksmith',
    'Logistics Analyst',
    'Logistics Coordinator',
    'Logistics Manager',
    'Logistics Specialist',
    'Loss Prevention Officer',
    'Loss Prevention Specialist',
    'LPN',
    'LVN',
    'Machine Learning Engineer',
    'Machinist',
    'Mail Carrier',
    'Mailroom Clerk',
    'Major Gifts Officer',
    'Management Consultant',
    'Manager',
    'Managing Editor',
    'Manufacturing Engineer',
    'Manufacturing Supervisor',
    'Marine Biologist',
    'Marketing Coordinator',
    'Marketing Manager',
    'Mason',
    'Massage Therapist',
    'Math Specialist',
    'Math Teacher',
    'Mathematician',
    'Mechanic',
    'Mechanical Engineer',
    'Media Relations Specialist',
    'Medical Assistant',
    'Medical Billing Specialist',
    'Medical Coder',
    'Medical Director',
    'Medical Laboratory Scientist',
    'Medical Laboratory Technician',
    'Medical Records Clerk',
    'Medical Scribe',
    'Medical Transcriptionist',
    'Mental Health Clinician',
    'Mental Health Counselor',
    'Merchandise Planner',
    'Merchandiser',
    'Merchandising Manager',
    'Meteorologist',
    'Microbiologist',
    'Middle School Teacher',
    'Military Officer',
    'Mobile Developer',
    'Montessori Teacher',
    'Mortgage Broker',
    'Motion Designer',
    'Multimedia Designer',
    'Museum Technician',
    'Music Producer',
    'Music Teacher',
    'Music Therapist',
    'Network Administrator',
    'Network Engineer',
    'News Anchor',
    'Non-Profit Director',
    'Nurse',
    'Nurse Practitioner',
    'Nursing Assistant',
    'Nursing Supervisor',
    'Nutritionist',
    'Obstetrician',
    'Occupational Health Nurse',
    'Occupational Therapist',
    'Occupational Therapy Assistant',
    'Office Administrator',
    'Office Assistant',
    'Office Coordinator',
    'Office Manager',
    'Onboarding Specialist',
    'Operations Analyst',
    'Operations Coordinator',
    'Operations Manager',
    'Ophthalmic Technician',
    'Optometric Technician',
    'Optometrist',
    'Orthotist',
    'Over-the-Road Truck Driver',
    'Packaging Operator',
    'Paid Media Manager',
    'Painter',
    'Palliative Care Nurse',
    'Paralegal',
    'Paramedic',
    'Partner',
    'Pastry Chef',
    'Patent Agent',
    'Patent Attorney',
    'Patent Paralegal',
    'Patient Advocate',
    'Patient Care Technician',
    'Patient Services Coordinator',
    'Payroll Specialist',
    'Pediatric Nurse',
    'Pediatrician',
    'Penetration Tester',
    'Personal Care Aide',
    'Personal Shopper',
    'Personal Trainer',
    'Petroleum Engineer',
    'Pharmacist',
    'Pharmacologist',
    'Pharmacy Technician',
    'Phlebotomist',
    'Photographer',
    'Photojournalist',
    'Physical Education Teacher',
    'Physical Therapist',
    'Physical Therapist Assistant',
    'Physician',
    'Physician Assistant',
    'Physicist',
    'Pilot',
    'Pipefitter',
    'Plant Manager',
    'Platform Engineer',
    'Plumber',
    'Podcast Host',
    'Police Officer',
    'Policy Analyst',
    'Portfolio Manager',
    'Postal Clerk',
    'Postdoctoral Researcher',
    'Pre-school Director',
    'Pre-school Teacher',
    'Prep Cook',
    'President',
    'Principal',
    'Principal Data Scientist',
    'Principal Investigator',
    'Principal Product Designer',
    'Principal Software Engineer',
    'Procurement Analyst',
    'Procurement Manager',
    'Procurement Specialist',
    'Producer',
    'Product Designer',
    'Product Development Engineer',
    'Product Manager',
    'Product Owner',
    'Production Assistant',
    'Production Engineer',
    'Production Planner',
    'Production Supervisor',
    'Professor',
    'Program Analyst',
    'Program Manager',
    'Project Coordinator',
    'Project Manager',
    'Project Superintendent',
    'Proofreader',
    'Property Manager',
    'Proposal Writer',
    'Prosthetist',
    'Psychiatric Nurse',
    'Psychiatrist',
    'Psychologist',
    'Public Administrator',
    'Public Relations Manager',
    'Public Relations Specialist',
    'Purchasing Agent',
    'QA Engineer',
    'Quality Assurance Engineer',
    'Quality Control Inspector',
    'Quality Engineer',
    'Quantitative Analyst',
    'Radiation Therapist',
    'Radiologic Tech',
    'Rancher',
    'Ranger',
    'RBT',
    'Real Estate Agent',
    'Receptionist',
    'Recreational Therapist',
    'Recruiter',
    'Regional Manager',
    'Registered Behavior Technician',
    'Registered Nurse',
    'Registrar',
    'Registrar Coordinator',
    'Regulatory Affairs Manager',
    'Regulatory Affairs Specialist',
    'Regulatory Writer',
    'Release Engineer',
    'Reliability Engineer',
    'Relocation Specialist',
    'Reporter',
    'Research Assistant',
    'Research Associate',
    'Research Scientist',
    'Researcher',
    'Respiratory Therapist',
    'Restaurant Manager',
    'Retail Associate',
    'Retail Buyer',
    'Retail Keyholder',
    'Retail Sales Associate',
    'Retail Salesperson',
    'Revenue Operations Manager',
    'Risk Analyst',
    'Robotics Engineer',
    'Roofer',
    'Route Driver',
    'Safety Director',
    'Safety Inspector',
    'Sales Associate',
    'Sales Development Representative',
    'Sales Director',
    'Sales Manager',
    'Sales Operations Manager',
    'Sales Representative',
    'School Counselor',
    'School Psychologist',
    'School Social Worker',
    'Science Teacher',
    'Scientific Writer',
    'Scientist',
    'Scrum Master',
    'Second Grade Teacher',
    'Secretary',
    'Security Analyst',
    'Security Architect',
    'Security Engineer',
    'Security Guard',
    'Security Officer',
    'Senior Account Executive',
    'Senior Account Manager',
    'Senior Accountant',
    'Senior AI Engineer',
    'Senior Analytics Engineer',
    'Senior Brand Manager',
    'Senior Business Analyst',
    'Senior Consultant',
    'Senior Copywriter',
    'Senior Customer Success Manager',
    'Senior Data Analyst',
    'Senior Data Engineer',
    'Senior Data Scientist',
    'Senior DevOps Engineer',
    'Senior Financial Analyst',
    'Senior Front End Developer',
    'Senior Game Designer',
    'Senior Graphic Designer',
    'Senior HR Business Partner',
    'Senior Machine Learning Engineer',
    'Senior Manager',
    'Senior Product Designer',
    'Senior Product Manager',
    'Senior Product Marketing Manager',
    'Senior QA Engineer',
    'Senior Recruiter',
    'Senior Registered Nurse',
    'Senior Research Scientist',
    'Senior Software Developer',
    'Senior Software Engineer',
    'Senior Sound Designer',
    'Senior Systems Analyst',
    'Senior Technical Artist',
    'Senior Technical Writer',
    'Senior UX Designer',
    'Senior UX Researcher',
    'Senior UX Writer',
    'Senior Video Editor',
    'Senior Visual Designer',
    'SEO Specialist',
    'Server',
    'Service Designer',
    'Shift Supervisor',
    'Shipping Clerk',
    'Site Reliability Engineer',
    'Social Media Manager',
    'Social Media Specialist',
    'Social Worker',
    'Software Architect',
    'Software Developer',
    'Software Engineer',
    'Software Engineering Manager',
    'Solar Installer',
    'Solution Architect',
    'Solutions Architect',
    'Solutions Consultant',
    'Solutions Engineer',
    'Sommelier',
    'Sound Designer',
    'Sous Chef',
    'Special Education Coordinator',
    'Special Education Teacher',
    'Specialist',
    'Speech Language Pathologist',
    'Sports Coach',
    'Staff Accountant',
    'Staff Nurse',
    'Staff Software Engineer',
    'Staff Writer',
    'Statistician',
    'Stock Clerk',
    'Store Manager',
    'Strategic Sourcing Manager',
    'Strategy Consultant',
    'Structural Engineer',
    'Student',
    'Substitute Teacher',
    'Superintendent',
    'Supervisor',
    'Supplier Quality Engineer',
    'Supply Chain Analyst',
    'Supply Chain Manager',
    'Supply Chain Planner',
    'Surgeon',
    'Surgical Technologist',
    'Surveyor',
    'Sustainability Manager',
    'Sustainability Specialist',
    'System Administrator',
    'Systems Administrator',
    'Systems Analyst',
    'Systems Architect',
    'Systems Designer',
    'Systems Engineer',
    'Talent Acquisition Specialist',
    'Talent Development Specialist',
    'Tax Accountant',
    'Tax Specialist',
    'Teacher',
    'Teacher Assistant',
    'Teaching Assistant',
    'Technical Artist',
    'Technical Editor',
    'Technical Product Manager',
    'Technical Program Manager',
    'Technical Proposal Writer',
    'Technical Recruiter',
    'Technical Support Engineer',
    'Technical Writer',
    'Technician',
    'Telemetry Nurse',
    'Test Automation Engineer',
    'Therapist',
    'Third Grade Teacher',
    'Tour Guide',
    'Translations Coordinator',
    'Transportation Manager',
    'Travel Agent',
    'Travel Nurse',
    'Treasury Analyst',
    'Triage Nurse',
    'Truck Driver',
    'Tutor',
    'UI Designer',
    'Underwriter',
    'University President',
    'Urban Planner',
    'UX Designer',
    'UX Researcher',
    'UX Writer',
    'Validation Engineer',
    'Veterinarian',
    'Veterinary Technician',
    'Vice President of Engineering',
    'Video Editor',
    'Video Producer',
    'Videographer',
    'Visual Designer',
    'Visual Merchandiser',
    'Voice Actor',
    'Volunteer Coordinator',
    'VP of Engineering',
    'VP of Finance',
    'VP of Human Resources',
    'VP of Legal',
    'VP of Operations',
    'VP of Product',
    'VP of Sales',
    'Waiter/Waitress',
    'Warehouse Associate',
    'Warehouse Manager',
    'Warehouse Supervisor',
    'Web Designer',
    'Web Developer',
    'Webmaster',
    'Welder',
    'Wound Care Nurse',
    'Writer',
    'Yoga Instructor',
    'Youth Worker',
    'Zoologist',
  ],

  companies: [
    ',',
    '3M',
    'A BN AMRO',
    'ABB',
    'Abbott Laboratories',
    'AbbVie',
    'Absa Group',
    'Abu Dhabi Commercial Bank',
    'Accenture',
    'Accor',
    'AccuWeather',
    'Activision Blizzard',
    'Adidas',
    'Adobe',
    'ADP',
    'Adyen',
    'Aegon',
    'Aeon',
    'AES Corporation',
    'Aflac',
    'AIA Group',
    'Air Canada',
    'Air France-KLM',
    'Airbnb',
    'Airbus',
    'Airtel',
    'Akamai',
    'Akamai Technologies',
    'Al Rajhi Bank',
    'Albertsons',
    'Alcoa',
    'Aldi',
    'Alexion Pharmaceuticals',
    'Alfa Laval',
    'Alibaba',
    'Alibaba Group',
    'AlixPartners',
    'AllianceBernstein',
    'Allianz',
    'Alphabet',
    'Alstom',
    'AltaGas',
    'Altria',
    'Amazon',
    'AMD',
    'American Airlines',
    'American Airlines Group',
    'American Express',
    'American International Group',
    'American Welding Society',
    'AmerisourceBergen',
    'Amgen',
    'AMRI Global',
    'ANA Holdings',
    'Analog Devices',
    'Anheuser-Busch',
    'Ansys',
    'Anthem',
    'ANZ',
    'AOL',
    'Aon',
    'AP Moller-Maersk',
    'Apollo Global Management',
    'Apple',
    'Applied Materials',
    'Arab National Bank',
    'Aramco',
    'Archer Daniels Midland',
    'Arista Networks',
    'Arup',
    'Asana',
    'Ascension Health',
    'Ashland Global',
    'Asiana Airlines',
    'ASML',
    'Astellas Pharma',
    'AstraZeneca',
    'ASUS',
    'AsusTek',
    'AT&T',
    'Atlassian',
    'Autodesk',
    'Avery Dennison',
    'Avis Budget',
    'Aviva',
    'Avnet',
    'Avon Products',
    'Avtovaz',
    'AXA',
    'Axalta Coating Systems',
    'Axis Bank',
    'AXT Inc.',
    'Ayguesrock',
    'AZRBJ',
    'BAE Systems',
    'Bain & Company',
    'Banco Bilbao Vizcaya Argentaria',
    'Banco Bradesco',
    'Banco de Chile',
    'Banco de Credito del Peru',
    'Banco do Brasil',
    'Banco Santander',
    'Banco Santander Brasil',
    'Bancolombia',
    'Bandai Namco',
    'Bank of America',
    'Bank of China',
    'Bank of England',
    'Bank of Montreal',
    'Bank of Nova Scotia',
    'Banorte',
    'Banque Misr',
    'Barclays',
    'BASF',
    'Baxter International',
    'Bayer',
    'BBVA',
    'Becton Dickinson',
    'Berkshire Hathaway',
    'Bertelsmann',
    'Best Buy',
    'Bill & Melinda Gates Foundation',
    'Biogen',
    'BlackRock',
    'Blackstone',
    'Block',
    'BMW',
    'BNP Paribas',
    'BNY Mellon',
    'Boehringer Ingelheim',
    'Boeing',
    'Booz Allen Hamilton',
    'Boston Consulting Group',
    'Boston Scientific',
    'BP',
    'BPCL',
    'Bristol Myers Squibb',
    'British Airways',
    'Broadcom',
    'BTG Pactual',
    'Bupa',
    'ByteDance',
    'C SL Limited',
    'Cadence Design Systems',
    'Canal+',
    'Capgemini',
    'Capital One',
    'Cardinal Health',
    'Carrefour',
    'Caterpillar',
    'CDC',
    'Centene',
    'Charles Schwab',
    'Charter Communications',
    'Check Point Software',
    'Chevron',
    'Chipotle Mexican Grill',
    'Choice Hotels',
    'Chubb',
    'CIB Egypt',
    'CIBC',
    'Cigna',
    'Cisco',
    'Cisco Systems',
    'Citi',
    'Citigroup',
    'Cleveland Clinic',
    'Cloudflare',
    'Coca-Cola',
    'Cognizant',
    'Coles Group',
    'Colgate-Palmolive',
    'Columbia University',
    'Comcast',
    'Commerzbank',
    'Commonwealth Bank of Australia',
    'Confluent',
    'Consulting Corp',
    'Costco Wholesale',
    'Creative Studio',
    'Credit Agricole',
    'CrowdStrike',
    'CVS Health',
    'Daiichi Sankyo',
    'Daiwa Securities',
    'Danaher',
    'Danone',
    'Danske Bank',
    'Databricks',
    'Davita',
    'Decathlon',
    'Deere & Company',
    'Dell',
    'Dell Technologies',
    'Deloitte',
    'Delta Air Lines',
    'Deutsche Bank',
    'Deutsche Telekom',
    'DHL',
    'Diageo',
    'Digital Agency',
    'DigitalOcean',
    'Discover Financial Services',
    'DNB',
    'Doctors Without Borders',
    'Dropbox',
    'Duke Energy',
    'DXC Technology',
    'Dynatrace',
    'E.ON',
    'Eaton',
    'eBay',
    'Ecopetrol',
    'EDF',
    'Eisai',
    'Elastic',
    'Electronic Arts',
    'Eli Lilly',
    'Emirates Group',
    'Enel',
    'Engie',
    'Eni',
    'Enterprise Solutions',
    'EPAM Systems',
    'Equinix',
    'Equinor',
    'Ericsson',
    'Estee Lauder',
    'European Central Bank',
    'European Commission',
    'Evercore',
    'EY',
    'F TI Consulting',
    'Facebook',
    'Fanuc',
    'FedEx',
    'Fidelity Investments',
    'First Abu Dhabi Bank',
    'FirstRand',
    'Ford',
    'Fortinet',
    'Fox Corporation',
    'Fresenius',
    'Fuji Media',
    'Fujitsu',
    'Gartner',
    'GE HealthCare',
    'Geisinger',
    'General Dynamics',
    'General Electric',
    'General Mills',
    'General Motors',
    'Gilead Sciences',
    'GitHub',
    'GlaxoSmithKline',
    'GlobalTech',
    'Goldman Sachs',
    'Google',
    'Grupo Aval',
    'H&M',
    'Handelsbanken',
    'Hanzhong Technologies',
    'Harvard University',
    'HCA Healthcare',
    'HDFC Bank',
    'Henry Schein',
    'Hermes',
    'Heroku',
    'Hewlett Packard Enterprise',
    'Hilton Worldwide',
    'Hitachi',
    'Home Depot',
    'Honda',
    'Honeywell',
    'HP',
    'HP Inc.',
    'HSBC',
    'HubSpot',
    'Humana',
    'Hyatt Hotels',
    'Hyundai',
    'Iberdrola',
    'IBM',
    'ICICI Bank',
    'IKEA',
    'Inbursa',
    'Indian Oil',
    'Indian Railways',
    'Inditex',
    'Infosys',
    'ING Group',
    'Innovation Labs',
    'Intel',
    'InterContinental Hotels Group',
    'Intermountain Health',
    'International Monetary Fund',
    'Intesa Sanpaolo',
    'Intuit',
    'Itaú Unibanco',
    'Japan Airlines',
    'JD.com',
    'Johns Hopkins Hospital',
    'Johns Hopkins Medicine',
    'Johnson & Johnson',
    'JP Morgan',
    'JPMorgan Chase',
    'Julius Baer',
    'Kaiser Permanente',
    'Kansai Electric Power',
    'KBC Group',
    'Kearney',
    'Kellogg\'s',
    'Kering',
    'Keyence',
    'King Faisal Specialist Hospital',
    'KLA Corporation',
    'KPMG',
    'Kraft Heinz',
    'Kroger',
    'Kuwait Finance House',
    'L\'Oreal',
    'Lam Research',
    'LATAM Airlines',
    'Legal & General',
    'Lenovo',
    'Lidl',
    'LinkedIn',
    'Lloyds Banking Group',
    'Lockheed Martin',
    'Logitech',
    'Lowe\'s',
    'Lufthansa Group',
    'LVMH',
    'Macquarie Group',
    'Macy\'s',
    'Maersk',
    'Manulife Financial',
    'Marks & Spencer',
    'Marriott International',
    'Mars',
    'Mass General Brigham',
    'Mastercard',
    'Mayo Clinic',
    'McDonald\'s',
    'McKesson',
    'McKinsey & Company',
    'Medtronic',
    'Mercadona',
    'Mercer',
    'Merck',
    'Merck KGaA',
    'Meta',
    'Meta Platforms',
    'MetLife',
    'Micron Technology',
    'Microsoft',
    'MIT',
    'Mitsubishi Heavy Industries',
    'Mitsubishi UFJ',
    'Mizuho Financial',
    'Moderna',
    'Molina Healthcare',
    'Mondelez International',
    'MongoDB',
    'Morgan Stanley',
    'Mount Sinai Health System',
    'MUFG Bank',
    'NASA',
    'National Australia Bank',
    'National Bank of Canada',
    'National Bank of Egypt',
    'National Bank of Kuwait',
    'National Grid',
    'National Health Service',
    'NatWest Group',
    'Nedbank',
    'NetApp',
    'Netflix',
    'Netlify',
    'New York Life',
    'New York University Langone',
    'NewYork-Presbyterian',
    'NextEra Energy',
    'NIH',
    'Nike',
    'Nintendo',
    'Nippon Steel',
    'Nissan',
    'Nokia',
    'Nomura Holdings',
    'Nordea Bank',
    'Northrop Grumman',
    'Novartis',
    'Novo Nordisk',
    'NVIDIA',
    'Okta',
    'Oliver Wyman',
    'Oman National Bank',
    'ONGC',
    'Oracle',
    'Otsuka',
    'Owens & Minor',
    'Palo Alto Networks',
    'Panasonic',
    'Paramount Global',
    'PayPal',
    'PEMEX',
    'PepsiCo',
    'Petrobras',
    'PetroChina',
    'Pfizer',
    'Philips Healthcare',
    'Ping An Insurance',
    'Pinterest',
    'PNC Financial Services',
    'Princeton',
    'Procter & Gamble',
    'Providence Health',
    'Prudential Financial',
    'Prudential plc',
    'PwC',
    'Qatar National Bank',
    'QBE Insurance',
    'Qualcomm',
    'Quest Diagnostics',
    'Rabobank',
    'Raytheon',
    'Raytheon Technologies',
    'Red Hat',
    'Regeneron',
    'Reliance Industries',
    'Reliance Retail',
    'Riyad Bank',
    'Roche',
    'Rockwell Automation',
    'Roland Berger',
    'Royal Bank of Canada',
    'Royal Caribbean',
    'RTL Group',
    'RWE',
    's',
    'S&P Global',
    'Salesforce',
    'Samsung',
    'Samsung Electronics',
    'Sanlam',
    'Sanofi',
    'SAP',
    'Sasol',
    'Saudi Aramco',
    'Saudi National Bank',
    'Schneider Electric',
    'Sears',
    'SEB',
    'Sephora',
    'ServiceNow',
    'Seven & i Holdings',
    'Sharp',
    'Shell',
    'Shopify',
    'Siemens',
    'Siemens Healthineers',
    'Singapore Airlines',
    'Sinopec',
    'Snowflake',
    'Societe Generale',
    'Sony',
    'Sony Pictures',
    'Southern Company',
    'Southwest Airlines',
    'SpaceX',
    'Splunk',
    'Spotify',
    'St. Jude Children\'s Research Hospital',
    'Standard Bank',
    'Standard Chartered',
    'Stanford University',
    'State Bank of India',
    'State Farm',
    'State Street',
    'Stripe',
    'Stryker',
    'Sumitomo Mitsui',
    'Suncorp',
    'Sutter Health',
    'Swedbank',
    'Swiss Re',
    'Synopsys',
    'Takeda Pharmaceutical',
    'Target',
    'Tata Consultancy Services',
    'Tech Startup Inc',
    'Tencent',
    'Tesco',
    'Tesla',
    'Texas Instruments',
    'The Walt Disney Company',
    'Thermo Fisher Scientific',
    'Tokyo Electric Power',
    'Toronto-Dominion Bank',
    'Toshiba',
    'TotalEnergies',
    'Toyota',
    'Trinity Health',
    'TSMC',
    'Twilio',
    'Twitter',
    'U.S. Bancorp',
    'UBS',
    'UC Berkeley',
    'UCLA',
    'UniCredit',
    'Unilever',
    'United Airlines',
    'United Nations',
    'UnitedHealth Group',
    'Universal Music Group',
    'University of California',
    'University of Michigan',
    'University of Texas',
    'UPMC',
    'UPS',
    'US Army',
    'US Navy',
    'US Postal Service',
    'Vanguard Group',
    'Vercel',
    'Verizon',
    'Vertex Pharmaceuticals',
    'Visa',
    'Vivendi',
    'VMware',
    'Volkswagen',
    'Walgreens Boots Alliance',
    'Walmart',
    'Warner Bros. Discovery',
    'Wellcome Trust',
    'Wells Fargo',
    'Western Digital',
    'Westpac',
    'Willis Towers Watson',
    'Wipro',
    'Woolworths Group',
    'Workday',
    'World Bank',
    'Wyndham Hotels',
    'Yale',
    'Zara (Inditex)',
    'Zillow',
    'Zimmer Biomet',
    'Zoom',
  ],

  universities: [
    'Aalto University',
    'Aarhus University',
    'Air Force Academy',
    'American University in Cairo',
    'American University of Beirut',
    'Amherst College',
    'Annapolis',
    'Arizona State University',
    'Australian National University',
    'Autonomous University of Barcelona',
    'Bates College',
    'Berklee College of Music',
    'Boise State University',
    'Boston College',
    'Boston University',
    'Bowdoin College',
    'Brandeis University',
    'Brown University',
    'Bryn Mawr College',
    'Cairo University',
    'California Institute of Technology',
    'Cardiff University',
    'Carleton College',
    'Carnegie Mellon University',
    'Case Western Reserve University',
    'Charles University',
    'Chinese University of Hong Kong',
    'Claremont Graduate University',
    'Claremont McKenna College',
    'Colby College',
    'Colgate University',
    'College of William & Mary',
    'Colorado College',
    'Columbia University',
    'Complutense University of Madrid',
    'Cornell University',
    'Dartmouth College',
    'Davidson College',
    'Delft University of Technology',
    'Duke University',
    'Ecole Normale Supérieure',
    'Ecole Polytechnique',
    'Emory University',
    'Eotvos Lorand University',
    'EPFL',
    'ETH Zurich',
    'European University Institute',
    'Federal University of Rio de Janeiro',
    'Freie Universitaet Berlin',
    'Fudan University',
    'Georgetown University',
    'Georgia Institute of Technology',
    'Ghent University',
    'Gothenburg University',
    'Grinnell College',
    'Hamilton College',
    'Harvard University',
    'Harvey Mudd College',
    'Haverford College',
    'Heidelberg University',
    'Hong Kong University of Science and Technology',
    'Humboldt University of Berlin',
    'IISER Pune',
    'Imperial College London',
    'Indian Institute of Science',
    'Indian Institute of Science, Bangalore',
    'Indian Institute of Technology Bombay',
    'Indian Institute of Technology Delhi',
    'Indian Institute of Technology Kanpur',
    'Indian Institute of Technology Madras',
    'International Autonomous University of Mexico',
    'Jagiellonian University',
    'Johns Hopkins University',
    'KAIST',
    'Karolinska Institute',
    'Kenyon College',
    'Khalifa University',
    'King Abdullah University of Science and Technology',
    'King Fahd University of Petroleum and Minerals',
    'King Saud University',
    'King\'s College London',
    'Korea Advanced Institute of Science and Technology',
    'Korea University',
    'KTH Royal Institute of Technology',
    'KU Leuven',
    'Kyoto University',
    'Lehigh University',
    'Leiden University',
    'Linkoping University',
    'London School of Economics',
    'Ludwig Maximilian University of Munich',
    'Lund University',
    'Macalester College',
    'Macquarie University',
    'Makerere University',
    'Massachusetts Institute of Technology',
    'McGill University',
    'McMaster University',
    'Michigan State University',
    'Middlebury College',
    'MIT',
    'Monash University',
    'Monterrey Institute of Technology',
    'Monterrey Institute of Technology and Higher Education',
    'Nanyang Technological University',
    'National Autonomous University of Mexico',
    'National Taiwan University',
    'National University of Colombia',
    'National University of Singapore',
    'New York University',
    'Newcastle University',
    'Northeastern University',
    'Northwestern University',
    'Norwegian University of Science and Technology',
    'Oberlin College',
    'Ohio State University',
    'Osaka University',
    'Peking University',
    'Pennsylvania State University',
    'Pomona College',
    'Pontifical Catholic University of Chile',
    'Princeton University',
    'Purdue University',
    'Queen\'s University',
    'Queen\'s University Belfast',
    'Rensselaer Polytechnic Institute',
    'Rice University',
    'Rutgers University',
    'Sapienza University of Rome',
    'Sciences Po',
    'Seoul National University',
    'Shanghai Jiao Tong University',
    'Simon Fraser University',
    'Smith College',
    'Sorbonne University',
    'Stanford University',
    'State University of Campinas',
    'Stellenbosch University',
    'Stockholm University',
    'Swarthmore College',
    'Syracuse University',
    'Technical University of Munich',
    'Technion - Israel Institute of Technology',
    'Tel Aviv University',
    'Tokyo Institute of Technology',
    'Trinity College Dublin',
    'Tsinghua University',
    'TU Berlin',
    'Tufts University',
    'Tulane University',
    'UCLA',
    'Umea University',
    'United Arab Emirates University',
    'Universite Paris-Saclay',
    'University College Dublin',
    'University College London',
    'University of Adelaide',
    'University of Alberta',
    'University of Amsterdam',
    'University of Andes',
    'University of Antwerp',
    'University of Arizona',
    'University of Athens',
    'University of Auckland',
    'University of Barcelona',
    'University of Basel',
    'University of Bath',
    'University of Belgrade',
    'University of Bergen',
    'University of Bern',
    'University of Birmingham',
    'University of Bologna',
    'University of Bristol',
    'University of British Columbia',
    'University of Buenos Aires',
    'University of Calgary',
    'University of California, Berkeley',
    'University of California, Los Angeles',
    'University of California, San Diego',
    'University of California, Santa Barbara',
    'University of Cambridge',
    'University of Cape Town',
    'University of Chicago',
    'University of Chile',
    'University of Coimbra',
    'University of Cologne',
    'University of Colorado Boulder',
    'University of Copenhagen',
    'University of Durham',
    'University of Eastern Finland',
    'University of Edinburgh',
    'University of Exeter',
    'University of Florida',
    'University of Freiburg',
    'University of Geneva',
    'University of Georgia',
    'University of Glasgow',
    'University of Goettingen',
    'University of Helsinki',
    'University of Hong Kong',
    'University of Ibadan',
    'University of Iceland',
    'University of Illinois at Urbana-Champaign',
    'University of Illinois Urbana-Champaign',
    'University of Leeds',
    'University of Liege',
    'University of Lisbon',
    'University of Liverpool',
    'University of Ljubljana',
    'University of Manchester',
    'University of Maryland',
    'University of Melbourne',
    'University of Miami',
    'University of Michigan',
    'University of Michigan, Ann Arbor',
    'University of Milan',
    'University of Minnesota',
    'University of Montreal',
    'University of Muenster',
    'University of Nairobi',
    'University of New South Wales',
    'University of Nicosia',
    'University of North Carolina at Chapel Hill',
    'University of Notre Dame',
    'University of Nottingham',
    'University of Oslo',
    'University of Otago',
    'University of Ottawa',
    'University of Oulu',
    'University of Oxford',
    'University of Paris (Sorbonne)',
    'University of Pennsylvania',
    'University of Pittsburgh',
    'University of Porto',
    'University of Pretoria',
    'University of Queensland',
    'University of Rochester',
    'University of Sao Paulo',
    'University of Science and Technology of China',
    'University of Sheffield',
    'University of Southampton',
    'University of Southern California',
    'University of Stuttgart',
    'University of Sydney',
    'University of São Paulo',
    'University of Tampere',
    'University of Tartu',
    'University of Technology Sydney',
    'University of Texas at Austin',
    'University of the Witwatersrand',
    'University of Tokyo',
    'University of Toronto',
    'University of Turku',
    'University of Utah',
    'University of Vienna',
    'University of Virginia',
    'University of Warsaw',
    'University of Warwick',
    'University of Washington',
    'University of Waterloo',
    'University of Western Australia',
    'University of Wisconsin-Madison',
    'University of York',
    'University of Zagreb',
    'University of Zurich',
    'Uppsala University',
    'Utrecht University',
    'Vanderbilt University',
    'Vassar College',
    'Vienna University of Technology',
    'Vilnius University',
    'Wake Forest University',
    'Washington University in St. Louis',
    'Wellesley College',
    'Wesleyan University',
    'Western University',
    'Williams College',
    'Yale University',
    'Yonsei University',
    'Zhejiang University',
    'École Polytechnique',
  ],

  degrees: [
    'Abitur',
    'Advanced Level (A-Level)',
    'Associate of Applied Science',
    'Associate of Arts',
    'Associate of Science',
    'Baccalaureate',
    'Bachelor of Applied Science',
    'Bachelor of Arts',
    'Bachelor of Business Administration',
    'Bachelor of Computer Science',
    'Bachelor of Education',
    'Bachelor of Engineering',
    'Bachelor of Fine Arts',
    'Bachelor of Laws',
    'Bachelor of Medicine',
    'Bachelor of Medicine, Bachelor of Surgery',
    'Bachelor of Science',
    'Bachelor of Science in Nursing',
    'Certificate',
    'Diploma',
    'Doctor of Dental Surgery',
    'Doctor of Education',
    'Doctor of Medicine',
    'Doctor of Nursing Practice',
    'Doctor of Pharmacy',
    'Doctor of Philosophy',
    'Doctor of Psychology',
    'Doctor of Public Health',
    'Doctor of Science',
    'Doctor of Veterinary Medicine',
    'General Certificate of Secondary Education (GCSE)',
    'High School Certificate',
    'High School Diploma',
    'Higher National Certificate',
    'Higher National Diploma',
    'Higher National Diploma (HND)',
    'International Baccalaureate',
    'International General Certificate of Secondary Education (IGCSE)',
    'Juris Doctor',
    'Master of Arts',
    'Master of Business Administration',
    'Master of Computer Science',
    'Master of Education',
    'Master of Engineering',
    'Master of Fine Arts',
    'Master of Laws',
    'Master of Public Administration',
    'Master of Public Health',
    'Master of Science',
    'Master of Social Work',
    'Matura',
    'National Vocational Qualification',
    'National Vocational Qualification (NVQ)',
    'PharmD',
    'Professional Engineer (PE) License',
  ],

  fieldsOfStudy: [
    'Accounting',
    'Actuarial Science',
    'Aerospace Engineering',
    'African American Studies',
    'Agricultural Engineering',
    'Agricultural Sciences',
    'Agriculture',
    'Alternative Dispute Resolution',
    'Anthropology',
    'Applied Mathematics',
    'Archaeology',
    'Architecture',
    'Art History',
    'Artificial Intelligence',
    'Astrobiology',
    'Astronomy',
    'Biochemistry',
    'Bioinformatics',
    'Biology',
    'Biomedical Engineering',
    'Biomedical Sciences',
    'Biostatistics',
    'Biotechnology',
    'Business Administration',
    'Carpentry',
    'Chemical Engineering',
    'Chemistry',
    'Child Development',
    'Civil Engineering',
    'Classics',
    'Clinical Psychology',
    'Cloud Computing',
    'Cognitive Science',
    'Communication',
    'Communication Studies',
    'Communications',
    'Comparative Literature',
    'Computer Engineering',
    'Computer Science',
    'Construction Management',
    'Creative Writing',
    'Criminal Justice',
    'Criminology',
    'Culinary Arts',
    'Cybersecurity',
    'Dance',
    'Data Analytics',
    'Data Science',
    'Dental Hygiene',
    'Dentistry',
    'Design',
    'Development Studies',
    'Dietetics',
    'Drama',
    'Early Childhood Education',
    'Earth Sciences',
    'Ecology',
    'Econometrics',
    'Economics',
    'Education',
    'Electrical Engineering',
    'Elementary Education',
    'Emergency Medical Services',
    'Engineering',
    'Engineering Management',
    'English',
    'English Literature',
    'Environmental Engineering',
    'Environmental Science',
    'Epidemiology',
    'Ethnic Studies',
    'Family and Consumer Sciences',
    'Film Production',
    'Film Studies',
    'Finance',
    'Fine Arts',
    'Food Science',
    'Forensic Science',
    'French',
    'Game Development',
    'Gender Studies',
    'General Studies',
    'Genetics',
    'Geography',
    'Geology',
    'Graphic Design',
    'Health Administration',
    'Health Sciences',
    'History',
    'Hospitality Management',
    'Human Resources',
    'Human-Computer Interaction',
    'Humanities',
    'Industrial Design',
    'Industrial Engineering',
    'Information Systems',
    'Information Technology',
    'Interdisciplinary Studies',
    'Interior Design',
    'International Relations',
    'Journalism',
    'Kinesiology',
    'Landscape Architecture',
    'Law',
    'Legal Studies',
    'Liberal Arts',
    'Linguistics',
    'Literature',
    'Logistics',
    'Machine Learning',
    'Management',
    'Marine Biology',
    'Marketing',
    'Materials Science',
    'Mathematics',
    'Mechanical Engineering',
    'Mechatronics',
    'Media Studies',
    'Medical Laboratory Science',
    'Medicine',
    'Microbiology',
    'Music',
    'Network Engineering',
    'Neuroscience',
    'Nursing',
    'Nutrition',
    'Occupational Therapy',
    'Operations Management',
    'Optometry',
    'Organizational Leadership',
    'Petroleum Engineering',
    'Pharmacology',
    'Pharmacy',
    'Philosophy',
    'Photography',
    'Physical Education',
    'Physical Therapy',
    'Physics',
    'Political Science',
    'Pre-Law',
    'Pre-Medicine',
    'Psychology',
    'Public Administration',
    'Public Health',
    'Public Policy',
    'Religious Studies',
    'Respiratory Therapy',
    'Robotics',
    'Social Sciences',
    'Social Work',
    'Sociology',
    'Software Engineering',
    'Spanish',
    'Special Education',
    'Statistics',
    'Supply Chain Management',
    'Sustainability',
    'Telecommunications',
    'Theater',
    'Theatre',
    'Theology',
    'Tourism',
    'Urban Planning',
    'Veterinary Science',
    'Visual Arts',
    'Welding',
    'Women\'s Studies',
  ],

  skills: {
    programming: [
      'Ada',
      'Apex',
      'Assembly',
      'Bash',
      'BASIC',
      'C',
      'C#',
      'C++',
      'Clojure',
      'COBOL',
      'Crystal',
      'CSS',
      'CSS3',
      'Dart',
      'Elixir',
      'Erlang',
      'F#',
      'Fortran',
      'Gleam',
      'Go',
      'GraphQL',
      'Groovy',
      'Haskell',
      'HTML',
      'HTML5',
      'Java',
      'JavaScript',
      'JSON',
      'Julia',
      'Kotlin',
      'Lisp',
      'Lua',
      'MATLAB',
      'Mojo',
      'Nim',
      'NoSQL',
      'Objective-C',
      'Perl',
      'PHP',
      'PL/SQL',
      'PowerShell',
      'Prolog',
      'Python',
      'R',
      'Racket',
      'REST API',
      'Ruby',
      'Rust',
      'SAS',
      'Scala',
      'Scheme',
      'Shell Scripting',
      'Smalltalk',
      'Solidity',
      'SQL',
      'Swift',
      'TypeScript',
      'Visual Basic',
      'Vyper',
      'XML',
      'Zig',
    ],
    frontend: [
      'Alpine.js',
      'Angular',
      'Ant Design',
      'Apollo Client',
      'Babel',
      'Bootstrap',
      'Bulma',
      'Chakra UI',
      'Chart.js',
      'CSS',
      'D3.js',
      'Ember.js',
      'Ethers.js',
      'Foundation',
      'Framer Motion',
      'Gatsby',
      'GraphQL',
      'Highcharts',
      'HTML',
      'HTML Canvas',
      'Ionic',
      'jQuery',
      'jQuery UI',
      'Leaflet',
      'LESS',
      'Lit',
      'Material-UI',
      'MobX',
      'Next.js',
      'npm',
      'Nuxt.js',
      'pnpm',
      'PostCSS',
      'Preact',
      'React',
      'React.js',
      'Recoil',
      'Redux',
      'RxJS',
      'Sass',
      'Semantic UI',
      'Sencha ExtJS',
      'SolidJS',
      'Stencil',
      'Svelte',
      'SVG',
      'Tailwind CSS',
      'Three.js',
      'Vite',
      'Vue.js',
      'Web3.js',
      'WebAssembly',
      'Webpack',
      'XState',
      'Yarn',
      'Zustand',
    ],
    backend: [
      'ActiveRecord',
      'AdonisJS',
      'Ansible',
      'Apache Ant',
      'API Gateway',
      'ASP.NET',
      'ASP.NET Core',
      'AWS CloudFormation',
      'Bun',
      'Caching',
      'Chef',
      'CI/CD',
      'Controller',
      'Deno',
      'Django',
      'Docker',
      'Echo',
      'Elixir',
      'Event-Driven Architecture',
      'Express.js',
      'FastAPI',
      'Fastify',
      'Fiber',
      'Flask',
      'Gin',
      'GraphQL',
      'gRPC',
      'Hibernate',
      'HPUX',
      'IBM Integration Bus',
      'IBM MQ',
      'IBM WebSphere',
      'JMS',
      'JWT',
      'Kafka',
      'Koa',
      'Kubernetes',
      'Laravel',
      'LDAP',
      'LINQ',
      'LoopBack',
      'Mercurial',
      'Message Queuing (RabbitMQ)',
      'Microservices',
      'Microsoft Azure',
      'Microsoft IIS',
      'Microsoft SQL Server',
      'Microsoft Windows Server',
      'Mono',
      'Multithreading',
      'MVC',
      'MySQL',
      'NestJS',
      'Node.js',
      'NoSQL',
      'OAuth',
      'OAuth 2.0',
      'Object-Oriented Programming',
      'OCaml',
      'OpenShift',
      'Oracle',
      'Pascal',
      'Perl',
      'Phoenix',
      'PostgreSQL',
      'PowerShell',
      'REST',
      'REST API',
      'REST APIs',
      'Ruby on Rails',
      'Security',
      'Serverless',
      'Shell Scripting',
      'SOAP',
      'Spring',
      'Spring Boot',
      'Struts',
      'Symfony',
      'TensorFlow',
      'Terraform',
      'Tomcat',
      'Web API',
      'WebSockets',
    ],
    databases: [
      'Amazon DynamoDB',
      'Amazon RDS',
      'Amazon Redshift',
      'ArangoDB',
      'Cassandra',
      'ChromaDB',
      'ClickHouse',
      'Couchbase',
      'CouchDB',
      'DynamoDB',
      'Elasticsearch',
      'Faiss',
      'Firebase',
      'Firebase Realtime Database',
      'Firestore',
      'Google BigQuery',
      'Google Cloud Bigtable',
      'IBM Db2',
      'InfluxDB',
      'MariaDB',
      'Microsoft SQL Server',
      'Milvus',
      'MongoDB',
      'MySQL',
      'Neo4j',
      'NoSQL',
      'Oracle',
      'Oracle Database',
      'Pinecone',
      'PostgreSQL',
      'Prometheus',
      'Qdrant',
      'Redis',
      'SingleStore',
      'Snowflake',
      'SQLite',
      'Supabase',
      'TimescaleDB',
      'VoltDB',
      'Weaviate',
    ],
    cloud: [
      'Amazon Aurora',
      'Amazon CloudFront',
      'Amazon CloudWatch',
      'Amazon DynamoDB',
      'Amazon EC2',
      'Amazon ECS',
      'Amazon EKS',
      'Amazon Elastic Beanstalk',
      'Amazon Lambda',
      'Amazon RDS',
      'Amazon Redshift',
      'Amazon Route 53',
      'Amazon S3',
      'Amazon SNS',
      'Amazon SQS',
      'Amazon VPC',
      'Amazon Web Services',
      'Apple iCloud',
      'AWS',
      'AWS CloudFormation',
      'AWS EC2',
      'AWS ECS',
      'AWS EKS',
      'AWS Fargate',
      'AWS IAM',
      'AWS Lambda',
      'AWS RDS',
      'AWS S3',
      'Azure',
      'Azure Active Directory',
      'Azure App Service',
      'Azure Blob Storage',
      'Azure Cosmos DB',
      'Azure Data Lake',
      'Azure DevOps',
      'Azure Functions',
      'Azure Kubernetes Service',
      'Azure SQL Database',
      'Azure Virtual Machines',
      'Cloud Functions',
      'Cloudflare Workers',
      'CloudFormation',
      'DigitalOcean',
      'Docker',
      'GCP',
      'Google App Engine',
      'Google BigQuery',
      'Google Cloud BigQuery',
      'Google Cloud Firestore',
      'Google Cloud Functions',
      'Google Cloud IAM',
      'Google Cloud Platform',
      'Google Cloud Run',
      'Google Cloud Spanner',
      'Google Cloud SQL',
      'Google Cloud Storage',
      'Google Compute Engine',
      'Google Firestore',
      'Google Kubernetes Engine',
      'Google Pub/Sub',
      'Helm',
      'Heroku',
      'IBM Cloud',
      'Kubernetes',
      'Lambda',
      'Linode',
      'Microsoft Azure',
      'Netlify',
      'OpenStack',
      'Oracle Cloud Infrastructure',
      'Salesforce',
      'Serverless',
      'Terraform',
      'Terraform Cloud',
      'Vercel',
      'VMware Cloud',
    ],
    devops: [
      'Ansible',
      'Apache HTTP Server',
      'Argo CD',
      'Argo Workflows',
      'ArgoCD',
      'Azure DevOps',
      'Bamboo',
      'Chef',
      'CircleCI',
      'Consul',
      'Datadog',
      'Docker',
      'ELK Stack',
      'Git',
      'GitHub Actions',
      'GitLab CI',
      'GitLab CI/CD',
      'Gradle',
      'Grafana',
      'HAProxy',
      'Helm',
      'Istio',
      'Jenkins',
      'Kubernetes',
      'Linkerd',
      'Maven',
      'Nagios',
      'New Relic',
      'Nginx',
      'OpenShift',
      'Packer',
      'PagerDuty',
      'Prometheus',
      'Pulumi',
      'Puppet',
      'SonarQube',
      'Splunk',
      'TeamCity',
      'Terraform',
      'Traefik',
      'Travis CI',
      'Vagrant',
      'Vault',
      'VictorOps',
      'WebLogic',
    ],
    tools: [
      'Adobe Creative Cloud',
      'Adobe Illustrator',
      'Adobe Photoshop',
      'Adobe XD',
      'Android Studio',
      'Asana',
      'Atom',
      'AutoCAD',
      'Azure Data Studio',
      'Azure DevOps',
      'Bitbucket',
      'Canva',
      'Chrome DevTools',
      'ClickUp',
      'Confluence',
      'Docker Compose',
      'Docker Desktop',
      'Eclipse',
      'Emacs',
      'Excel',
      'Figma',
      'GIMP',
      'Git',
      'GitHub',
      'GitLab',
      'Google Analytics',
      'Google Workspace',
      'Illustrator',
      'Insomnia',
      'IntelliJ IDEA',
      'Jira',
      'JMeter',
      'LaTeX',
      'Linear',
      'Microsoft Office',
      'Microsoft Teams',
      'Miro',
      'Notion',
      'Photoshop',
      'Postman',
      'Power BI',
      'PyCharm',
      'Sketch',
      'Slack',
      'Sublime Text',
      'Tableau',
      'Trello',
      'Vim',
      'Visual Studio',
      'Visual Studio Code',
      'VS Code',
      'WebStorm',
      'Wix',
      'WordPress',
      'Xcode',
      'Zoom',
    ],
    frameworks: [
      'Android SDK',
      'Angular',
      'Apache Cordova',
      'ASP.NET Core',
      'Bootstrap',
      'Capacitor',
      'Chai',
      'Cordova',
      'Cypress',
      'Django',
      'Electron',
      'Express.js',
      'FastAPI',
      'Flask',
      'Flutter',
      'GNU Octave',
      'Hadoop',
      'Hive',
      'Ionic',
      'Jest',
      'JUnit',
      'Keras',
      'Laravel',
      'Mocha',
      'NestJS',
      'Next.js',
      'Node.js',
      'NUnit',
      'Nuxt.js',
      'OpenCV',
      'Playwright',
      'PyTest',
      'PyTorch',
      'Qt',
      'React',
      'React Native',
      'Robot Framework',
      'RSpec',
      'Ruby on Rails',
      'Selenium',
      'Spring Boot',
      'Svelte',
      'Tauri',
      'TensorFlow',
      'Vue.js',
      'Xamarin',
    ],
    methodologies: [
      'Agile',
      'BDD',
      'Behavior-Driven Development',
      'CI/CD',
      'CMMI',
      'COBIT',
      'Code Review',
      'Continuous Deployment',
      'Continuous Integration',
      'Design Thinking',
      'DevOps',
      'DevSecOps',
      'Discipline Agile Delivery (DAD)',
      'DMAIC',
      'Domain-Driven Design',
      'Extreme Programming',
      'Extreme Programming (XP)',
      'Functional Programming',
      'GitFlow',
      'ISO 9001',
      'ITIL',
      'Kanban',
      'Lean',
      'Microservices',
      'Microservices Architecture',
      'Object-Oriented Programming',
      'Pair Programming',
      'PMBOK',
      'PMP',
      'PRINCE2',
      'PRINCE2 Agile',
      'Rapid Application Development (RAD)',
      'RESTful Design',
      'RUP',
      'SAFe',
      'Scrum',
      'Service-Oriented Architecture',
      'Six Sigma',
      'SOA',
      'Spiral model',
      'TDD',
      'TDD (Test-Driven Development)',
      'Test-Driven Development',
      'Trunk-Based Development',
      'Waterfall',
    ],
    softSkills: [
      'Accountability',
      'Active listening',
      'Adaptability',
      'Analytical Thinking',
      'Attention to detail',
      'Collaboration',
      'Communication',
      'Conflict Resolution',
      'Creativity',
      'Critical Thinking',
      'Customer Service',
      'Decision making',
      'Emotional intelligence',
      'Empathy',
      'Flexibility',
      'Initiative',
      'Interpersonal skills',
      'Leadership',
      'Mentoring',
      'Multitasking',
      'Negotiation',
      'Organization',
      'Patience',
      'Presentation',
      'Presentation Skills',
      'Problem Solving',
      'Project Management',
      'Public Speaking',
      'Punctuality',
      'Reliability',
      'Self-motivation',
      'Stakeholder Management',
      'Strategic Thinking',
      'Stress management',
      'Team Management',
      'Teamwork',
      'Time Management',
      'Work Ethic',
    ],
  },

  certifications: [
    'AAMA Medical Assistant',
    'ACLS',
    'ACLS (Advanced Cardiovascular Life Support)',
    'Adobe Certified Expert',
    'Adobe Certified Professional',
    'Adult-Gerontology Primary Care Nurse Practitioner',
    'Advanced Cardiac Life Support (ACLS)',
    'Advanced Cardiovascular Life Support',
    'AHA ACLS',
    'AHA BLS',
    'Airline Transport Pilot License',
    'ANCC Certified Nurse',
    'APICS Certified Supply Chain Professional',
    'APM Project Professional',
    'Apple Certified iOS App Developer',
    'ARRT (Registered Radiologic Technologist)',
    'Aruba Certified Switching Associate',
    'Associate in Risk Management',
    'Associate Professional in Human Resources',
    'Associate Safety Professional',
    'AWS Certified Advanced Networking – Specialty',
    'AWS Certified AI Practitioner',
    'AWS Certified Cloud Practitioner',
    'AWS Certified Data Analytics – Specialty',
    'AWS Certified Data Engineer',
    'AWS Certified Database – Specialty',
    'AWS Certified Developer – Associate',
    'AWS Certified DevOps Engineer',
    'AWS Certified DevOps Engineer – Professional',
    'AWS Certified Machine Learning – Specialty',
    'AWS Certified SAP on AWS – Specialty',
    'AWS Certified Security – Specialty',
    'AWS Certified Solutions Architect – Associate',
    'AWS Certified Solutions Architect – Professional',
    'AWS Certified SysOps Administrator – Associate',
    'AWS Developer Associate',
    'AWS Solutions Architect',
    'AWS SysOps Administrator',
    'Bar Admission',
    'Bar Admission (State Bar)',
    'Barrister (Bar Admission)',
    'Basic Life Support',
    'BLS/CPR',
    'Bluetooth Certified Product Developer',
    'Board Certified Behavior Analyst (BCBA)',
    'CAPM',
    'CCIE',
    'CCNA',
    'CCNP',
    'CCSP (ISC2)',
    'CCSP - Certified Cloud Security Professional',
    'CEH - Certified Ethical Hacker',
    'Certified AI Governance Professional',
    'Certified Anti-Money Laundering Specialist',
    'Certified Associate in Project Management',
    'Certified Associate in Project Management (CAPM)',
    'Certified Case Manager (CCM)',
    'Certified Clinical Research Professional',
    'Certified Coding Associate',
    'Certified Coding Specialist',
    'Certified Compensation Professional',
    'Certified EKG Technician',
    'Certified Financial Planner',
    'Certified Financial Planner (CFP)',
    'Certified Financial Services Auditor',
    'Certified Fraud Examiner',
    'Certified Health Education Specialist',
    'Certified Healthcare Constructor',
    'Certified Healthcare Environmental Services Professional',
    'Certified Healthcare Financial Professional',
    'Certified Healthcare Safety Professional',
    'Certified in Risk and Information Systems Control (CRISC)',
    'Certified Information Privacy Manager',
    'Certified Information Privacy Professional',
    'Certified Information Systems Auditor',
    'Certified Information Systems Manager',
    'Certified Information Systems Security Professional (CISSP)',
    'Certified Internal Auditor',
    'Certified Kubernetes Administrator',
    'Certified Kubernetes Administrator (CKA)',
    'Certified Kubernetes Application Developer (CKAD)',
    'Certified Kubernetes Developer',
    'Certified Kubernetes Security Specialist',
    'Certified Management Accountant',
    'Certified Medical Assistant',
    'Certified Medical Assistant (CMA)',
    'Certified Medical Office Manager',
    'Certified Medical Practice Executive',
    'Certified Medication Aide (CMA)',
    'Certified Nurse Assistant',
    'Certified Nursing Assistant (CNA)',
    'Certified Paralegal',
    'Certified Patient Care Technician',
    'Certified Pharmacy Technician',
    'Certified Phlebotomy Technician',
    'Certified Phlebotomy Technician (CPT)',
    'Certified Product Owner',
    'Certified Professional in Healthcare Quality',
    'Certified Professional in Patient Safety',
    'Certified Public Accountant',
    'Certified Quality Auditor',
    'Certified Regulatory Compliance Manager',
    'Certified Safety Professional',
    'Certified Scrum Product Owner',
    'Certified Scrum Professional',
    'Certified ScrumMaster',
    'Certified Surgical Technologist',
    'Certified Treasury Professional',
    'Certified Tumor Registrar',
    'Certified Welder',
    'CGEIT - Certified in the Governance of Enterprise IT',
    'Chartered Accountant',
    'Chartered Alternative Investment Analyst',
    'Chartered Alternative Investment Analyst (CAIA)',
    'Chartered Financial Analyst',
    'Chartered Global Management Accountant',
    'Chartered Property Casualty Underwriter',
    'Check Point Certified Security Administrator',
    'CHFI - Computer Hacking Forensic Investigator',
    'CIA (Certified Internal Auditor)',
    'CIH (GIAC Certified Incident Handler)',
    'CISA (ISC2)',
    'Cisco CCAr',
    'Cisco CCIE',
    'Cisco CCNA',
    'Cisco CCNP',
    'Cisco Certified DevNet Associate',
    'Cisco Certified DevNet Professional',
    'Cisco Certified Internetwork Expert',
    'Cisco Certified Network Associate',
    'Cisco Certified Network Professional Collaboration',
    'Cisco Certified Network Professional Data Center',
    'Cisco Certified Network Professional Enterprise',
    'Cisco Certified Network Professional Security',
    'Cisco Certified Network Professional Service Provider',
    'Cisco Certified Support Technician',
    'CISM',
    'CISM (Certified Information Security Manager)',
    'CISM (ISC2)',
    'CISSP',
    'CISSP - Certified Information Systems Security Professional',
    'Citrix Certified Associate',
    'CLSSBB (Lean Six Sigma Black Belt)',
    'CLSSGB (Lean Six Sigma Green Belt)',
    'CMA (Certified Management Accountant)',
    'Commercial Driver\'s License Class A',
    'Commercial Driver\'s License Class B',
    'CompTIA A+',
    'CompTIA CASP+',
    'CompTIA Cloud Essentials+',
    'CompTIA Cloud+',
    'CompTIA CySA+',
    'CompTIA Data+',
    'CompTIA DataSys+',
    'CompTIA Linux+',
    'CompTIA Network+',
    'CompTIA PenTest+',
    'CompTIA Project+',
    'CompTIA Security Analytics Professional',
    'CompTIA Security+',
    'CompTIA Server+',
    'CPA (Certified Public Accountant)',
    'CPHQ',
    'CRISC - Certified in Risk and Information Systems Control',
    'CSM (Certified ScrumMaster)',
    'CSPO',
    'CSPO (Certified Scrum Product Owner)',
    'DA-100 (Microsoft Certified: Data Analyst)',
    'Datadog Certified Professional',
    'Docker Certified Associate',
    'EKG Technician Certification',
    'EMT',
    'Enrolled Agent (EA)',
    'EPA Section 608 Technician Certification',
    'Family Nurse Practitioner',
    'Family Nurse Practitioner (FNP-BC)',
    'Financial Risk Manager',
    'Forklift Operator Certification',
    'Fortinet Network Security Expert',
    'FRM',
    'FRM (Financial Risk Manager)',
    'GCED (Google Certified Educator Level 1)',
    'GCED (Google Certified Educator Level 2)',
    'GCIA (GIAC Certified Intrusion Analyst)',
    'GIAC Certified Forensic Analyst',
    'GIAC Certified Incident Handler',
    'GIAC GCFA',
    'GiAC GPEN (Certified Penetration Tester)',
    'GIAC Offensive AI Analyst',
    'GIAC Penetration Tester',
    'GIAC Security Essentials',
    'GIAC Security Essentials (GSEC)',
    'GIAC Security Leadership',
    'Global Professional in Human Resources',
    'Google Ads Display Certification',
    'Google Ads Search Certification',
    'Google Analytics Individual Qualification',
    'Google Associate Cloud Engineer',
    'Google Cloud Associate Engineer',
    'Google Cloud Certified Associate Cloud Engineer',
    'Google Cloud Certified Professional Cloud Architect',
    'Google Cloud Certified Professional Cloud Database Engineer',
    'Google Cloud Certified Professional Cloud Developer',
    'Google Cloud Certified Professional Cloud DevOps Engineer',
    'Google Cloud Certified Professional Cloud Network Engineer',
    'Google Cloud Certified Professional Cloud Security Engineer',
    'Google Cloud Certified Professional Data Engineer',
    'Google Cloud Certified Professional Machine Learning Engineer',
    'Google Cloud Digital Leader',
    'Google Cloud Professional',
    'Google Cloud Professional Cloud Architect',
    'Google Cloud Professional Data Engineer',
    'Google Professional Cloud Architect',
    'Google Professional Cloud Database Engineer',
    'Google Professional Cloud Developer',
    'Google Professional Cloud DevOps Engineer',
    'Google Professional Cloud Network Engineer',
    'Google Professional Cloud Security Engineer',
    'Google Professional Collaboration Engineer',
    'Google Professional Data Engineer',
    'Google UX Design Certificate',
    'HashiCorp Certified: Terraform Associate',
    'HashiCorp Certified: Vault Associate',
    'HashiCorp Terraform Associate',
    'HashiCorp Vault Associate',
    'HubSpot Content Marketing Certification',
    'HubSpot Email Marketing Certification',
    'HubSpot Inbound Marketing Certification',
    'HubSpot Sales Software Certification',
    'HVAC Excellence Certification',
    'IBM Data Science Professional',
    'ISC2 Certified in Cybersecurity',
    'ISO 27001 Lead Implementer',
    'ITIL 4 Foundation',
    'ITIL Foundation',
    'Juniper Networks Certified Associate',
    'Juniper Networks Certified Specialist',
    'Kubernetes Administrator',
    'Kubernetes and Cloud Native Associate (KCNA)',
    'Kubernetes Certified Application Developer',
    'Lean Six Sigma',
    'Lean Six Sigma Black Belt',
    'Lean Six Sigma Green Belt',
    'Lean Six Sigma Yellow Belt',
    'LEED Accredited Professional',
    'LeSS Practitioner',
    'LFCS',
    'Licensed Electrician',
    'Licensed Plumber',
    'Licensed Professional Counselor (LPC)',
    'Linux Professional Institute Certification 1',
    'Linux Professional Institute Certification 2',
    'LPIC-1',
    'MA (Master of Arts Degree)',
    'MCP (Microsoft Certified Professional)',
    'MCSA (Microsoft Certified Solutions Associate)',
    'MCSE (Microsoft Certified Systems Engineer)',
    'MD (Medical Doctor)',
    'Meta Back-End Developer',
    'Meta Front-End Developer',
    'Microsoft Azure Administrator',
    'Microsoft Azure Administrator (AZ-104)',
    'Microsoft Azure Fundamentals (AZ-900)',
    'Microsoft Azure Solutions Architect (AZ-305)',
    'Microsoft Certified: Agentic AI Business Solutions Architect',
    'Microsoft Certified: Azure Administrator Associate',
    'Microsoft Certified: Azure AI Engineer Associate',
    'Microsoft Certified: Azure Data Engineer Associate',
    'Microsoft Certified: Azure Data Scientist Associate',
    'Microsoft Certified: Azure Database Administrator Associate',
    'Microsoft Certified: Azure Developer Associate',
    'Microsoft Certified: Azure DevOps Engineer Expert',
    'Microsoft Certified: Azure Fundamentals',
    'Microsoft Certified: Azure Network Engineer Associate',
    'Microsoft Certified: Azure Security Engineer Associate',
    'Microsoft Certified: Azure Solutions Architect Expert',
    'Microsoft Certified: Cybersecurity Architect Expert',
    'MongoDB Certified Developer',
    'Montessori Teacher Credential',
    'National Board Certification in Teaching',
    'National Certified Counselor (NCC)',
    'New Relic Certified Performance Engineer',
    'NP (Nurse Practitioner)',
    'Nurse Practitioner License',
    'Nutanix Certified Professional',
    'Nutanix Certified Professional (NCP)',
    'Oracle Certified Associate',
    'Oracle Certified Associate (OCA)',
    'Oracle Certified Master (OCM)',
    'Oracle Certified Professional',
    'Oracle Certified Professional (OCP)',
    'OSCE - Offensive Security Certified Expert',
    'OSCP (Offensive Security Certified Professional)',
    'OSCP - Offensive Security Certified Professional',
    'OSHA 10-Hour Construction Card',
    'OSHA 10-Hour Construction Safety',
    'OSHA 10-Hour General Industry Card',
    'OSHA 10-Hour General Industry Safety',
    'OSHA 30-Hour Construction Card',
    'OSHA 30-Hour Construction Safety',
    'OSHA 30-Hour General Industry Card',
    'OSHA 30-Hour General Industry Safety',
    'OSHA Certified Instructor',
    'OSHA OSHA-10',
    'OSHA Technician Certification',
    'Palo Alto Networks Certified Network Security Administrator',
    'Pediatric Advanced Life Support',
    'Pediatric Advanced Life Support (PALS)',
    'PennDOT Section 608 (EPA)',
    'PharmD (Doctor of Pharmacy)',
    'PHR (Professional in Human Resources)',
    'PMI Agile Certified Practitioner',
    'PMI Professional in Business Analysis',
    'PMI Risk Management Professional',
    'PMP',
    'PMP (Project Management Professional)',
    'Portfolio Management Professional',
    'PRINCE2 Agile Foundation',
    'PRINCE2 Agile Practitioner',
    'PRINCE2 Foundation',
    'PRINCE2 Practitioner',
    'Professional in Human Resources',
    'Professional in Human Resources (PHR)',
    'Professional Scrum Master I',
    'Professional Scrum Master II',
    'Professional Scrum Product Owner I',
    'Professional Scrum Product Owner II',
    'Program Management Professional',
    'Project Management Professional',
    'Project Management Professional (PMP)',
    'PSY D (Doctor of Psychology)',
    'Psychiatric-Mental Health Nurse Practitioner',
    'Quartermaster Certification (Military)',
    'Real Estate License',
    'Red Hat Certified Engineer',
    'Red Hat Certified Engineer (RHCE)',
    'Red Hat Certified System Administrator',
    'Red Hat Certified System Administrator (RHCSA)',
    'Registered Health Information Administrator',
    'Registered Health Information Technician',
    'Registered Medical Assistant',
    'Registered Medical Assistant (RMA)',
    'Registered Nurse License',
    'Registered Radiologic Technologist',
    'Registered Respiratory Therapist',
    'SAFe Agilist',
    'SAFe Practice Consultant',
    'SAFe Product Owner/Product Manager',
    'SAFe Scrum Master',
    'Salesforce Administrator',
    'Salesforce Architect',
    'Salesforce Certified Administrator',
    'Salesforce Certified Application Architect',
    'Salesforce Certified Business Analyst',
    'Salesforce Certified Platform Developer I',
    'Salesforce Certified Platform Developer II',
    'Salesforce Certified System Architect',
    'Salesforce Certified Technical Architect',
    'Salesforce Developer',
    'SAP Certified Application Associate',
    'SAP Certified Technology Associate',
    'Securities Industry Essentials',
    'Senior Professional in Human Resources',
    'Senior Professional in Human Resources (SPHR)',
    'Senior Professional in Human Resources - International',
    'Series 6 License',
    'Series 63',
    'Series 63 - Uniform Securities Agent',
    'Series 63 License',
    'Series 65',
    'Series 65 - Uniform Investment Adviser Law',
    'Series 65 License',
    'Series 66',
    'Series 66 - Combined Uniform State Law',
    'Series 66 License',
    'Series 7',
    'Series 7 - General Securities Representative',
    'Series 7 License',
    'Series 79 License',
    'SHRM Certified Professional',
    'SHRM Certified Professional (SHRM-CP)',
    'SHRM Senior Certified Professional',
    'SHRM Senior Certified Professional (SHRM-SCP)',
    'SHRM-CP',
    'SHRM-SCP',
    'SIE (Securities Industry Essentials)',
    'Six Sigma Black Belt',
    'Six Sigma Green Belt',
    'Splunk Core Certified Advanced Power User',
    'Splunk Core Certified Power User',
    'SSCP (Systems Security Certified Practitioner)',
    'SSCP - Systems Security Certified Practitioner',
    'State Teaching License',
    'Systems Security Certified Practitioner (SSCP)',
    'Teaching English as a Foreign Language (TEFL)',
    'TEFL Certification',
    'TensorFlow Developer Certificate',
    'TESOL Certification',
    'TESOL/TEFL Certificate',
    'TS / SCI (Top Secret Security Clearance with SCI access)',
    'VMCE (Veeam Certified Engineer)',
    'VMCP (VMware Certified Professional)',
    'VMware Certified Advanced Professional',
    'VMware Certified Advanced Professional (VCAP)',
    'VMware Certified Professional',
    'VMware Certified Professional (VCP)',
  ],

  certificationIssuers: [
    '(ISC)²',
    'Adobe',
    'AHA (American Heart Association)',
    'Amazon Web Services',
    'American Association of Medical Assistants (AAMA)',
    'American Bar Association',
    'American Board of Internal Medicine',
    'American Chiropractic Board of Sports Physicians',
    'American Dental Association',
    'American Heart Association',
    'American Institute of Certified Public Accountants',
    'American Nurses Credentialing Center',
    'American Red Cross',
    'American Registry for Diagnostic Medical Sonography',
    'American Registry of Radiologic Technologists',
    'American Society of Quality',
    'American Welding Society',
    'Apple',
    'Association of Certified Anti-Money Laundering Specialists',
    'Board of Certified Safety Professionals',
    'British Computer Society',
    'Certified Financial Planner Board of Standards',
    'Certified Financial Planner Board of Standards (FPSB)',
    'CFA Institute',
    'Chartered Insurance Institute',
    'Cisco',
    'Cisco Systems',
    'CompTIA',
    'CPA',
    'Docker',
    'EC-Council',
    'FINRA (Financial Industry Regulatory Authority)',
    'GARP',
    'GIAC Certifications',
    'GitLab',
    'Google',
    'HashiCorp',
    'HR Certification Institute',
    'HRCI (HR Certification Institute)',
    'HubSpot',
    'IBM',
    'International Association of Privacy Professionals',
    'International Council of E-Commerce Consultants (EC-Council)',
    'International Registry of Microbial Standardization',
    'ISACA',
    'ISC2',
    'ITIL',
    'Kubernetes',
    'Linux Foundation',
    'Linux Professional Institute',
    'Meta',
    'Microsoft',
    'MongoDB',
    'Montessori Accreditation Council for Teacher Education',
    'NABA (National Association of Black Accountants)',
    'NATE (North Amer. Technician Excellence)',
    'National Board for Professional Teaching Standards',
    'National Board for Respiratory Care',
    'National Board of Medical Examiners',
    'National Fire Protection Association',
    'National Healthcareer Association',
    'NCCCO (Cert. for Construction Equipment Operators)',
    'NCCER (Natl. Ctr. for Construction Education and Research)',
    'NHTSA (Natl. Highway Traffic Safety Admin.)',
    'Offensive Security',
    'Oracle',
    'OSHA',
    'OSHA (Occupational Safety and Health Admin.)',
    'PeopleCert',
    'PMI (Project Management Institute)',
    'Project Management Institute',
    'Red Hat',
    'Salesforce',
    'SAP',
    'Scaled Agile',
    'Scrum Alliance',
    'Scrum.org',
    'SHRM (Society for Human Resource Management)',
    'Six Sigma',
    'Society for Human Resource Management',
    'State Board of Education',
    'TensorFlow',
    'TESOL International Association',
    'TSA (Transportation Security Administration)',
    'VMware',
  ],

  locations: {
    usCities: [
      'Akron, OH',
      'Albany, NY',
      'Albuquerque, NM',
      'Alexandria, VA',
      'Allentown, PA',
      'Amarillo, TX',
      'Anaheim, CA',
      'Anchorage, AK',
      'Annapolis, MD',
      'Arlington, TX',
      'Arlington, VA',
      'Atlanta, GA',
      'Augusta, GA',
      'Augusta, ME',
      'Aurora, CO',
      'Austin, TX',
      'Bakersfield, CA',
      'Baltimore, MD',
      'Baton Rouge, LA',
      'Bellevue, WA',
      'Birmingham, AL',
      'Bismarck, ND',
      'Boise, ID',
      'Boston, MA',
      'Bridgeport, CT',
      'Brownsville, TX',
      'Buffalo, NY',
      'Cape Coral, FL',
      'Carrollton, TX',
      'Carson City, NV',
      'Cary, NC',
      'Chandler, AZ',
      'Charleston, SC',
      'Charleston, WV',
      'Charlotte, NC',
      'Chattanooga, TN',
      'Chesapeake, VA',
      'Cheyenne, WY',
      'Chicago, IL',
      'Chula Vista, CA',
      'Cincinnati, OH',
      'Cleveland, OH',
      'Colorado Springs, CO',
      'Columbia, SC',
      'Columbus, GA',
      'Columbus, OH',
      'Concord, NH',
      'Corona, CA',
      'Corpus Christi, TX',
      'Dallas, TX',
      'Dayton, OH',
      'Denver, CO',
      'Des Moines, IA',
      'Detroit, MI',
      'Dover, DE',
      'Durham, NC',
      'El Paso, TX',
      'Elk Grove, CA',
      'Escondido, CA',
      'Eugene, OR',
      'Fairfax, VA',
      'Fargo, ND',
      'Fayetteville, NC',
      'Fontana, CA',
      'Fort Collins, CO',
      'Fort Lauderdale, FL',
      'Fort Wayne, IN',
      'Fort Worth, TX',
      'Frankfort, KY',
      'Fremont, CA',
      'Fresno, CA',
      'Frisco, TX',
      'Fullerton, CA',
      'Garland, TX',
      'Gilbert, AZ',
      'Glendale, AZ',
      'Glendale, CA',
      'Grand Prairie, TX',
      'Grand Rapids, MI',
      'Green Bay, WI',
      'Greensboro, NC',
      'Hampton, VA',
      'Harrisburg, PA',
      'Hartford, CT',
      'Hayward, CA',
      'Helena, MT',
      'Henderson, NV',
      'Hialeah, FL',
      'Honolulu, HI',
      'Hoover, AL',
      'Houston, TX',
      'Huntington Beach, CA',
      'Huntsville, AL',
      'Indianapolis, IN',
      'Irvine, CA',
      'Irving, TX',
      'Jackson, MS',
      'Jacksonville, FL',
      'Jefferson City, MO',
      'Jersey City, NJ',
      'Joliet, IL',
      'Juneau, AK',
      'Kansas City, MO',
      'Killeen, TX',
      'Knoxville, TN',
      'Lancaster, CA',
      'Laredo, TX',
      'Las Vegas, NV',
      'Lexington, KY',
      'Lincoln, NE',
      'Little Rock, AR',
      'Long Beach, CA',
      'Los Angeles, CA',
      'Louisville, KY',
      'Lubbock, TX',
      'Madison, WI',
      'McAllen, TX',
      'McKinney, TX',
      'Memphis, TN',
      'Mesa, AZ',
      'Mesquite, TX',
      'Miami, FL',
      'Milwaukee, WI',
      'Minneapolis, MN',
      'Miramar, FL',
      'Mobile, AL',
      'Modesto, CA',
      'Montgomery, AL',
      'Montpelier, VT',
      'Moreno Valley, CA',
      'Myrtle Beach, SC',
      'Nashville, TN',
      'New Orleans, LA',
      'New York, NY',
      'Newark, NJ',
      'Newport News, VA',
      'Norfolk, VA',
      'North Las Vegas, NV',
      'Oakland, CA',
      'Oceanside, CA',
      'Oklahoma City, OK',
      'Olympia, WA',
      'Omaha, NE',
      'Orange, CA',
      'Orlando, FL',
      'Overland Park, KS',
      'Oxnard, CA',
      'Palmdale, CA',
      'Paradise, NV',
      'Pasadena, CA',
      'Pasadena, TX',
      'Paterson, NJ',
      'Pembroke Pines, FL',
      'Peoria, AZ',
      'Philadelphia, PA',
      'Phoenix, AZ',
      'Pierre, SD',
      'Pittsburgh, PA',
      'Plano, TX',
      'Pomona, CA',
      'Port St. Lucie, FL',
      'Portland, OR',
      'Providence, RI',
      'Raleigh, NC',
      'Rancho Cucamonga, CA',
      'Reno, NV',
      'Richmond, VA',
      'Riverside, CA',
      'Rochester, NY',
      'Rockford, IL',
      'Sacramento, CA',
      'Saint Paul, MN',
      'Salem, OR',
      'Salinas, CA',
      'Salt Lake City, UT',
      'San Antonio, TX',
      'San Bernardino, CA',
      'San Diego, CA',
      'San Francisco, CA',
      'San Jose, CA',
      'San Juan, PR',
      'Santa Ana, CA',
      'Santa Clarita, CA',
      'Santa Fe, NM',
      'Santa Rosa, CA',
      'Savannah, GA',
      'Scottsdale, AZ',
      'Seattle, WA',
      'Shreveport, LA',
      'Sioux Falls, SD',
      'Spokane, WA',
      'Springfield, MA',
      'Springfield, MO',
      'St. Louis, MO',
      'St. Paul, MN',
      'St. Petersburg, FL',
      'Stockton, CA',
      'Sunnyvale, CA',
      'Syracuse, NY',
      'Tacoma, WA',
      'Tallahassee, FL',
      'Tampa, FL',
      'Tempe, AZ',
      'Toledo, OH',
      'Torrance, CA',
      'Trenton, NJ',
      'Tucson, AZ',
      'Tulsa, OK',
      'Vancouver, WA',
      'Virginia Beach, VA',
      'Washington, DC',
      'Wichita, KS',
      'Winston-Salem, NC',
      'Worcester, MA',
      'Yonkers, NY',
    ],
    states: [
      'Alabama',
      'Alaska',
      'American Samoa',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'District of Columbia',
      'Federated States of Micronesia',
      'Florida',
      'Georgia',
      'Guam',
      'Hawaii',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Kentucky',
      'Louisiana',
      'Maine',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'Nevada',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'New York',
      'North Carolina',
      'North Dakota',
      'Northern Mariana Islands',
      'Ohio',
      'Oklahoma',
      'Oregon',
      'Palau',
      'Pennsylvania',
      'Puerto Rico',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'U.S. Virgin Islands',
      'Utah',
      'Vermont',
      'Virgin Islands',
      'Virginia',
      'Washington',
      'West Virginia',
      'Wisconsin',
      'Wyoming',
    ],
    countries: [
      'Afghanistan',
      'Albania',
      'Algeria',
      'Angola',
      'Argentina',
      'Armenia',
      'Australia',
      'Austria',
      'Azerbaijan',
      'Bahrain',
      'Bangladesh',
      'Belgium',
      'Bolivia',
      'Bosnia and Herzegovina',
      'Brazil',
      'Bulgaria',
      'Cameroon',
      'Canada',
      'Chile',
      'China',
      'Colombia',
      'Costa Rica',
      'Croatia',
      'Cyprus',
      'Czech Republic',
      'Czechia',
      'Denmark',
      'Dominican Republic',
      'Ecuador',
      'Egypt',
      'Estonia',
      'Ethiopia',
      'Finland',
      'France',
      'Georgia',
      'Germany',
      'Ghana',
      'Greece',
      'Guatemala',
      'Honduras',
      'Hong Kong',
      'Hungary',
      'Iceland',
      'India',
      'Indonesia',
      'Iran',
      'Iraq',
      'Ireland',
      'Israel',
      'Italy',
      'Ivory Coast',
      'Japan',
      'Jordan',
      'Kazakhstan',
      'Kenya',
      'Kuwait',
      'Latvia',
      'Lebanon',
      'Lithuania',
      'Luxembourg',
      'Malaysia',
      'Malta',
      'Mexico',
      'Morocco',
      'Netherlands',
      'New Zealand',
      'Nigeria',
      'North Macedonia',
      'Norway',
      'Oman',
      'Pakistan',
      'Panama',
      'Paraguay',
      'Peru',
      'Philippines',
      'Poland',
      'Portugal',
      'Qatar',
      'Romania',
      'Russia',
      'Saudi Arabia',
      'Serbia',
      'Singapore',
      'Slovakia',
      'Slovenia',
      'South Africa',
      'South Korea',
      'Spain',
      'Sweden',
      'Switzerland',
      'Taiwan',
      'Tanzania',
      'Thailand',
      'Turkey',
      'UAE',
      'Uganda',
      'Ukraine',
      'United Arab Emirates',
      'United Kingdom',
      'United States',
      'Uruguay',
      'Uzbekistan',
      'Venezuela',
      'Vietnam',
      'Zimbabwe',
    ],
  },

  languages: [
    'Afaan Oromoo (Oromo)',
    'Afrikaans',
    'Albanian',
    'Amharic',
    'Arabic',
    'Arabic (العربية)',
    'Armenian',
    'Azerbaijani',
    'Basque',
    'Bengali',
    'Bengali (বাংলা)',
    'Bosnian',
    'Bulgarian',
    'Burmese',
    'Cantonese',
    'Cantonese Chinese',
    'Catalan',
    'Chinese (Cantonese)',
    'Chinese (Mandarin)',
    'Croatian',
    'Czech',
    'Danish',
    'Dutch',
    'English',
    'Estonian',
    'Farsi (Persian)',
    'Finnish',
    'French',
    'French (Français)',
    'Galician',
    'Georgian',
    'German',
    'German (Deutsch)',
    'Greek',
    'Greek (Ελληνικά)',
    'Gujarati',
    'Hebrew',
    'Hebrew (עברית)',
    'Hindi',
    'Hindi (हिन्दी)',
    'Hungarian',
    'Icelandic',
    'Indonesian',
    'Irish',
    'Italian',
    'Italian (Italiano)',
    'Japanese',
    'Japanese (日本語)',
    'Javanese',
    'Kannada',
    'Kazakh',
    'Khmer',
    'Korean',
    'Korean (한국어)',
    'Latvian',
    'Lithuanian',
    'Macedonian',
    'Malay',
    'Malayalam',
    'Mandarin Chinese',
    'Marathi',
    'Mongolian',
    'Nepali',
    'Norwegian',
    'Pashto',
    'Polish',
    'Portuguese',
    'Portuguese (Português)',
    'Punjabi',
    'Romanian',
    'Russian',
    'Russian (Русский)',
    'Serbian',
    'Sinhala',
    'Slovak',
    'Slovenian',
    'Spanish',
    'Spanish (Español)',
    'Swahili',
    'Swedish',
    'Tagalog',
    'Tagalog (Filipino)',
    'Tamil',
    'Telugu',
    'Thai',
    'Turkish',
    'Ukrainian',
    'Urdu',
    'Vietnamese',
    'Welsh',
  ],

  proficiencyLevels: [
    'Beginner',
    'Elementary',
    'Intermediate',
    'Upper Intermediate',
    'Advanced',
    'Fluent',
    'Native',
  ],

  skillLevels: [
    'beginner',
    'intermediate',
    'advanced',
    'expert',
  ],

  relationships: [
    'Former Manager',
    'Former Supervisor',
    'Former Colleague',
    'Former Coworker',
    'Direct Report',
    'Former Employee',
    'Professor',
    'Academic Advisor',
    'Mentor',
    'Professional Mentor',
    'Client',
    'Business Partner',
    'Collaborator',
    'Internship Supervisor',
    'Volunteer Coordinator',
  ],

  coreCompetencies: [
    'Strategic Planning',
    'Team Leadership',
    'Project Management',
    'Cross-Functional Collaboration',
    'Performance Management',
    'Budget Management',
    'P&L Responsibility',
    'Process Improvement',
    'Risk Management',
    'Change Management',
    'Stakeholder Management',
    'Talent Development',
    'Business Development',
    'Data Analysis',
    'Operational Excellence',
    'Quality Assurance',
    'Contract Negotiation',
    'Vendor Management',
    'Executive Leadership',
    'Succession Planning',
    'Employee Engagement',
    'Conflict Resolution',
    'Digital Transformation',
    'Market Analysis',
    'Product Development',
  ],

  clinicalSkills: [
    'Vital Signs Monitoring',
    'Patient Assessment',
    'Wound Care',
    'Wound Dressing',
    'Medication Administration',
    'Intravenous Therapy',
    'IV Insertion',
    'Phlebotomy',
    'Venipuncture',
    'EKG',
    'Electrocardiography',
    'EKG Interpretation',
    'Catheter Care',
    'Catheterization',
    'Infection Control',
    'Patient Mobility Assistance',
    'Patient Lifting',
    'Hoyer Lift Operation',
    'Specimen Collection',
    'Blood Glucose Monitoring',
    'Basic Life Support (BLS)',
    'CPR',
    'Advanced Cardiac Life Support (ACLS)',
    'Patient Education',
    'EHR Documentation',
    'Epic Systems',
    'Cerner',
    'PointClickCare',
    'Medical Terminology',
    'HIPAA Compliance',
    'Fall Prevention',
    'Pain Management',
    'Oxygen Therapy',
    'End-of-Life Care',
    'Dementia Care',
    'Geriatric Care',
    'Pediatric Care',
    'Acute Care',
    'Critical Care',
    'Post-Operative Monitoring',
  ],

  practiceAreas: [
    'Corporate Law',
    'Business Law',
    'Criminal Law',
    'Civil Litigation',
    'Family Law',
    'Divorce Law',
    'Intellectual Property',
    'Patent Law',
    'Real Estate Law',
    'Tax Law',
    'Employment Law',
    'Labor Law',
    'Immigration Law',
    'Securities Law',
    'Environmental Law',
    'Bankruptcy Law',
    'Personal Injury',
    'Medical Malpractice',
    'Constitutional Law',
    'Human Rights Law',
    'International Law',
    'Contract Law',
    'Mergers and Acquisitions',
    'Insurance Law',
    'Health Care Law',
    'Estate Planning',
    'Probate Law',
    'Product Liability',
    'Defamation',
    'Appellate Practice',
    'Alternative Dispute Resolution',
    'Arbitration',
    'Mediation',
  ],

  securityClearance: [
    'Confidential',
    'Secret',
    'Top Secret',
    'TS/SCI',
    'Top Secret/Sensitive Compartmented Information',
    'Public Trust',
    'Q Clearance',
    'L Clearance',
  ],

};
