import type { AutocompleteData } from './types';

export const es: Partial<AutocompleteData> = {
  jobTitles: [
    'Ingeniero de Software',
    'Ingeniero de Software Senior',
    'Ingeniero de Software Principal',
    'Desarrollador de Software',
    'Desarrollador Senior',
    'Desarrollador Full Stack',
    'Desarrollador Frontend',
    'Desarrollador Backend',
    'Desarrollador Móvil',
    'Desarrollador iOS',
    'Desarrollador Android',
    'Ingeniero DevOps',
    'Ingeniero de Confiabilidad',
    'Científico de Datos',
    'Científico de Datos Senior',
    'Ingeniero de Machine Learning',
    'Analista de Datos',
    'Analista de Negocios',
    'Gerente de Producto',
    'Gerente de Producto Senior',
    'Gerente de Proyectos',
    'Scrum Master',
    'Diseñador UX',
    'Diseñador UI',
    'Diseñador UX Senior',
    'Diseñador Gráfico',
    'Diseñador Web',
    'Gerente de Marketing',
    'Gerente de Marketing Digital',
    'Especialista SEO',
    'Gerente de Redes Sociales',
    'Representante de Ventas',
    'Ejecutivo de Cuentas',
    'Gerente de Ventas',
    'Contador',
    'Contador Senior',
    'Analista Financiero',
    'Gerente de RH',
    'Gerente de RRHH',
    'Reclutador',
    'Reclutador Técnico',
    'Asistente Ejecutivo',
    'Director Ejecutivo (CEO)',
    'Director de Tecnología (CTO)',
    'Director Financiero (CFO)',
    'Director de Operaciones (COO)',
    'VP de Ingeniería',
    'VP de Producto',
    'Director de Ingeniería',
    'Director de Marketing',
    'Profesor',
    'Profesor Universitario',
    'Maestro',
    'Asistente de Enseñanza',
    'Investigador',
    'Científico Investigador',
    'Abogado',
    'Paralegal',
    'Consultor',
    'Consultor de Gestión',
    'Consultor Estratégico',
    'Enfermero',
    'Enfermero Titulado',
    'Enfermero Jefe',
    'Ingeniero Civil',
    'Ingeniero Mecánico',
    'Ingeniero Eléctrico',
    'Ingeniero Estructural',
    'Ingeniero de Sistemas',
    'Técnico de Soporte TI',
    'Administrador de Sistemas',
    'Administrador de Redes',
    'Analista de Seguridad',
    'Gerente de TI',
  ],

  degrees: [
    'Licenciatura en Artes',
    'Licenciatura en Ciencias',
    'Licenciatura en Administración de Empresas',
    'Licenciatura en Bellas Artes',
    'Licenciatura en Ingeniería',
    'Licenciatura en Ciencias de la Computación',
    'Maestría en Artes',
    'Maestría en Ciencias',
    'Maestría en Administración de Empresas (MBA)',
    'Maestría en Bellas Artes',
    'Maestría en Ingeniería',
    'Maestría en Ciencias de la Computación',
    'Doctorado en Jurisprudencia',
    'Doctorado en Filosofía',
    'Doctorado en Medicina',
    'Técnico Superior',
    'Diplomatura',
    'Certificado',
  ],

  fieldsOfStudy: [
    'Ciencias de la Computación',
    'Ingeniería de Software',
    'Tecnología de la Información',
    'Ciencia de Datos',
    'Machine Learning',
    'Inteligencia Artificial',
    'Administración de Empresas',
    'Mercadotecnia',
    'Finanzas',
    'Economía',
    'Contabilidad',
    'Psicología',
    'Sociología',
    'Ciencias Políticas',
    'Comunicación',
    'Diseño Gráfico',
    'Diseño Industrial',
    'Arquitectura',
    'Ingeniería',
    'Ingeniería Civil',
    'Ingeniería Mecánica',
    'Ingeniería Eléctrica',
    'Ingeniería Química',
    'Ingeniería Biomédica',
    'Física',
    'Matemáticas',
    'Química',
    'Biología',
    'Enfermería',
    'Medicina',
    'Derecho',
    'Educación',
    'Literatura Inglesa',
    'Historia',
    'Filosofía',
    'Teología',
    'Recursos Humanos',
    'Relaciones Internacionales',
    'Políticas Públicas',
    'Ciencias Ambientales',
    'Estadística',
    'Sistemas de Información',
    'Ciberseguridad',
    'Ingeniería de Redes',
    'Computación en la Nube',
    'Desarrollo de Videojuegos',
    'Interacción Humano-Computadora',
  ],

  languages: [
    'Español',
    'Inglés',
    'Chino Mandarín',
    'Cantonés',
    'Francés',
    'Alemán',
    'Italiano',
    'Portugués',
    'Ruso',
    'Japonés',
    'Coreano',
    'Árabe',
    'Hindi',
    'Bengalí',
    'Turco',
    'Vietnamita',
    'Tailandés',
    'Neerlandés',
    'Sueco',
    'Polaco',
    'Griego',
    'Hebreo',
    'Indonesio',
    'Malayo',
    'Urdu',
    'Panyabí',
    'Tamil',
    'Telugu',
    'Maratí',
    'Checo',
    'Rumano',
    'Húngaro',
    'Ucraniano',
  ],

  proficiencyLevels: [
    'Principiante',
    'Elemental',
    'Intermedio',
    'Intermedio Alto',
    'Avanzado',
    'Fluido',
    'Nativo',
  ],

  skillLevels: ['principiante', 'intermedio', 'avanzado', 'experto'],

  relationships: [
    'Ex Gerente',
    'Ex Supervisor',
    'Ex Colega',
    'Ex Compañero de Trabajo',
    'Subordinado Directo',
    'Ex Empleado',
    'Profesor',
    'Asesor Académico',
    'Mentor',
    'Cliente',
    'Socio Comercial',
    'Colaborador',
    'Supervisor de Prácticas',
  ],

  coreCompetencies: [
    'Planificación Estratégica',
    'Liderazgo de Equipos',
    'Gestión de Proyectos',
    'Colaboración Interdepartamental',
    'Gestión del Rendimiento',
    'Gestión Presupuestaria',
    'Responsabilidad de P&L',
    'Mejora de Procesos',
    'Gestión de Riesgos',
    'Gestión del Cambio',
    'Gestión de Interesados',
    'Desarrollo de Talento',
    'Desarrollo de Negocios',
    'Análisis de Datos',
    'Excelencia Operativa',
    'Aseguramiento de Calidad',
    'Negociación de Contratos',
    'Gestión de Proveedores',
    'Liderazgo Ejecutivo',
    'Planificación de Sucesión',
    'Compromiso de Empleados',
  ],

  practiceAreas: [
    'Derecho Corporativo',
    'Derecho Mercantil',
    'Derecho Penal',
    'Litigio Civil',
    'Derecho de Familia',
    'Derecho de Divorcio',
    'Propiedad Intelectual',
    'Derecho de Patentes',
    'Derecho Inmobiliario',
    'Derecho Fiscal',
    'Derecho Laboral',
    'Derecho de Inmigración',
    'Derecho de Valores',
    'Derecho Ambiental',
    'Derecho Concursal',
    'Daños Personales',
    'Negligencia Médica',
    'Derecho Constitucional',
    'Derechos Humanos',
    'Derecho Internacional',
    'Derecho Contractual',
    'Fusiones y Adquisiciones',
    'Planificación Patrimonial',
    'Mediación',
    'Arbitraje',
  ],
};
