import type { AutocompleteData } from './types';

export const fr: Partial<AutocompleteData> = {
  jobTitles: [
    'Ingénieur Logiciel',
    'Ingénieur Logiciel Senior',
    'Ingénieur Logiciel Principal',
    'Développeur Logiciel',
    'Développeur Senior',
    'Développeur Full Stack',
    'Développeur Frontend',
    'Développeur Backend',
    'Développeur Mobile',
    'Développeur iOS',
    'Développeur Android',
    'Ingénieur DevOps',
    'Ingénieur Fiabilité',
    'Scientifique des Données',
    'Scientifique des Données Senior',
    'Ingénieur Machine Learning',
    'Analyste de Données',
    'Analyste d\'Affaires',
    'Chef de Produit',
    'Chef de Produit Senior',
    'Chef de Projet',
    'Scrum Master',
    'Designer UX',
    'Designer UI',
    'Designer UX Senior',
    'Designer Graphique',
    'Designer Web',
    'Responsable Marketing',
    'Responsable Marketing Digital',
    'Spécialiste SEO',
    'Community Manager',
    'Représentant Commercial',
    'Responsable Commercial',
    'Comptable',
    'Comptable Senior',
    'Analyste Financier',
    'Responsable RH',
    'Recruteur',
    'Recruteur Technique',
    'Assistant(e) de Direction',
    'Directeur Général',
    'Directeur Technique',
    'Directeur Financier',
    'Directeur des Opérations',
    'VP Ingénierie',
    'VP Produit',
    'Directeur d\'Ingénierie',
    'Professeur',
    'Enseignant',
    'Assistant d\'Enseignement',
    'Chercheur',
    'Avocat',
    'Consultant',
    'Consultant en Management',
    'Infirmier',
    'Infirmier Diplômé',
    'Infirmier en Chef',
    'Ingénieur Civil',
    'Ingénieur Mécanique',
    'Ingénieur Électrique',
    'Technicien Support IT',
    'Administrateur Système',
    'Administrateur Réseau',
    'Analyste de Sécurité',
    'Responsable IT',
  ],

  degrees: [
    'Licence en Arts',
    'Licence en Sciences',
    'Licence en Administration des Affaires',
    'Licence en Beaux-Arts',
    'Licence en Ingénierie',
    'Licence en Informatique',
    'Master en Arts',
    'Master en Sciences',
    'Master en Administration des Affaires (MBA)',
    'Master en Beaux-Arts',
    'Master en Ingénierie',
    'Master en Informatique',
    'Doctorat en Droit',
    'Doctorat',
    'Doctorat en Médecine',
    'Diplôme d\'Études Supérieures',
    'Certificat',
  ],

  fieldsOfStudy: [
    'Informatique',
    'Génie Logiciel',
    'Technologie de l\'Information',
    'Science des Données',
    'Machine Learning',
    'Intelligence Artificielle',
    'Administration des Affaires',
    'Marketing',
    'Finance',
    'Économie',
    'Comptabilité',
    'Psychologie',
    'Sociologie',
    'Sciences Politiques',
    'Communication',
    'Design Graphique',
    'Architecture',
    'Génie Civil',
    'Génie Mécanique',
    'Génie Électrique',
    'Génie Chimique',
    'Physique',
    'Mathématiques',
    'Chimie',
    'Biologie',
    'Soins Infirmiers',
    'Médecine',
    'Droit',
    'Éducation',
    'Histoire',
    'Philosophie',
    'Ressources Humaines',
    'Relations Internationales',
    'Sciences de l\'Environnement',
    'Statistiques',
    'Cybersécurité',
  ],

  languages: [
    'Français',
    'Anglais',
    'Espagnol',
    'Chinois Mandarin',
    'Allemand',
    'Italien',
    'Portugais',
    'Russe',
    'Japonais',
    'Coréen',
    'Arabe',
    'Hindi',
    'Néerlandais',
    'Suédois',
    'Polonais',
    'Grec',
    'Turc',
  ],

  proficiencyLevels: [
    'Débutant',
    'Élémentaire',
    'Intermédiaire',
    'Intermédiaire Supérieur',
    'Avancé',
    'Courant',
    'Langue Maternelle',
  ],

  skillLevels: ['débutant', 'intermédiaire', 'avancé', 'expert'],

  relationships: [
    'Ancien Manager',
    'Ancien Supérieur',
    'Ancien Collègue',
    'Ancien Collaborateur',
    'Subordonné Direct',
    'Ancien Employé',
    'Professeur',
    'Conseiller Académique',
    'Mentor',
    'Client',
    'Partenaire Commercial',
    'Collaborateur',
    'Superviseur de Stage',
  ],

  coreCompetencies: [
    'Planification Stratégique',
    'Leadership d\'Équipe',
    'Gestion de Projet',
    'Collaboration Interfonctionnelle',
    'Gestion de la Performance',
    'Gestion Budgétaire',
    'Responsabilité P&L',
    'Amélioration des Processus',
    'Gestion des Risques',
    'Gestion du Changement',
    'Gestion des Parties Prenantes',
    'Développement des Talents',
    'Développement Commercial',
    'Analyse de Données',
    'Excellence Opérationnelle',
    'Assurance Qualité',
    'Négociation de Contrats',
    'Gestion des Fournisseurs',
  ],

  practiceAreas: [
    'Droit des Sociétés',
    'Droit Commercial',
    'Droit Pénal',
    'Contentieux Civil',
    'Droit de la Famille',
    'Droit des Divorces',
    'Propriété Intellectuelle',
    'Droit des Brevets',
    'Droit Immobilier',
    'Droit Fiscal',
    'Droit du Travail',
    'Droit de l\'Immigration',
    'Droit de l\'Environnement',
    'Droit des Faillites',
    'Dommages Corporels',
    'Droit Constitutionnel',
    'Droits de l\'Homme',
    'Droit International',
    'Droit des Contrats',
    'Fusions et Acquisitions',
  ],
};
