import type { AutocompleteData } from './types';

export const pt: Partial<AutocompleteData> = {
  jobTitles: [
    'Engenheiro de Software',
    'Engenheiro de Software Sênior',
    'Desenvolvedor de Software',
    'Desenvolvedor Sênior',
    'Desenvolvedor Full Stack',
    'Desenvolvedor Frontend',
    'Desenvolvedor Backend',
    'Desenvolvedor Mobile',
    'Desenvolvedor iOS',
    'Desenvolvedor Android',
    'Engenheiro DevOps',
    'Cientista de Dados',
    'Cientista de Dados Sênior',
    'Engenheiro de Machine Learning',
    'Analista de Dados',
    'Analista de Negócios',
    'Gerente de Produto',
    'Gerente de Produto Sênior',
    'Gerente de Projetos',
    'Scrum Master',
    'Designer UX',
    'Designer UI',
    'Designer UX Sênior',
    'Designer Gráfico',
    'Designer Web',
    'Gerente de Marketing',
    'Gerente de Marketing Digital',
    'Especialista SEO',
    'Gerente de Mídias Sociais',
    'Representante de Vendas',
    'Gerente de Vendas',
    'Contador',
    'Contador Sênior',
    'Analista Financeiro',
    'Gerente de RH',
    'Recrutador',
    'Recrutador Técnico',
    'Assistente Executivo',
    'CEO',
    'CTO',
    'CFO',
    'Diretor de Engenharia',
    'Professor',
    'Professor Universitário',
    'Pesquisador',
    'Advogado',
    'Consultor',
    'Consultor de Gestão',
    'Enfermeiro',
    'Enfermeiro Registrado',
    'Engenheiro Civil',
    'Engenheiro Mecânico',
    'Engenheiro Elétrico',
    'Técnico de Suporte TI',
    'Administrador de Sistemas',
    'Administrador de Redes',
    'Analista de Segurança',
    'Gerente de TI',
  ],

  degrees: [
    'Bacharelado em Artes',
    'Bacharelado em Ciências',
    'Bacharelado em Administração de Empresas',
    'Bacharelado em Belas Artes',
    'Bacharelado em Engenharia',
    'Bacharelado em Ciência da Computação',
    'Mestrado em Artes',
    'Mestrado em Ciências',
    'Mestrado em Administração de Empresas (MBA)',
    'Mestrado em Engenharia',
    'Mestrado em Ciência da Computação',
    'Doutorado',
    'Doutorado em Medicina',
    'Tecnólogo',
    'Certificado',
  ],

  fieldsOfStudy: [
    'Ciência da Computação',
    'Engenharia de Software',
    'Tecnologia da Informação',
    'Ciência de Dados',
    'Machine Learning',
    'Inteligência Artificial',
    'Administração de Empresas',
    'Marketing',
    'Finanças',
    'Economia',
    'Contabilidade',
    'Psicologia',
    'Sociologia',
    'Ciências Políticas',
    'Comunicação',
    'Design Gráfico',
    'Arquitetura',
    'Engenharia',
    'Engenharia Civil',
    'Engenharia Mecânica',
    'Engenharia Elétrica',
    'Engenharia Química',
    'Física',
    'Matemática',
    'Química',
    'Biologia',
    'Enfermagem',
    'Medicina',
    'Direito',
    'Educação',
    'História',
    'Filosofia',
    'Recursos Humanos',
    'Relações Internacionais',
    'Ciências Ambientais',
    'Estatística',
    'Segurança Cibernética',
  ],

  languages: [
    'Português',
    'Inglês',
    'Espanhol',
    'Francês',
    'Alemão',
    'Italiano',
    'Russo',
    'Japonês',
    'Coreano',
    'Chinês Mandarim',
    'Árabe',
    'Hindi',
    'Neerlandês',
    'Sueco',
    'Polonês',
  ],

  proficiencyLevels: [
    'Iniciante',
    'Elementar',
    'Intermediário',
    'Intermediário Superior',
    'Avançado',
    'Fluente',
    'Nativo',
  ],

  skillLevels: ['iniciante', 'intermediário', 'avançado', 'especialista'],

  relationships: [
    'Ex-Gerente',
    'Ex-Supervisor',
    'Ex-Colega',
    'Ex-Companheiro de Trabalho',
    'Subordinado Direto',
    'Ex-Funcionário',
    'Professor',
    'Conselheiro Acadêmico',
    'Mentor',
    'Cliente',
    'Sócio Comercial',
    'Colaborador',
    'Supervisor de Estágio',
  ],

  coreCompetencies: [
    'Planejamento Estratégico',
    'Liderança de Equipes',
    'Gerenciamento de Projetos',
    'Colaboração Interfuncional',
    'Gestão de Desempenho',
    'Gestão Orçamentária',
    'Melhoria de Processos',
    'Gestão de Riscos',
    'Gestão de Mudanças',
    'Gestão de Stakeholders',
    'Desenvolvimento de Talentos',
    'Desenvolvimento de Negócios',
    'Análise de Dados',
    'Excelência Operacional',
    'Garantia de Qualidade',
    'Negociação de Contratos',
  ],
};
