import { IconDefinition } from '../types';
import { FaAws, FaMicrosoft, FaAmazon } from 'react-icons/fa';
import {
  SiGooglecloud,
  SiCloudflare,
  SiVercel,
  SiNetlify,
  SiHeroku,
  SiDigitalocean,
  SiRailway,
  SiFlydotio,
  SiFirebase,
} from 'react-icons/si';

// NOTE: react-icons/si v5.6.0 bundles an older Simple Icons release without
// AWS, Azure, Lambda, S3, EC2, Cloud Functions, Cloud Run branded icons.
// We use Font Awesome alternatives (FaAws, FaMicrosoft, FaAmazon) as fallbacks
// and reuse parent-platform Si icons for GCP sub-services.

export const cloudInfraIcons: IconDefinition[] = [
  {
    key: 'aws',
    category: 'cloud',
    label: 'AWS',
    Component: FaAws,
    color: '#FF9900',
    searchTerms: ['amazon web services', 'amazon'],
  },
  {
    key: 'azure',
    category: 'cloud',
    label: 'Azure',
    Component: FaMicrosoft,
    color: '#0078D4',
    searchTerms: ['azuredevops'],
  },
  {
    key: 'googlecloud',
    category: 'cloud',
    label: 'Google Cloud',
    Component: SiGooglecloud,
    color: '#4285F4',
    searchTerms: ['gcp', 'google cloud platform'],
  },
  {
    key: 'cloudflare',
    category: 'cloud',
    label: 'Cloudflare',
    Component: SiCloudflare,
    color: '#F38020',
    searchTerms: ['cloudflare workers'],
  },
  {
    key: 'vercel',
    category: 'cloud',
    label: 'Vercel',
    Component: SiVercel,
    color: '#000000',
    searchTerms: [],
  },
  {
    key: 'netlify',
    category: 'cloud',
    label: 'Netlify',
    Component: SiNetlify,
    color: '#00C7B7',
    searchTerms: [],
  },
  {
    key: 'heroku',
    category: 'cloud',
    label: 'Heroku',
    Component: SiHeroku,
    color: '#430098',
    searchTerms: [],
  },
  {
    key: 'digitalocean',
    category: 'cloud',
    label: 'DigitalOcean',
    Component: SiDigitalocean,
    color: '#0080FF',
    searchTerms: ['do'],
  },
  {
    key: 'railway',
    category: 'cloud',
    label: 'Railway',
    Component: SiRailway,
    color: '#0B0D0E',
    searchTerms: [],
  },
  {
    key: 'flydotio',
    category: 'cloud',
    label: 'Fly.io',
    Component: SiFlydotio,
    color: '#7C3AED',
    searchTerms: ['fly.io', 'flyio'],
  },
  {
    key: 'awslambda',
    category: 'cloud',
    label: 'AWS Lambda',
    Component: FaAws,
    color: '#FF9900',
    searchTerms: ['lambda', 'aws lambda'],
  },
  {
    key: 'amazons3',
    category: 'cloud',
    label: 'Amazon S3',
    Component: FaAws,
    color: '#569A31',
    searchTerms: ['s3', 'aws s3'],
  },
  {
    key: 'ec2',
    category: 'cloud',
    label: 'Amazon EC2',
    Component: FaAmazon,
    color: '#FF9900',
    searchTerms: ['ec2 service', 'aws ec2'],
  },
  {
    key: 'googlecloudfunctions',
    category: 'cloud',
    label: 'Cloud Functions',
    Component: SiGooglecloud,
    color: '#4285F4',
    searchTerms: ['cloud functions', 'gcf'],
  },
  {
    key: 'googlecloudrun',
    category: 'cloud',
    label: 'Cloud Run',
    Component: SiGooglecloud,
    color: '#4285F4',
    searchTerms: ['cloud run'],
  },
  {
    key: 'firebase-platform',
    category: 'cloud',
    label: 'Firebase',
    Component: SiFirebase,
    color: '#FFCA28',
    searchTerms: ['firebase cloud', 'google firebase'],
  },
];
