import { IconDefinition } from '../types';
import React from 'react';
import {
  CN,
  CZ,
  DE,
  DK,
  ES,
  FI,
  FR,
  GR,
  HU,
  ID,
  IL,
  IN,
  IT,
  JP,
  KR,
  NL,
  NO,
  PL,
  PT,
  RO,
  RU,
  SA,
  SE,
  TH,
  TR,
  UA,
  US,
  VN,
  AC,
  AD,
  AE,
  AF,
  AG,
  AI,
  AL,
  AM,
  AO,
  AQ,
  AR,
  AS,
  AT,
  AU,
  AW,
  AX,
  AZ,
  BA,
  BB,
  BD,
  BE,
  BF,
  BG,
  BH,
  BI,
  BJ,
  BL,
  BM,
  BN,
  BO,
  BQ,
  BQ_BO,
  BQ_SA,
  BQ_SE,
  BR,
  BS,
  BT,
  BV,
  BW,
  BY,
  BZ,
  CA,
  CC,
  CD,
  CF,
  CG,
  CH,
  CI,
  CK,
  CL,
  CM,
  CO,
  CR,
  CU,
  CV,
  CW,
  CX,
  CY,
  DJ,
  DM,
  DO,
  DZ,
  EC,
  EE,
  EG,
  EH,
  ER,
  ES_CT,
  ET,
  EU,
  FJ,
  FK,
  FM,
  FO,
  GA,
  GB,
  GB_ENG,
  GB_NIR,
  GB_SCT,
  GB_WLS,
  GD,
  GE,
  GF,
  GG,
  GH,
  GI,
  GL,
  GM,
  GN,
  GP,
  GQ,
  GS,
  GT,
  GU,
  GW,
  GY,
  HK,
  HM,
  HN,
  HR,
  HT,
  IC,
  IE,
  IM,
  IO,
  IQ,
  IR,
  IS,
  JE,
  JM,
  JO,
  KE,
  KG,
  KH,
  KI,
  KM,
  KN,
  KP,
  KW,
  KY,
  KZ,
  LA,
  LB,
  LC,
  LI,
  LK,
  LR,
  LS,
  LT,
  LU,
  LV,
  LY,
  MA,
  MC,
  MD,
  ME,
  MF,
  MG,
  MH,
  MK,
  ML,
  MM,
  MN,
  MO,
  MP,
  MQ,
  MR,
  MS,
  MT,
  MU,
  MV,
  MW,
  MX,
  MY,
  MZ,
  NA,
  NC,
  NE,
  NF,
  NG,
  NI,
  NP,
  NR,
  NU,
  NZ,
  OM,
  PA,
  PE,
  PF,
  PG,
  PH,
  PK,
  PM,
  PN,
  PR,
  PS,
  PW,
  PY,
  QA,
  RE,
  RS,
  RW,
  SB,
  SC,
  SD,
  SG,
  SH,
  SI,
  SJ,
  SK,
  SL,
  SM,
  SN,
  SO,
  SR,
  SS,
  ST,
  SV,
  SX,
  SY,
  SZ,
  TA,
  TC,
  TD,
  TF,
  TG,
  TJ,
  TK,
  TL,
  TM,
  TN,
  TO,
  TT,
  TV,
  TW,
  TZ,
  UG,
  UM,
  UY,
  UZ,
  VA,
  VC,
  VE,
  VG,
  VI,
  VU,
  WF,
  WS,
  XA,
  XC,
  XK,
  XO,
  YE,
  YT,
  ZA,
  ZM,
  ZW,
} from 'country-flag-icons/react/3x2';

type FlagProps = { className?: string; size?: number; style?: React.CSSProperties };

function flag(Flag: typeof US) {
  return (props: FlagProps) => <Flag className={props.className} style={props.style} />;
}

function flagWithViewBox(Flag: typeof US, viewBox: string) {
  return (props: FlagProps) => <Flag className={props.className} style={props.style} viewBox={viewBox} />;
}

export const countryFlagIcons: IconDefinition[] = [
  {
    key: 'cn',
    category: 'country-flag',
    label: 'China',
    Component: flag(CN),
    color: '#666',
    searchTerms: ['chinese', '中文', 'mandarin', 'china'],
  },
  {
    key: 'cz',
    category: 'country-flag',
    label: 'Czech Republic',
    Component: flag(CZ),
    color: '#666',
    searchTerms: ['czech', 'čeština', 'czech republic', 'czechia'],
  },
  {
    key: 'de',
    category: 'country-flag',
    label: 'Germany',
    Component: flag(DE),
    color: '#666',
    searchTerms: ['german', 'deutsch', 'germany'],
  },
  {
    key: 'dk',
    category: 'country-flag',
    label: 'Denmark',
    Component: flag(DK),
    color: '#666',
    searchTerms: ['danish', 'dansk', 'denmark'],
  },
  {
    key: 'es',
    category: 'country-flag',
    label: 'Spain',
    Component: flag(ES),
    color: '#666',
    searchTerms: ['spanish', 'español', 'castellano', 'spain'],
  },
  {
    key: 'fi',
    category: 'country-flag',
    label: 'Finland',
    Component: flag(FI),
    color: '#666',
    searchTerms: ['finnish', 'suomi', 'finland'],
  },
  {
    key: 'fr',
    category: 'country-flag',
    label: 'France',
    Component: flag(FR),
    color: '#666',
    searchTerms: ['french', 'français', 'france'],
  },
  {
    key: 'gr',
    category: 'country-flag',
    label: 'Greece',
    Component: flag(GR),
    color: '#666',
    searchTerms: ['greek', 'ελληνικά', 'greece'],
  },
  {
    key: 'hu',
    category: 'country-flag',
    label: 'Hungary',
    Component: flag(HU),
    color: '#666',
    searchTerms: ['hungarian', 'magyar', 'hungary'],
  },
  {
    key: 'id',
    category: 'country-flag',
    label: 'Indonesia',
    Component: flag(ID),
    color: '#666',
    searchTerms: ['indonesian', 'bahasa indonesia', 'indonesia'],
  },
  {
    key: 'il',
    category: 'country-flag',
    label: 'Israel',
    Component: flag(IL),
    color: '#666',
    searchTerms: ['hebrew', 'עברית', 'israel'],
  },
  {
    key: 'in',
    category: 'country-flag',
    label: 'India',
    Component: flag(IN),
    color: '#666',
    searchTerms: ['hindi', 'हिन्दी', 'india'],
  },
  {
    key: 'it',
    category: 'country-flag',
    label: 'Italy',
    Component: flag(IT),
    color: '#666',
    searchTerms: ['italian', 'italiano', 'italy'],
  },
  {
    key: 'jp',
    category: 'country-flag',
    label: 'Japan',
    Component: flag(JP),
    color: '#666',
    searchTerms: ['japanese', '日本語', 'japan'],
  },
  {
    key: 'kr',
    category: 'country-flag',
    label: 'South Korea',
    Component: flag(KR),
    color: '#666',
    searchTerms: ['korean', '한국어', 'korea', 'south korea'],
  },
  {
    key: 'nl',
    category: 'country-flag',
    label: 'Netherlands',
    Component: flag(NL),
    color: '#666',
    searchTerms: ['dutch', 'nederlands', 'netherlands'],
  },
  {
    key: 'no',
    category: 'country-flag',
    label: 'Norway',
    Component: flag(NO),
    color: '#666',
    searchTerms: ['norwegian', 'norsk', 'norway'],
  },
  {
    key: 'pl',
    category: 'country-flag',
    label: 'Poland',
    Component: flag(PL),
    color: '#666',
    searchTerms: ['polish', 'polski', 'poland'],
  },
  {
    key: 'pt',
    category: 'country-flag',
    label: 'Portugal',
    Component: flag(PT),
    color: '#666',
    searchTerms: ['portuguese', 'português', 'portugal', 'brazil'],
  },
  {
    key: 'ro',
    category: 'country-flag',
    label: 'Romania',
    Component: flag(RO),
    color: '#666',
    searchTerms: ['romanian', 'română', 'romania'],
  },
  {
    key: 'ru',
    category: 'country-flag',
    label: 'Russia',
    Component: flag(RU),
    color: '#666',
    searchTerms: ['russian', 'русский', 'russia', 'russian federation'],
  },
  {
    key: 'sa',
    category: 'country-flag',
    label: 'Saudi Arabia',
    Component: flag(SA),
    color: '#666',
    searchTerms: ['arabic', 'العربية', 'saudi arabia'],
  },
  {
    key: 'se',
    category: 'country-flag',
    label: 'Sweden',
    Component: flag(SE),
    color: '#666',
    searchTerms: ['swedish', 'svenska', 'sweden'],
  },
  {
    key: 'th',
    category: 'country-flag',
    label: 'Thailand',
    Component: flag(TH),
    color: '#666',
    searchTerms: ['thai', 'ไทย', 'thailand'],
  },
  {
    key: 'tr',
    category: 'country-flag',
    label: 'Turkey',
    Component: flag(TR),
    color: '#666',
    searchTerms: ['turkish', 'türkçe', 'turkey', 'turkiye'],
  },
  {
    key: 'ua',
    category: 'country-flag',
    label: 'Ukraine',
    Component: flag(UA),
    color: '#666',
    searchTerms: ['ukrainian', 'українська', 'ukraine'],
  },
  {
    key: 'us',
    category: 'country-flag',
    label: 'United States',
    Component: flag(US),
    color: '#666',
    searchTerms: ['english', 'american english', 'united states', 'usa', 'america'],
  },
  {
    key: 'vn',
    category: 'country-flag',
    label: 'Vietnam',
    Component: flag(VN),
    color: '#666',
    searchTerms: ['vietnamese', 'tiếng việt', 'vietnam'],
  },
  {
    key: 'ac',
    category: 'country-flag',
    label: 'Ascension Island',
    Component: flag(AC),
    color: '#666',
    searchTerms: ['ascension island'],
  },
  {
    key: 'ad',
    category: 'country-flag',
    label: 'Andorra',
    Component: flag(AD),
    color: '#666',
    searchTerms: ['andorra'],
  },
  {
    key: 'ae',
    category: 'country-flag',
    label: 'United Arab Emirates',
    Component: flag(AE),
    color: '#666',
    searchTerms: ['united arab emirates'],
  },
  {
    key: 'af',
    category: 'country-flag',
    label: 'Afghanistan',
    Component: flag(AF),
    color: '#666',
    searchTerms: ['afghanistan'],
  },
  {
    key: 'ag',
    category: 'country-flag',
    label: 'Antigua and Barbuda',
    Component: flag(AG),
    color: '#666',
    searchTerms: ['antigua and barbuda'],
  },
  {
    key: 'ai',
    category: 'country-flag',
    label: 'Anguilla',
    Component: flag(AI),
    color: '#666',
    searchTerms: ['anguilla'],
  },
  {
    key: 'al',
    category: 'country-flag',
    label: 'Albania',
    Component: flag(AL),
    color: '#666',
    searchTerms: ['albania'],
  },
  {
    key: 'am',
    category: 'country-flag',
    label: 'Armenia',
    Component: flag(AM),
    color: '#666',
    searchTerms: ['armenia'],
  },
  {
    key: 'ao',
    category: 'country-flag',
    label: 'Angola',
    Component: flag(AO),
    color: '#666',
    searchTerms: ['angola'],
  },
  {
    key: 'aq',
    category: 'country-flag',
    label: 'Antarctica',
    Component: flag(AQ),
    color: '#666',
    searchTerms: ['antarctica'],
  },
  {
    key: 'ar',
    category: 'country-flag',
    label: 'Argentina',
    Component: flag(AR),
    color: '#666',
    searchTerms: ['argentina'],
  },
  {
    key: 'as',
    category: 'country-flag',
    label: 'American Samoa',
    Component: flag(AS),
    color: '#666',
    searchTerms: ['american samoa'],
  },
  {
    key: 'at',
    category: 'country-flag',
    label: 'Austria',
    Component: flag(AT),
    color: '#666',
    searchTerms: ['austria'],
  },
  {
    key: 'au',
    category: 'country-flag',
    label: 'Australia',
    Component: flag(AU),
    color: '#666',
    searchTerms: ['australia'],
  },
  {
    key: 'aw',
    category: 'country-flag',
    label: 'Aruba',
    Component: flag(AW),
    color: '#666',
    searchTerms: ['aruba'],
  },
  {
    key: 'ax',
    category: 'country-flag',
    label: 'Åland Islands',
    Component: flag(AX),
    color: '#666',
    searchTerms: ['åland islands'],
  },
  {
    key: 'az',
    category: 'country-flag',
    label: 'Azerbaijan',
    Component: flag(AZ),
    color: '#666',
    searchTerms: ['azerbaijan'],
  },
  {
    key: 'ba',
    category: 'country-flag',
    label: 'Bosnia and Herzegovina',
    Component: flag(BA),
    color: '#666',
    searchTerms: ['bosnia and herzegovina'],
  },
  {
    key: 'bb',
    category: 'country-flag',
    label: 'Barbados',
    Component: flag(BB),
    color: '#666',
    searchTerms: ['barbados'],
  },
  {
    key: 'bd',
    category: 'country-flag',
    label: 'Bangladesh',
    Component: flag(BD),
    color: '#666',
    searchTerms: ['bangladesh'],
  },
  {
    key: 'be',
    category: 'country-flag',
    label: 'Belgium',
    Component: flag(BE),
    color: '#666',
    searchTerms: ['belgium'],
  },
  {
    key: 'bf',
    category: 'country-flag',
    label: 'Burkina Faso',
    Component: flag(BF),
    color: '#666',
    searchTerms: ['burkina faso'],
  },
  {
    key: 'bg',
    category: 'country-flag',
    label: 'Bulgaria',
    Component: flag(BG),
    color: '#666',
    searchTerms: ['bulgaria'],
  },
  {
    key: 'bh',
    category: 'country-flag',
    label: 'Bahrain',
    Component: flag(BH),
    color: '#666',
    searchTerms: ['bahrain'],
  },
  {
    key: 'bi',
    category: 'country-flag',
    label: 'Burundi',
    Component: flag(BI),
    color: '#666',
    searchTerms: ['burundi'],
  },
  {
    key: 'bj',
    category: 'country-flag',
    label: 'Benin',
    Component: flag(BJ),
    color: '#666',
    searchTerms: ['benin'],
  },
  {
    key: 'bl',
    category: 'country-flag',
    label: 'Saint Barthélemy',
    Component: flag(BL),
    color: '#666',
    searchTerms: ['saint barthélemy'],
  },
  {
    key: 'bm',
    category: 'country-flag',
    label: 'Bermuda',
    Component: flag(BM),
    color: '#666',
    searchTerms: ['bermuda'],
  },
  {
    key: 'bn',
    category: 'country-flag',
    label: 'Brunei',
    Component: flag(BN),
    color: '#666',
    searchTerms: ['brunei'],
  },
  {
    key: 'bo',
    category: 'country-flag',
    label: 'Bolivia',
    Component: flag(BO),
    color: '#666',
    searchTerms: ['bolivia'],
  },
  {
    key: 'bq',
    category: 'country-flag',
    label: 'Caribbean Netherlands',
    Component: flag(BQ),
    color: '#666',
    searchTerms: ['caribbean netherlands'],
  },
  {
    key: 'bq_bo',
    category: 'country-flag',
    label: 'Bonaire',
    Component: flag(BQ_BO),
    color: '#666',
    searchTerms: ['bonaire'],
  },
  {
    key: 'bq_sa',
    category: 'country-flag',
    label: 'Saba',
    Component: flag(BQ_SA),
    color: '#666',
    searchTerms: ['saba'],
  },
  {
    key: 'bq_se',
    category: 'country-flag',
    label: 'Sint Eustatius',
    Component: flagWithViewBox(BQ_SE, '0 0 900 600'),
    color: '#666',
    searchTerms: ['sint eustatius'],
  },
  {
    key: 'br',
    category: 'country-flag',
    label: 'Brazil',
    Component: flag(BR),
    color: '#666',
    searchTerms: ['brazil'],
  },
  {
    key: 'bs',
    category: 'country-flag',
    label: 'Bahamas',
    Component: flag(BS),
    color: '#666',
    searchTerms: ['bahamas'],
  },
  {
    key: 'bt',
    category: 'country-flag',
    label: 'Bhutan',
    Component: flag(BT),
    color: '#666',
    searchTerms: ['bhutan'],
  },
  {
    key: 'bv',
    category: 'country-flag',
    label: 'Bouvet Island',
    Component: flag(BV),
    color: '#666',
    searchTerms: ['bouvet island'],
  },
  {
    key: 'bw',
    category: 'country-flag',
    label: 'Botswana',
    Component: flag(BW),
    color: '#666',
    searchTerms: ['botswana'],
  },
  {
    key: 'by',
    category: 'country-flag',
    label: 'Belarus',
    Component: flag(BY),
    color: '#666',
    searchTerms: ['belarus'],
  },
  {
    key: 'bz',
    category: 'country-flag',
    label: 'Belize',
    Component: flag(BZ),
    color: '#666',
    searchTerms: ['belize'],
  },
  {
    key: 'ca',
    category: 'country-flag',
    label: 'Canada',
    Component: flag(CA),
    color: '#666',
    searchTerms: ['canada'],
  },
  {
    key: 'cc',
    category: 'country-flag',
    label: 'Cocos (Keeling) Islands',
    Component: flag(CC),
    color: '#666',
    searchTerms: ['cocos (keeling) islands'],
  },
  {
    key: 'cd',
    category: 'country-flag',
    label: 'DR Congo',
    Component: flag(CD),
    color: '#666',
    searchTerms: ['dr congo', 'congo'],
  },
  {
    key: 'cf',
    category: 'country-flag',
    label: 'Central African Republic',
    Component: flag(CF),
    color: '#666',
    searchTerms: ['central african republic'],
  },
  {
    key: 'cg',
    category: 'country-flag',
    label: 'Republic of the Congo',
    Component: flag(CG),
    color: '#666',
    searchTerms: ['republic of the congo', 'congo'],
  },
  {
    key: 'ch',
    category: 'country-flag',
    label: 'Switzerland',
    Component: flag(CH),
    color: '#666',
    searchTerms: ['switzerland'],
  },
  {
    key: 'ci',
    category: 'country-flag',
    label: 'Côte d\'Ivoire',
    Component: flag(CI),
    color: '#666',
    searchTerms: ['côte d\'ivoire', 'ivory coast'],
  },
  {
    key: 'ck',
    category: 'country-flag',
    label: 'Cook Islands',
    Component: flag(CK),
    color: '#666',
    searchTerms: ['cook islands'],
  },
  {
    key: 'cl',
    category: 'country-flag',
    label: 'Chile',
    Component: flag(CL),
    color: '#666',
    searchTerms: ['chile'],
  },
  {
    key: 'cm',
    category: 'country-flag',
    label: 'Cameroon',
    Component: flag(CM),
    color: '#666',
    searchTerms: ['cameroon'],
  },
  {
    key: 'co',
    category: 'country-flag',
    label: 'Colombia',
    Component: flag(CO),
    color: '#666',
    searchTerms: ['colombia'],
  },
  {
    key: 'cr',
    category: 'country-flag',
    label: 'Costa Rica',
    Component: flag(CR),
    color: '#666',
    searchTerms: ['costa rica'],
  },
  {
    key: 'cu',
    category: 'country-flag',
    label: 'Cuba',
    Component: flag(CU),
    color: '#666',
    searchTerms: ['cuba'],
  },
  {
    key: 'cv',
    category: 'country-flag',
    label: 'Cape Verde',
    Component: flag(CV),
    color: '#666',
    searchTerms: ['cape verde'],
  },
  {
    key: 'cw',
    category: 'country-flag',
    label: 'Curaçao',
    Component: flag(CW),
    color: '#666',
    searchTerms: ['curaçao'],
  },
  {
    key: 'cx',
    category: 'country-flag',
    label: 'Christmas Island',
    Component: flag(CX),
    color: '#666',
    searchTerms: ['christmas island'],
  },
  {
    key: 'cy',
    category: 'country-flag',
    label: 'Cyprus',
    Component: flag(CY),
    color: '#666',
    searchTerms: ['cyprus'],
  },
  {
    key: 'dj',
    category: 'country-flag',
    label: 'Djibouti',
    Component: flag(DJ),
    color: '#666',
    searchTerms: ['djibouti'],
  },
  {
    key: 'dm',
    category: 'country-flag',
    label: 'Dominica',
    Component: flag(DM),
    color: '#666',
    searchTerms: ['dominica'],
  },
  {
    key: 'do',
    category: 'country-flag',
    label: 'Dominican Republic',
    Component: flag(DO),
    color: '#666',
    searchTerms: ['dominican republic'],
  },
  {
    key: 'dz',
    category: 'country-flag',
    label: 'Algeria',
    Component: flag(DZ),
    color: '#666',
    searchTerms: ['algeria'],
  },
  {
    key: 'ec',
    category: 'country-flag',
    label: 'Ecuador',
    Component: flag(EC),
    color: '#666',
    searchTerms: ['ecuador'],
  },
  {
    key: 'ee',
    category: 'country-flag',
    label: 'Estonia',
    Component: flag(EE),
    color: '#666',
    searchTerms: ['estonia'],
  },
  {
    key: 'eg',
    category: 'country-flag',
    label: 'Egypt',
    Component: flag(EG),
    color: '#666',
    searchTerms: ['egypt'],
  },
  {
    key: 'eh',
    category: 'country-flag',
    label: 'Western Sahara',
    Component: flag(EH),
    color: '#666',
    searchTerms: ['western sahara'],
  },
  {
    key: 'er',
    category: 'country-flag',
    label: 'Eritrea',
    Component: flag(ER),
    color: '#666',
    searchTerms: ['eritrea'],
  },
  {
    key: 'es_ct',
    category: 'country-flag',
    label: 'Catalonia',
    Component: flagWithViewBox(ES_CT, '0 0 810 540'),
    color: '#666',
    searchTerms: ['catalonia'],
  },
  {
    key: 'et',
    category: 'country-flag',
    label: 'Ethiopia',
    Component: flag(ET),
    color: '#666',
    searchTerms: ['ethiopia'],
  },
  {
    key: 'eu',
    category: 'country-flag',
    label: 'European Union',
    Component: flag(EU),
    color: '#666',
    searchTerms: ['european union'],
  },
  {
    key: 'fj',
    category: 'country-flag',
    label: 'Fiji',
    Component: flag(FJ),
    color: '#666',
    searchTerms: ['fiji'],
  },
  {
    key: 'fk',
    category: 'country-flag',
    label: 'Falkland Islands',
    Component: flag(FK),
    color: '#666',
    searchTerms: ['falkland islands'],
  },
  {
    key: 'fm',
    category: 'country-flag',
    label: 'Micronesia',
    Component: flag(FM),
    color: '#666',
    searchTerms: ['micronesia'],
  },
  {
    key: 'fo',
    category: 'country-flag',
    label: 'Faroe Islands',
    Component: flag(FO),
    color: '#666',
    searchTerms: ['faroe islands'],
  },
  {
    key: 'ga',
    category: 'country-flag',
    label: 'Gabon',
    Component: flag(GA),
    color: '#666',
    searchTerms: ['gabon'],
  },
  {
    key: 'gb',
    category: 'country-flag',
    label: 'United Kingdom',
    Component: flag(GB),
    color: '#666',
    searchTerms: ['united kingdom', 'uk', 'great britain'],
  },
  {
    key: 'gb_eng',
    category: 'country-flag',
    label: 'England',
    Component: flag(GB_ENG),
    color: '#666',
    searchTerms: ['england'],
  },
  {
    key: 'gb_nir',
    category: 'country-flag',
    label: 'Northern Ireland',
    Component: flag(GB_NIR),
    color: '#666',
    searchTerms: ['northern ireland'],
  },
  {
    key: 'gb_sct',
    category: 'country-flag',
    label: 'Scotland',
    Component: flag(GB_SCT),
    color: '#666',
    searchTerms: ['scotland'],
  },
  {
    key: 'gb_wls',
    category: 'country-flag',
    label: 'Wales',
    Component: flag(GB_WLS),
    color: '#666',
    searchTerms: ['wales'],
  },
  {
    key: 'gd',
    category: 'country-flag',
    label: 'Grenada',
    Component: flag(GD),
    color: '#666',
    searchTerms: ['grenada'],
  },
  {
    key: 'ge',
    category: 'country-flag',
    label: 'Georgia',
    Component: flag(GE),
    color: '#666',
    searchTerms: ['georgia'],
  },
  {
    key: 'gf',
    category: 'country-flag',
    label: 'French Guiana',
    Component: flag(GF),
    color: '#666',
    searchTerms: ['french guiana'],
  },
  {
    key: 'gg',
    category: 'country-flag',
    label: 'Guernsey',
    Component: flag(GG),
    color: '#666',
    searchTerms: ['guernsey'],
  },
  {
    key: 'gh',
    category: 'country-flag',
    label: 'Ghana',
    Component: flag(GH),
    color: '#666',
    searchTerms: ['ghana'],
  },
  {
    key: 'gi',
    category: 'country-flag',
    label: 'Gibraltar',
    Component: flag(GI),
    color: '#666',
    searchTerms: ['gibraltar'],
  },
  {
    key: 'gl',
    category: 'country-flag',
    label: 'Greenland',
    Component: flag(GL),
    color: '#666',
    searchTerms: ['greenland'],
  },
  {
    key: 'gm',
    category: 'country-flag',
    label: 'Gambia',
    Component: flag(GM),
    color: '#666',
    searchTerms: ['gambia'],
  },
  {
    key: 'gn',
    category: 'country-flag',
    label: 'Guinea',
    Component: flag(GN),
    color: '#666',
    searchTerms: ['guinea'],
  },
  {
    key: 'gp',
    category: 'country-flag',
    label: 'Guadeloupe',
    Component: flag(GP),
    color: '#666',
    searchTerms: ['guadeloupe'],
  },
  {
    key: 'gq',
    category: 'country-flag',
    label: 'Equatorial Guinea',
    Component: flag(GQ),
    color: '#666',
    searchTerms: ['equatorial guinea'],
  },
  {
    key: 'gs',
    category: 'country-flag',
    label: 'South Georgia',
    Component: flag(GS),
    color: '#666',
    searchTerms: ['south georgia'],
  },
  {
    key: 'gt',
    category: 'country-flag',
    label: 'Guatemala',
    Component: flag(GT),
    color: '#666',
    searchTerms: ['guatemala'],
  },
  {
    key: 'gu',
    category: 'country-flag',
    label: 'Guam',
    Component: flag(GU),
    color: '#666',
    searchTerms: ['guam'],
  },
  {
    key: 'gw',
    category: 'country-flag',
    label: 'Guinea-Bissau',
    Component: flag(GW),
    color: '#666',
    searchTerms: ['guinea-bissau'],
  },
  {
    key: 'gy',
    category: 'country-flag',
    label: 'Guyana',
    Component: flag(GY),
    color: '#666',
    searchTerms: ['guyana'],
  },
  {
    key: 'hk',
    category: 'country-flag',
    label: 'Hong Kong',
    Component: flag(HK),
    color: '#666',
    searchTerms: ['hong kong'],
  },
  {
    key: 'hm',
    category: 'country-flag',
    label: 'Heard Island',
    Component: flag(HM),
    color: '#666',
    searchTerms: ['heard island'],
  },
  {
    key: 'hn',
    category: 'country-flag',
    label: 'Honduras',
    Component: flag(HN),
    color: '#666',
    searchTerms: ['honduras'],
  },
  {
    key: 'hr',
    category: 'country-flag',
    label: 'Croatia',
    Component: flag(HR),
    color: '#666',
    searchTerms: ['croatia'],
  },
  {
    key: 'ht',
    category: 'country-flag',
    label: 'Haiti',
    Component: flag(HT),
    color: '#666',
    searchTerms: ['haiti'],
  },
  {
    key: 'ic',
    category: 'country-flag',
    label: 'Canary Islands',
    Component: flag(IC),
    color: '#666',
    searchTerms: ['canary islands'],
  },
  {
    key: 'ie',
    category: 'country-flag',
    label: 'Ireland',
    Component: flag(IE),
    color: '#666',
    searchTerms: ['ireland'],
  },
  {
    key: 'im',
    category: 'country-flag',
    label: 'Isle of Man',
    Component: flag(IM),
    color: '#666',
    searchTerms: ['isle of man'],
  },
  {
    key: 'io',
    category: 'country-flag',
    label: 'British Indian Ocean Territory',
    Component: flag(IO),
    color: '#666',
    searchTerms: ['british indian ocean territory'],
  },
  {
    key: 'iq',
    category: 'country-flag',
    label: 'Iraq',
    Component: flag(IQ),
    color: '#666',
    searchTerms: ['iraq'],
  },
  {
    key: 'ir',
    category: 'country-flag',
    label: 'Iran',
    Component: flag(IR),
    color: '#666',
    searchTerms: ['iran', 'persian'],
  },
  {
    key: 'is',
    category: 'country-flag',
    label: 'Iceland',
    Component: flag(IS),
    color: '#666',
    searchTerms: ['iceland'],
  },
  {
    key: 'je',
    category: 'country-flag',
    label: 'Jersey',
    Component: flag(JE),
    color: '#666',
    searchTerms: ['jersey'],
  },
  {
    key: 'jm',
    category: 'country-flag',
    label: 'Jamaica',
    Component: flag(JM),
    color: '#666',
    searchTerms: ['jamaica'],
  },
  {
    key: 'jo',
    category: 'country-flag',
    label: 'Jordan',
    Component: flag(JO),
    color: '#666',
    searchTerms: ['jordan'],
  },
  {
    key: 'ke',
    category: 'country-flag',
    label: 'Kenya',
    Component: flag(KE),
    color: '#666',
    searchTerms: ['kenya'],
  },
  {
    key: 'kg',
    category: 'country-flag',
    label: 'Kyrgyzstan',
    Component: flag(KG),
    color: '#666',
    searchTerms: ['kyrgyzstan'],
  },
  {
    key: 'kh',
    category: 'country-flag',
    label: 'Cambodia',
    Component: flag(KH),
    color: '#666',
    searchTerms: ['cambodia'],
  },
  {
    key: 'ki',
    category: 'country-flag',
    label: 'Kiribati',
    Component: flag(KI),
    color: '#666',
    searchTerms: ['kiribati'],
  },
  {
    key: 'km',
    category: 'country-flag',
    label: 'Comoros',
    Component: flag(KM),
    color: '#666',
    searchTerms: ['comoros'],
  },
  {
    key: 'kn',
    category: 'country-flag',
    label: 'Saint Kitts and Nevis',
    Component: flag(KN),
    color: '#666',
    searchTerms: ['saint kitts and nevis'],
  },
  {
    key: 'kp',
    category: 'country-flag',
    label: 'North Korea',
    Component: flag(KP),
    color: '#666',
    searchTerms: ['north korea'],
  },
  {
    key: 'kw',
    category: 'country-flag',
    label: 'Kuwait',
    Component: flag(KW),
    color: '#666',
    searchTerms: ['kuwait'],
  },
  {
    key: 'ky',
    category: 'country-flag',
    label: 'Cayman Islands',
    Component: flag(KY),
    color: '#666',
    searchTerms: ['cayman islands'],
  },
  {
    key: 'kz',
    category: 'country-flag',
    label: 'Kazakhstan',
    Component: flag(KZ),
    color: '#666',
    searchTerms: ['kazakhstan'],
  },
  {
    key: 'la',
    category: 'country-flag',
    label: 'Laos',
    Component: flag(LA),
    color: '#666',
    searchTerms: ['laos'],
  },
  {
    key: 'lb',
    category: 'country-flag',
    label: 'Lebanon',
    Component: flag(LB),
    color: '#666',
    searchTerms: ['lebanon'],
  },
  {
    key: 'lc',
    category: 'country-flag',
    label: 'Saint Lucia',
    Component: flag(LC),
    color: '#666',
    searchTerms: ['saint lucia'],
  },
  {
    key: 'li',
    category: 'country-flag',
    label: 'Liechtenstein',
    Component: flag(LI),
    color: '#666',
    searchTerms: ['liechtenstein'],
  },
  {
    key: 'lk',
    category: 'country-flag',
    label: 'Sri Lanka',
    Component: flag(LK),
    color: '#666',
    searchTerms: ['sri lanka'],
  },
  {
    key: 'lr',
    category: 'country-flag',
    label: 'Liberia',
    Component: flag(LR),
    color: '#666',
    searchTerms: ['liberia'],
  },
  {
    key: 'ls',
    category: 'country-flag',
    label: 'Lesotho',
    Component: flag(LS),
    color: '#666',
    searchTerms: ['lesotho'],
  },
  {
    key: 'lt',
    category: 'country-flag',
    label: 'Lithuania',
    Component: flag(LT),
    color: '#666',
    searchTerms: ['lithuania'],
  },
  {
    key: 'lu',
    category: 'country-flag',
    label: 'Luxembourg',
    Component: flag(LU),
    color: '#666',
    searchTerms: ['luxembourg'],
  },
  {
    key: 'lv',
    category: 'country-flag',
    label: 'Latvia',
    Component: flag(LV),
    color: '#666',
    searchTerms: ['latvia'],
  },
  {
    key: 'ly',
    category: 'country-flag',
    label: 'Libya',
    Component: flag(LY),
    color: '#666',
    searchTerms: ['libya'],
  },
  {
    key: 'ma',
    category: 'country-flag',
    label: 'Morocco',
    Component: flag(MA),
    color: '#666',
    searchTerms: ['morocco'],
  },
  {
    key: 'mc',
    category: 'country-flag',
    label: 'Monaco',
    Component: flag(MC),
    color: '#666',
    searchTerms: ['monaco'],
  },
  {
    key: 'md',
    category: 'country-flag',
    label: 'Moldova',
    Component: flag(MD),
    color: '#666',
    searchTerms: ['moldova'],
  },
  {
    key: 'me',
    category: 'country-flag',
    label: 'Montenegro',
    Component: flag(ME),
    color: '#666',
    searchTerms: ['montenegro'],
  },
  {
    key: 'mf',
    category: 'country-flag',
    label: 'Saint Martin',
    Component: flag(MF),
    color: '#666',
    searchTerms: ['saint martin'],
  },
  {
    key: 'mg',
    category: 'country-flag',
    label: 'Madagascar',
    Component: flag(MG),
    color: '#666',
    searchTerms: ['madagascar'],
  },
  {
    key: 'mh',
    category: 'country-flag',
    label: 'Marshall Islands',
    Component: flag(MH),
    color: '#666',
    searchTerms: ['marshall islands'],
  },
  {
    key: 'mk',
    category: 'country-flag',
    label: 'North Macedonia',
    Component: flag(MK),
    color: '#666',
    searchTerms: ['north macedonia', 'macedonia'],
  },
  {
    key: 'ml',
    category: 'country-flag',
    label: 'Mali',
    Component: flag(ML),
    color: '#666',
    searchTerms: ['mali'],
  },
  {
    key: 'mm',
    category: 'country-flag',
    label: 'Myanmar',
    Component: flag(MM),
    color: '#666',
    searchTerms: ['myanmar', 'burma'],
  },
  {
    key: 'mn',
    category: 'country-flag',
    label: 'Mongolia',
    Component: flag(MN),
    color: '#666',
    searchTerms: ['mongolia'],
  },
  {
    key: 'mo',
    category: 'country-flag',
    label: 'Macau',
    Component: flag(MO),
    color: '#666',
    searchTerms: ['macau'],
  },
  {
    key: 'mp',
    category: 'country-flag',
    label: 'Northern Mariana Islands',
    Component: flag(MP),
    color: '#666',
    searchTerms: ['northern mariana islands'],
  },
  {
    key: 'mq',
    category: 'country-flag',
    label: 'Martinique',
    Component: flag(MQ),
    color: '#666',
    searchTerms: ['martinique'],
  },
  {
    key: 'mr',
    category: 'country-flag',
    label: 'Mauritania',
    Component: flag(MR),
    color: '#666',
    searchTerms: ['mauritania'],
  },
  {
    key: 'ms',
    category: 'country-flag',
    label: 'Montserrat',
    Component: flag(MS),
    color: '#666',
    searchTerms: ['montserrat'],
  },
  {
    key: 'mt',
    category: 'country-flag',
    label: 'Malta',
    Component: flag(MT),
    color: '#666',
    searchTerms: ['malta'],
  },
  {
    key: 'mu',
    category: 'country-flag',
    label: 'Mauritius',
    Component: flag(MU),
    color: '#666',
    searchTerms: ['mauritius'],
  },
  {
    key: 'mv',
    category: 'country-flag',
    label: 'Maldives',
    Component: flag(MV),
    color: '#666',
    searchTerms: ['maldives'],
  },
  {
    key: 'mw',
    category: 'country-flag',
    label: 'Malawi',
    Component: flag(MW),
    color: '#666',
    searchTerms: ['malawi'],
  },
  {
    key: 'mx',
    category: 'country-flag',
    label: 'Mexico',
    Component: flag(MX),
    color: '#666',
    searchTerms: ['mexico'],
  },
  {
    key: 'my',
    category: 'country-flag',
    label: 'Malaysia',
    Component: flag(MY),
    color: '#666',
    searchTerms: ['malaysia'],
  },
  {
    key: 'mz',
    category: 'country-flag',
    label: 'Mozambique',
    Component: flag(MZ),
    color: '#666',
    searchTerms: ['mozambique'],
  },
  {
    key: 'na',
    category: 'country-flag',
    label: 'Namibia',
    Component: flag(NA),
    color: '#666',
    searchTerms: ['namibia'],
  },
  {
    key: 'nc',
    category: 'country-flag',
    label: 'New Caledonia',
    Component: flag(NC),
    color: '#666',
    searchTerms: ['new caledonia'],
  },
  {
    key: 'ne',
    category: 'country-flag',
    label: 'Niger',
    Component: flag(NE),
    color: '#666',
    searchTerms: ['niger'],
  },
  {
    key: 'nf',
    category: 'country-flag',
    label: 'Norfolk Island',
    Component: flag(NF),
    color: '#666',
    searchTerms: ['norfolk island'],
  },
  {
    key: 'ng',
    category: 'country-flag',
    label: 'Nigeria',
    Component: flag(NG),
    color: '#666',
    searchTerms: ['nigeria'],
  },
  {
    key: 'ni',
    category: 'country-flag',
    label: 'Nicaragua',
    Component: flag(NI),
    color: '#666',
    searchTerms: ['nicaragua'],
  },
  {
    key: 'np',
    category: 'country-flag',
    label: 'Nepal',
    Component: flag(NP),
    color: '#666',
    searchTerms: ['nepal'],
  },
  {
    key: 'nr',
    category: 'country-flag',
    label: 'Nauru',
    Component: flag(NR),
    color: '#666',
    searchTerms: ['nauru'],
  },
  {
    key: 'nu',
    category: 'country-flag',
    label: 'Niue',
    Component: flag(NU),
    color: '#666',
    searchTerms: ['niue'],
  },
  {
    key: 'nz',
    category: 'country-flag',
    label: 'New Zealand',
    Component: flag(NZ),
    color: '#666',
    searchTerms: ['new zealand'],
  },
  {
    key: 'om',
    category: 'country-flag',
    label: 'Oman',
    Component: flag(OM),
    color: '#666',
    searchTerms: ['oman'],
  },
  {
    key: 'pa',
    category: 'country-flag',
    label: 'Panama',
    Component: flag(PA),
    color: '#666',
    searchTerms: ['panama'],
  },
  {
    key: 'pe',
    category: 'country-flag',
    label: 'Peru',
    Component: flag(PE),
    color: '#666',
    searchTerms: ['peru'],
  },
  {
    key: 'pf',
    category: 'country-flag',
    label: 'French Polynesia',
    Component: flag(PF),
    color: '#666',
    searchTerms: ['french polynesia'],
  },
  {
    key: 'pg',
    category: 'country-flag',
    label: 'Papua New Guinea',
    Component: flag(PG),
    color: '#666',
    searchTerms: ['papua new guinea'],
  },
  {
    key: 'ph',
    category: 'country-flag',
    label: 'Philippines',
    Component: flag(PH),
    color: '#666',
    searchTerms: ['philippines'],
  },
  {
    key: 'pk',
    category: 'country-flag',
    label: 'Pakistan',
    Component: flag(PK),
    color: '#666',
    searchTerms: ['pakistan'],
  },
  {
    key: 'pm',
    category: 'country-flag',
    label: 'Saint Pierre and Miquelon',
    Component: flag(PM),
    color: '#666',
    searchTerms: ['saint pierre and miquelon'],
  },
  {
    key: 'pn',
    category: 'country-flag',
    label: 'Pitcairn Islands',
    Component: flag(PN),
    color: '#666',
    searchTerms: ['pitcairn islands'],
  },
  {
    key: 'pr',
    category: 'country-flag',
    label: 'Puerto Rico',
    Component: flag(PR),
    color: '#666',
    searchTerms: ['puerto rico'],
  },
  {
    key: 'ps',
    category: 'country-flag',
    label: 'Palestine',
    Component: flag(PS),
    color: '#666',
    searchTerms: ['palestine'],
  },
  {
    key: 'pw',
    category: 'country-flag',
    label: 'Palau',
    Component: flag(PW),
    color: '#666',
    searchTerms: ['palau'],
  },
  {
    key: 'py',
    category: 'country-flag',
    label: 'Paraguay',
    Component: flag(PY),
    color: '#666',
    searchTerms: ['paraguay'],
  },
  {
    key: 'qa',
    category: 'country-flag',
    label: 'Qatar',
    Component: flag(QA),
    color: '#666',
    searchTerms: ['qatar'],
  },
  {
    key: 're',
    category: 'country-flag',
    label: 'Réunion',
    Component: flag(RE),
    color: '#666',
    searchTerms: ['réunion'],
  },
  {
    key: 'rs',
    category: 'country-flag',
    label: 'Serbia',
    Component: flag(RS),
    color: '#666',
    searchTerms: ['serbia'],
  },
  {
    key: 'rw',
    category: 'country-flag',
    label: 'Rwanda',
    Component: flag(RW),
    color: '#666',
    searchTerms: ['rwanda'],
  },
  {
    key: 'sb',
    category: 'country-flag',
    label: 'Solomon Islands',
    Component: flag(SB),
    color: '#666',
    searchTerms: ['solomon islands'],
  },
  {
    key: 'sc',
    category: 'country-flag',
    label: 'Seychelles',
    Component: flag(SC),
    color: '#666',
    searchTerms: ['seychelles'],
  },
  {
    key: 'sd',
    category: 'country-flag',
    label: 'Sudan',
    Component: flag(SD),
    color: '#666',
    searchTerms: ['sudan'],
  },
  {
    key: 'sg',
    category: 'country-flag',
    label: 'Singapore',
    Component: flag(SG),
    color: '#666',
    searchTerms: ['singapore'],
  },
  {
    key: 'sh',
    category: 'country-flag',
    label: 'Saint Helena',
    Component: flag(SH),
    color: '#666',
    searchTerms: ['saint helena'],
  },
  {
    key: 'si',
    category: 'country-flag',
    label: 'Slovenia',
    Component: flag(SI),
    color: '#666',
    searchTerms: ['slovenia'],
  },
  {
    key: 'sj',
    category: 'country-flag',
    label: 'Svalbard',
    Component: flag(SJ),
    color: '#666',
    searchTerms: ['svalbard'],
  },
  {
    key: 'sk',
    category: 'country-flag',
    label: 'Slovakia',
    Component: flag(SK),
    color: '#666',
    searchTerms: ['slovakia'],
  },
  {
    key: 'sl',
    category: 'country-flag',
    label: 'Sierra Leone',
    Component: flag(SL),
    color: '#666',
    searchTerms: ['sierra leone'],
  },
  {
    key: 'sm',
    category: 'country-flag',
    label: 'San Marino',
    Component: flag(SM),
    color: '#666',
    searchTerms: ['san marino'],
  },
  {
    key: 'sn',
    category: 'country-flag',
    label: 'Senegal',
    Component: flag(SN),
    color: '#666',
    searchTerms: ['senegal'],
  },
  {
    key: 'so',
    category: 'country-flag',
    label: 'Somalia',
    Component: flag(SO),
    color: '#666',
    searchTerms: ['somalia'],
  },
  {
    key: 'sr',
    category: 'country-flag',
    label: 'Suriname',
    Component: flag(SR),
    color: '#666',
    searchTerms: ['suriname'],
  },
  {
    key: 'ss',
    category: 'country-flag',
    label: 'South Sudan',
    Component: flag(SS),
    color: '#666',
    searchTerms: ['south sudan'],
  },
  {
    key: 'st',
    category: 'country-flag',
    label: 'São Tomé and Príncipe',
    Component: flag(ST),
    color: '#666',
    searchTerms: ['são tomé and príncipe'],
  },
  {
    key: 'sv',
    category: 'country-flag',
    label: 'El Salvador',
    Component: flag(SV),
    color: '#666',
    searchTerms: ['el salvador'],
  },
  {
    key: 'sx',
    category: 'country-flag',
    label: 'Sint Maarten',
    Component: flag(SX),
    color: '#666',
    searchTerms: ['sint maarten'],
  },
  {
    key: 'sy',
    category: 'country-flag',
    label: 'Syria',
    Component: flag(SY),
    color: '#666',
    searchTerms: ['syria'],
  },
  {
    key: 'sz',
    category: 'country-flag',
    label: 'Eswatini',
    Component: flag(SZ),
    color: '#666',
    searchTerms: ['eswatini'],
  },
  {
    key: 'ta',
    category: 'country-flag',
    label: 'Tristan da Cunha',
    Component: flag(TA),
    color: '#666',
    searchTerms: ['tristan da cunha'],
  },
  {
    key: 'tc',
    category: 'country-flag',
    label: 'Turks and Caicos Islands',
    Component: flag(TC),
    color: '#666',
    searchTerms: ['turks and caicos islands'],
  },
  {
    key: 'td',
    category: 'country-flag',
    label: 'Chad',
    Component: flag(TD),
    color: '#666',
    searchTerms: ['chad'],
  },
  {
    key: 'tf',
    category: 'country-flag',
    label: 'French Southern Territories',
    Component: flag(TF),
    color: '#666',
    searchTerms: ['french southern territories'],
  },
  {
    key: 'tg',
    category: 'country-flag',
    label: 'Togo',
    Component: flag(TG),
    color: '#666',
    searchTerms: ['togo'],
  },
  {
    key: 'tj',
    category: 'country-flag',
    label: 'Tajikistan',
    Component: flag(TJ),
    color: '#666',
    searchTerms: ['tajikistan'],
  },
  {
    key: 'tk',
    category: 'country-flag',
    label: 'Tokelau',
    Component: flag(TK),
    color: '#666',
    searchTerms: ['tokelau'],
  },
  {
    key: 'tl',
    category: 'country-flag',
    label: 'Timor-Leste',
    Component: flag(TL),
    color: '#666',
    searchTerms: ['timor-leste'],
  },
  {
    key: 'tm',
    category: 'country-flag',
    label: 'Turkmenistan',
    Component: flag(TM),
    color: '#666',
    searchTerms: ['turkmenistan'],
  },
  {
    key: 'tn',
    category: 'country-flag',
    label: 'Tunisia',
    Component: flag(TN),
    color: '#666',
    searchTerms: ['tunisia'],
  },
  {
    key: 'to',
    category: 'country-flag',
    label: 'Tonga',
    Component: flag(TO),
    color: '#666',
    searchTerms: ['tonga'],
  },
  {
    key: 'tt',
    category: 'country-flag',
    label: 'Trinidad and Tobago',
    Component: flag(TT),
    color: '#666',
    searchTerms: ['trinidad and tobago'],
  },
  {
    key: 'tv',
    category: 'country-flag',
    label: 'Tuvalu',
    Component: flag(TV),
    color: '#666',
    searchTerms: ['tuvalu'],
  },
  {
    key: 'tw',
    category: 'country-flag',
    label: 'Taiwan',
    Component: flag(TW),
    color: '#666',
    searchTerms: ['taiwan'],
  },
  {
    key: 'tz',
    category: 'country-flag',
    label: 'Tanzania',
    Component: flag(TZ),
    color: '#666',
    searchTerms: ['tanzania'],
  },
  {
    key: 'ug',
    category: 'country-flag',
    label: 'Uganda',
    Component: flag(UG),
    color: '#666',
    searchTerms: ['uganda'],
  },
  {
    key: 'um',
    category: 'country-flag',
    label: 'U.S. Outlying Islands',
    Component: flag(UM),
    color: '#666',
    searchTerms: ['u.s. outlying islands'],
  },
  {
    key: 'uy',
    category: 'country-flag',
    label: 'Uruguay',
    Component: flag(UY),
    color: '#666',
    searchTerms: ['uruguay'],
  },
  {
    key: 'uz',
    category: 'country-flag',
    label: 'Uzbekistan',
    Component: flag(UZ),
    color: '#666',
    searchTerms: ['uzbekistan'],
  },
  {
    key: 'va',
    category: 'country-flag',
    label: 'Vatican City',
    Component: flag(VA),
    color: '#666',
    searchTerms: ['vatican city'],
  },
  {
    key: 'vc',
    category: 'country-flag',
    label: 'Saint Vincent and the Grenadines',
    Component: flag(VC),
    color: '#666',
    searchTerms: ['saint vincent and the grenadines'],
  },
  {
    key: 've',
    category: 'country-flag',
    label: 'Venezuela',
    Component: flag(VE),
    color: '#666',
    searchTerms: ['venezuela'],
  },
  {
    key: 'vg',
    category: 'country-flag',
    label: 'British Virgin Islands',
    Component: flag(VG),
    color: '#666',
    searchTerms: ['british virgin islands'],
  },
  {
    key: 'vi',
    category: 'country-flag',
    label: 'U.S. Virgin Islands',
    Component: flag(VI),
    color: '#666',
    searchTerms: ['u.s. virgin islands'],
  },
  {
    key: 'vu',
    category: 'country-flag',
    label: 'Vanuatu',
    Component: flag(VU),
    color: '#666',
    searchTerms: ['vanuatu'],
  },
  {
    key: 'wf',
    category: 'country-flag',
    label: 'Wallis and Futuna',
    Component: flag(WF),
    color: '#666',
    searchTerms: ['wallis and futuna'],
  },
  {
    key: 'ws',
    category: 'country-flag',
    label: 'Samoa',
    Component: flag(WS),
    color: '#666',
    searchTerms: ['samoa'],
  },
  {
    key: 'xa',
    category: 'country-flag',
    label: 'Acrotiri',
    Component: flag(XA),
    color: '#666',
    searchTerms: ['acrotiri'],
  },
  {
    key: 'xc',
    category: 'country-flag',
    label: 'Northern Cyprus',
    Component: flag(XC),
    color: '#666',
    searchTerms: ['northern cyprus'],
  },
  {
    key: 'xk',
    category: 'country-flag',
    label: 'Kosovo',
    Component: flag(XK),
    color: '#666',
    searchTerms: ['kosovo'],
  },
  {
    key: 'xo',
    category: 'country-flag',
    label: 'Oecusse',
    Component: flag(XO),
    color: '#666',
    searchTerms: ['oecusse'],
  },
  {
    key: 'ye',
    category: 'country-flag',
    label: 'Yemen',
    Component: flag(YE),
    color: '#666',
    searchTerms: ['yemen'],
  },
  {
    key: 'yt',
    category: 'country-flag',
    label: 'Mayotte',
    Component: flag(YT),
    color: '#666',
    searchTerms: ['mayotte'],
  },
  {
    key: 'za',
    category: 'country-flag',
    label: 'South Africa',
    Component: flag(ZA),
    color: '#666',
    searchTerms: ['south africa'],
  },
  {
    key: 'zm',
    category: 'country-flag',
    label: 'Zambia',
    Component: flag(ZM),
    color: '#666',
    searchTerms: ['zambia'],
  },
  {
    key: 'zw',
    category: 'country-flag',
    label: 'Zimbabwe',
    Component: flag(ZW),
    color: '#666',
    searchTerms: ['zimbabwe'],
  },
];
