import { IconDefinition } from '../types';
import { FaAws } from 'react-icons/fa';
import {
  SiPostgresql,
  SiMysql,
  SiSqlite,
  SiMongodb,
  SiRedis,
  SiElasticsearch,
  SiApachecassandra,
  SiMariadb,
  SiSupabase,
  SiFirebase,
  SiPrisma,
  SiNeo4J,
  SiClickhouse,
  SiCockroachlabs,
  SiPlanetscale,
  SiFauna,
  SiDrizzle,
  SiSqlalchemy,
} from 'react-icons/si';

export const databaseIcons: IconDefinition[] = [
  {
    key: 'postgresql',
    category: 'database',
    label: 'PostgreSQL',
    Component: SiPostgresql,
    color: '#4169E1',
    searchTerms: ['postgres'],
  },
  {
    key: 'mysql',
    category: 'database',
    label: 'MySQL',
    Component: SiMysql,
    color: '#4479A1',
    searchTerms: [],
  },
  {
    key: 'sqlite',
    category: 'database',
    label: 'SQLite',
    Component: SiSqlite,
    color: '#003B57',
    searchTerms: [],
  },
  {
    key: 'mongodb',
    category: 'database',
    label: 'MongoDB',
    Component: SiMongodb,
    color: '#47A248',
    searchTerms: ['mongo'],
  },
  {
    key: 'redis',
    category: 'database',
    label: 'Redis',
    Component: SiRedis,
    color: '#FF4438',
    searchTerms: ['redislabs'],
  },
  {
    key: 'elasticsearch',
    category: 'database',
    label: 'Elasticsearch',
    Component: SiElasticsearch,
    color: '#005571',
    searchTerms: ['elastic'],
  },
  {
    key: 'cassandra',
    category: 'database',
    label: 'Cassandra',
    Component: SiApachecassandra,
    color: '#1287B1',
    searchTerms: [],
  },
  {
    key: 'mariadb',
    category: 'database',
    label: 'MariaDB',
    Component: SiMariadb,
    color: '#003545',
    searchTerms: [],
  },
  {
    key: 'supabase',
    category: 'database',
    label: 'Supabase',
    Component: SiSupabase,
    color: '#3FCF8E',
    searchTerms: [],
  },
  {
    key: 'firebase',
    category: 'database',
    label: 'Firebase',
    Component: SiFirebase,
    color: '#FFCA28',
    searchTerms: [],
  },
  {
    key: 'prisma',
    category: 'database',
    label: 'Prisma',
    Component: SiPrisma,
    color: '#2D3748',
    searchTerms: [],
  },
  {
    key: 'dynamodb',
    category: 'database',
    label: 'DynamoDB',
    Component: FaAws,
    color: '#4053D6',
    searchTerms: ['dynamo'],
  },
  {
    key: 'neo4j',
    category: 'database',
    label: 'Neo4j',
    Component: SiNeo4J,
    color: '#4581C3',
    searchTerms: [],
  },
  {
    key: 'clickhouse',
    category: 'database',
    label: 'ClickHouse',
    Component: SiClickhouse,
    color: '#FFCC01',
    searchTerms: [],
  },
  {
    key: 'cockroachdb',
    category: 'database',
    label: 'CockroachDB',
    Component: SiCockroachlabs,
    color: '#6933FF',
    searchTerms: ['cockroach'],
  },
  {
    key: 'planetscale',
    category: 'database',
    label: 'PlanetScale',
    Component: SiPlanetscale,
    color: '#000000',
    searchTerms: [],
  },
  {
    key: 'fauna',
    category: 'database',
    label: 'Fauna',
    Component: SiFauna,
    color: '#3A1AB6',
    searchTerms: [],
  },
  {
    key: 'drizzle',
    category: 'database',
    label: 'Drizzle',
    Component: SiDrizzle,
    color: '#C5F74F',
    searchTerms: ['drizzleorm', 'drizzle orm'],
  },
  {
    key: 'sqlalchemy',
    category: 'database',
    label: 'SQLAlchemy',
    Component: SiSqlalchemy,
    color: '#D71F00',
    searchTerms: [],
  },
];
