import { IconDefinition } from '../types';
import {
  SiReact,
  SiAngular,
  SiVuedotjs,
  SiSvelte,
  SiNextdotjs,
  SiNuxt,
  SiNestjs,
  SiExpress,
  SiDjango,
  SiRubyonrails,
  SiSpringboot,
  SiLaravel,
  SiFastapi,
  SiFlask,
  SiGatsby,
  SiRemix,
  SiAstro,
  SiSolid,
  SiQwik,
  SiNx,
  SiMui,
  SiTailwindcss,
  SiBootstrap,
  SiChakraui,
  SiShadcnui,
  SiRadixui,
  SiAntdesign,
  SiStorybook,
  SiHeadlessui,
  SiSemanticui,
} from 'react-icons/si';

export const frameworkIcons: IconDefinition[] = [
  {
    key: 'react',
    category: 'framework',
    label: 'React',
    Component: SiReact,
    color: '#61DAFB',
    searchTerms: ['reactjs', 'react.js'],
  },
  {
    key: 'angular',
    category: 'framework',
    label: 'Angular',
    Component: SiAngular,
    color: '#DD0031',
    searchTerms: ['ng', 'angularjs'],
  },
  {
    key: 'vue',
    category: 'framework',
    label: 'Vue',
    Component: SiVuedotjs,
    color: '#4FC08D',
    searchTerms: ['vuejs', 'vue.js'],
  },
  {
    key: 'svelte',
    category: 'framework',
    label: 'Svelte',
    Component: SiSvelte,
    color: '#FF3E00',
    searchTerms: ['sveltekit'],
  },
  {
    key: 'nextdotjs',
    category: 'framework',
    label: 'Next.js',
    Component: SiNextdotjs,
    color: '#000000',
    searchTerms: ['next.js', 'nextjs'],
  },
  {
    key: 'nuxt',
    category: 'framework',
    label: 'Nuxt',
    Component: SiNuxt,
    color: '#00DC82',
    searchTerms: ['nuxtjs'],
  },
  {
    key: 'nestjs',
    category: 'framework',
    label: 'NestJS',
    Component: SiNestjs,
    color: '#E0234E',
    searchTerms: ['nest'],
  },
  {
    key: 'express',
    category: 'framework',
    label: 'Express',
    Component: SiExpress,
    color: '#000000',
    searchTerms: ['express.js', 'expressjs'],
  },
  {
    key: 'django',
    category: 'framework',
    label: 'Django',
    Component: SiDjango,
    color: '#092E20',
    searchTerms: [],
  },
  {
    key: 'rubyonrails',
    category: 'framework',
    label: 'Ruby on Rails',
    Component: SiRubyonrails,
    color: '#CC0000',
    searchTerms: ['rails', 'ruby on rails'],
  },
  {
    key: 'springboot',
    category: 'framework',
    label: 'Spring Boot',
    Component: SiSpringboot,
    color: '#6DB33F',
    searchTerms: ['spring'],
  },
  {
    key: 'laravel',
    category: 'framework',
    label: 'Laravel',
    Component: SiLaravel,
    color: '#FF2D20',
    searchTerms: [],
  },
  {
    key: 'fastapi',
    category: 'framework',
    label: 'FastAPI',
    Component: SiFastapi,
    color: '#009688',
    searchTerms: [],
  },
  {
    key: 'flask',
    category: 'framework',
    label: 'Flask',
    Component: SiFlask,
    color: '#000000',
    searchTerms: [],
  },
  {
    key: 'gatsby',
    category: 'framework',
    label: 'Gatsby',
    Component: SiGatsby,
    color: '#663399',
    searchTerms: [],
  },
  {
    key: 'remix',
    category: 'framework',
    label: 'Remix',
    Component: SiRemix,
    color: '#000000',
    searchTerms: [],
  },
  {
    key: 'astro',
    category: 'framework',
    label: 'Astro',
    Component: SiAstro,
    color: '#FF5D01',
    searchTerms: [],
  },
  {
    key: 'solid',
    category: 'framework',
    label: 'SolidJS',
    Component: SiSolid,
    color: '#2C4F7C',
    searchTerms: ['solidjs'],
  },
  {
    key: 'qwik',
    category: 'framework',
    label: 'Qwik',
    Component: SiQwik,
    color: '#18B6F6',
    searchTerms: [],
  },
  {
    key: 'nx',
    category: 'framework',
    label: 'Nx',
    Component: SiNx,
    color: '#143055',
    searchTerms: [],
  },
  {
    key: 'mui',
    category: 'framework',
    label: 'MUI',
    Component: SiMui,
    color: '#007FFF',
    searchTerms: ['material-ui', 'material ui', 'material design'],
  },
  {
    key: 'tailwindcss',
    category: 'framework',
    label: 'Tailwind CSS',
    Component: SiTailwindcss,
    color: '#06B6D4',
    searchTerms: ['tailwind', 'tw'],
  },
  {
    key: 'bootstrap',
    category: 'framework',
    label: 'Bootstrap',
    Component: SiBootstrap,
    color: '#7952B3',
    searchTerms: ['bs', 'bootstrap5'],
  },
  {
    key: 'chakraui',
    category: 'framework',
    label: 'Chakra UI',
    Component: SiChakraui,
    color: '#319795',
    searchTerms: ['chakra', 'chakra-ui'],
  },
  {
    key: 'shadcnui',
    category: 'framework',
    label: 'shadcn/ui',
    Component: SiShadcnui,
    color: '#000000',
    searchTerms: ['shadcn', 'shadcn-ui'],
  },
  {
    key: 'radixui',
    category: 'framework',
    label: 'Radix UI',
    Component: SiRadixui,
    color: '#000000',
    searchTerms: ['radix', 'radix-ui', 'radix primitives'],
  },
  {
    key: 'antdesign',
    category: 'framework',
    label: 'Ant Design',
    Component: SiAntdesign,
    color: '#0170FE',
    searchTerms: ['antd', 'ant-design'],
  },
  {
    key: 'storybook',
    category: 'framework',
    label: 'Storybook',
    Component: SiStorybook,
    color: '#FF4785',
    searchTerms: ['sb'],
  },
  {
    key: 'headlessui',
    category: 'framework',
    label: 'Headless UI',
    Component: SiHeadlessui,
    color: '#66E3FF',
    searchTerms: ['headlessui', 'headless-ui'],
  },
  {
    key: 'semanticui',
    category: 'framework',
    label: 'Semantic UI',
    Component: SiSemanticui,
    color: '#35BDB2',
    searchTerms: ['semantic-ui', 'semantic'],
  },
];
