import { IconDefinition } from '../types';
import { DiJava } from 'react-icons/di';
import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiRust,
  SiGo,
  SiSharp,
  SiCplusplus,
  SiC,
  SiPhp,
  SiRuby,
  SiSwift,
  SiKotlin,
  SiScala,
  SiDart,
  SiElixir,
  SiHaskell,
  SiLua,
  SiR,
  SiPerl,
  SiApachegroovy,
  SiClojure,
  SiErlang,
  SiJulia,
  SiNodedotjs,
} from 'react-icons/si';

export const programmingLanguageIcons: IconDefinition[] = [
  {
    key: 'javascript',
    category: 'programming-language',
    label: 'JavaScript',
    Component: SiJavascript,
    color: '#F7DF1E',
    searchTerms: ['js', 'ecmascript', 'es6', 'es2015', 'es2020'],
  },
  {
    key: 'typescript',
    category: 'programming-language',
    label: 'TypeScript',
    Component: SiTypescript,
    color: '#3178C6',
    searchTerms: ['ts', 'typed javascript'],
  },
  {
    key: 'python',
    category: 'programming-language',
    label: 'Python',
    Component: SiPython,
    color: '#3776AB',
    searchTerms: ['py', 'django', 'flask', 'fastapi'],
  },
  {
    key: 'rust',
    category: 'programming-language',
    label: 'Rust',
    Component: SiRust,
    color: '#DEA584',
    searchTerms: ['cargo', 'rustc', 'rust-lang'],
  },
  {
    key: 'go',
    category: 'programming-language',
    label: 'Go',
    Component: SiGo,
    color: '#00ADD8',
    searchTerms: ['golang', 'go-lang'],
  },
  {
    key: 'java',
    category: 'programming-language',
    label: 'Java',
    Component: DiJava,
    color: '#ED8B00',
    searchTerms: ['jvm', 'jdk', 'j2ee', 'spring'],
  },
  {
    key: 'csharp',
    category: 'programming-language',
    label: 'C#',
    Component: SiSharp,
    color: '#239120',
    searchTerms: ['c-sharp', 'dotnet', '.net', 'c#', 'csharp'],
  },
  {
    key: 'cpp',
    category: 'programming-language',
    label: 'C++',
    Component: SiCplusplus,
    color: '#00599C',
    searchTerms: ['cpp', 'c-plus-plus', 'cxx', 'c++'],
  },
  {
    key: 'c',
    category: 'programming-language',
    label: 'C',
    Component: SiC,
    color: '#A8B9CC',
    searchTerms: ['clang', 'ansi-c', 'c-lang'],
  },
  {
    key: 'php',
    category: 'programming-language',
    label: 'PHP',
    Component: SiPhp,
    color: '#777BB4',
    searchTerms: ['php8', 'laravel', 'wordpress'],
  },
  {
    key: 'ruby',
    category: 'programming-language',
    label: 'Ruby',
    Component: SiRuby,
    color: '#CC342D',
    searchTerms: ['rb', 'rails', 'ruby-on-rails', 'rubygems'],
  },
  {
    key: 'swift',
    category: 'programming-language',
    label: 'Swift',
    Component: SiSwift,
    color: '#FA7343',
    searchTerms: ['swiftlang', 'ios', 'macos'],
  },
  {
    key: 'kotlin',
    category: 'programming-language',
    label: 'Kotlin',
    Component: SiKotlin,
    color: '#7F52FF',
    searchTerms: ['kt', 'kotlinlang', 'android'],
  },
  {
    key: 'scala',
    category: 'programming-language',
    label: 'Scala',
    Component: SiScala,
    color: '#DC322F',
    searchTerms: ['sc', 'scalac', 'akka', 'play'],
  },
  {
    key: 'dart',
    category: 'programming-language',
    label: 'Dart',
    Component: SiDart,
    color: '#0175C2',
    searchTerms: ['flutter', 'dartlang'],
  },
  {
    key: 'elixir',
    category: 'programming-language',
    label: 'Elixir',
    Component: SiElixir,
    color: '#4B275F',
    searchTerms: ['ex', 'exs', 'phoenix', 'erlang'],
  },
  {
    key: 'haskell',
    category: 'programming-language',
    label: 'Haskell',
    Component: SiHaskell,
    color: '#5E5086',
    searchTerms: ['hs', 'ghc', 'cabal', 'stack'],
  },
  {
    key: 'lua',
    category: 'programming-language',
    label: 'Lua',
    Component: SiLua,
    color: '#000080',
    searchTerms: ['luajit', 'lua-lang', 'roblox'],
  },
  {
    key: 'r',
    category: 'programming-language',
    label: 'R',
    Component: SiR,
    color: '#276DC3',
    searchTerms: ['rlang', 'rstudio', 'ggplot', 'tidyverse'],
  },
  {
    key: 'perl',
    category: 'programming-language',
    label: 'Perl',
    Component: SiPerl,
    color: '#39457E',
    searchTerms: ['pl', 'perl6', 'raku'],
  },
  {
    key: 'groovy',
    category: 'programming-language',
    label: 'Groovy',
    Component: SiApachegroovy,
    color: '#4298B8',
    searchTerms: ['gradle', 'groovylang'],
  },
  {
    key: 'clojure',
    category: 'programming-language',
    label: 'Clojure',
    Component: SiClojure,
    color: '#5881D8',
    searchTerms: ['clj', 'cljs', 'clojurescript', 'cljc'],
  },
  {
    key: 'erlang',
    category: 'programming-language',
    label: 'Erlang',
    Component: SiErlang,
    color: '#A90533',
    searchTerms: ['erl', 'otp', 'beam'],
  },
  {
    key: 'julia',
    category: 'programming-language',
    label: 'Julia',
    Component: SiJulia,
    color: '#9558B2',
    searchTerms: ['jl', 'julialang'],
  },
  {
    key: 'nodejs',
    category: 'programming-language',
    label: 'Node.js',
    Component: SiNodedotjs,
    color: '#339933',
    searchTerms: ['node', 'node.js', 'nodejs', 'express', 'npm', 'yarn', 'pnpm'],
  },
];
