import { IconDefinition } from '../types';
import {
  SiGit,
  SiDocker,
  SiKubernetes,
  SiGithubactions,
  SiGitlab,
  SiWebpack,
  SiVite,
  SiTurborepo,
  SiPnpm,
  SiNpm,
  SiYarn,
  SiGradle,
  SiApachemaven,
  SiTerraform,
  SiAnsible,
  SiVscodium,
  SiNeovim,
  SiPostman,
  SiFigma,
  SiEslint,
  SiPrettier,
  SiNginx,
  SiApache,
  SiGrafana,
  SiPrometheus,
  SiDatadog,
  SiSentry,
  SiJira,
  SiNotion,
  SiStripe,
  SiCypress,
  SiJest,
  SiVitest,
  SiTestinglibrary,
  SiRollupdotjs,
  SiGraphql,
  SiSwagger,
  SiRedux,
  SiMobx,
  SiZod,
  SiReactquery,
  SiAxios,
  SiSass,
  SiStyledcomponents,
  SiBabel,
  SiEsbuild,
  SiSwc,
  SiSlack,
  SiDiscord,
  SiTrello,
  SiAsana,
  SiLinear,
  SiConfluence,
  SiAuth0,
  SiOkta,
} from 'react-icons/si';

export const toolIcons: IconDefinition[] = [
  {
    key: 'git',
    category: 'tool',
    label: 'Git',
    Component: SiGit,
    color: '#F05032',
    searchTerms: [],
  },
  {
    key: 'docker',
    category: 'tool',
    label: 'Docker',
    Component: SiDocker,
    color: '#2496ED',
    searchTerms: [],
  },
  {
    key: 'kubernetes',
    category: 'tool',
    label: 'Kubernetes',
    Component: SiKubernetes,
    color: '#326CE5',
    searchTerms: ['k8s'],
  },
  {
    key: 'githubactions',
    category: 'tool',
    label: 'GitHub Actions',
    Component: SiGithubactions,
    color: '#2088FF',
    searchTerms: ['gh actions', 'ci/cd'],
  },
  {
    key: 'gitlabci',
    category: 'tool',
    label: 'GitLab CI',
    Component: SiGitlab,
    color: '#FC6D26',
    searchTerms: ['gitlab ci'],
  },
  {
    key: 'webpack',
    category: 'tool',
    label: 'Webpack',
    Component: SiWebpack,
    color: '#8DD6F9',
    searchTerms: [],
  },
  {
    key: 'vite',
    category: 'tool',
    label: 'Vite',
    Component: SiVite,
    color: '#646CFF',
    searchTerms: [],
  },
  {
    key: 'turbopack',
    category: 'tool',
    label: 'Turbopack',
    Component: SiTurborepo,
    color: '#EF4444',
    searchTerms: ['turbo'],
  },
  {
    key: 'pnpm',
    category: 'tool',
    label: 'pnpm',
    Component: SiPnpm,
    color: '#F69220',
    searchTerms: [],
  },
  {
    key: 'npm',
    category: 'tool',
    label: 'npm',
    Component: SiNpm,
    color: '#CB3837',
    searchTerms: [],
  },
  {
    key: 'yarn',
    category: 'tool',
    label: 'Yarn',
    Component: SiYarn,
    color: '#2C8EBB',
    searchTerms: [],
  },
  {
    key: 'gradle',
    category: 'tool',
    label: 'Gradle',
    Component: SiGradle,
    color: '#02303A',
    searchTerms: [],
  },
  {
    key: 'maven',
    category: 'tool',
    label: 'Maven',
    Component: SiApachemaven,
    color: '#C71A36',
    searchTerms: [],
  },
  {
    key: 'terraform',
    category: 'tool',
    label: 'Terraform',
    Component: SiTerraform,
    color: '#844FBA',
    searchTerms: ['iac'],
  },
  {
    key: 'ansible',
    category: 'tool',
    label: 'Ansible',
    Component: SiAnsible,
    color: '#EE0000',
    searchTerms: [],
  },
  {
    key: 'vscode',
    category: 'tool',
    label: 'VS Code',
    Component: SiVscodium,
    color: '#007ACC',
    searchTerms: ['vs code', 'visual studio code'],
  },
  {
    key: 'neovim',
    category: 'tool',
    label: 'Neovim',
    Component: SiNeovim,
    color: '#57A143',
    searchTerms: ['nvim'],
  },
  {
    key: 'postman',
    category: 'tool',
    label: 'Postman',
    Component: SiPostman,
    color: '#FF6C37',
    searchTerms: [],
  },
  {
    key: 'figma',
    category: 'tool',
    label: 'Figma',
    Component: SiFigma,
    color: '#F24E1E',
    searchTerms: [],
  },
  {
    key: 'eslint',
    category: 'tool',
    label: 'ESLint',
    Component: SiEslint,
    color: '#4B32C3',
    searchTerms: [],
  },
  {
    key: 'prettier',
    category: 'tool',
    label: 'Prettier',
    Component: SiPrettier,
    color: '#F7B93E',
    searchTerms: [],
  },
  {
    key: 'nginx',
    category: 'tool',
    label: 'Nginx',
    Component: SiNginx,
    color: '#009639',
    searchTerms: [],
  },
  {
    key: 'apache',
    category: 'tool',
    label: 'Apache',
    Component: SiApache,
    color: '#D22128',
    searchTerms: [],
  },
  {
    key: 'grafana',
    category: 'tool',
    label: 'Grafana',
    Component: SiGrafana,
    color: '#F46800',
    searchTerms: [],
  },
  {
    key: 'prometheus',
    category: 'tool',
    label: 'Prometheus',
    Component: SiPrometheus,
    color: '#E6522C',
    searchTerms: [],
  },
  {
    key: 'datadog',
    category: 'tool',
    label: 'Datadog',
    Component: SiDatadog,
    color: '#632CA6',
    searchTerms: [],
  },
  {
    key: 'sentry',
    category: 'tool',
    label: 'Sentry',
    Component: SiSentry,
    color: '#362D59',
    searchTerms: [],
  },
  {
    key: 'jira',
    category: 'tool',
    label: 'Jira',
    Component: SiJira,
    color: '#0052CC',
    searchTerms: [],
  },
  {
    key: 'notion',
    category: 'tool',
    label: 'Notion',
    Component: SiNotion,
    color: '#000000',
    searchTerms: [],
  },
  {
    key: 'stripe',
    category: 'tool',
    label: 'Stripe',
    Component: SiStripe,
    color: '#008CDD',
    searchTerms: ['payment', 'payments'],
  },
  {
    key: 'cypress',
    category: 'tool',
    label: 'Cypress',
    Component: SiCypress,
    color: '#69D3A7',
    searchTerms: ['e2e', 'end-to-end'],
  },
  {
    key: 'jest',
    category: 'tool',
    label: 'Jest',
    Component: SiJest,
    color: '#C21325',
    searchTerms: ['testing', 'unit test'],
  },
  {
    key: 'vitest',
    category: 'tool',
    label: 'Vitest',
    Component: SiVitest,
    color: '#6E9F18',
    searchTerms: ['vite test'],
  },
  {
    key: 'testinglibrary',
    category: 'tool',
    label: 'Testing Library',
    Component: SiTestinglibrary,
    color: '#E33332',
    searchTerms: ['rtl', 'react testing library', '@testing-library'],
  },
  {
    key: 'graphql',
    category: 'tool',
    label: 'GraphQL',
    Component: SiGraphql,
    color: '#E10098',
    searchTerms: ['gql', 'apollo', 'graphql'],
  },
  {
    key: 'swagger',
    category: 'tool',
    label: 'Swagger',
    Component: SiSwagger,
    color: '#85EA2D',
    searchTerms: ['openapi', 'api docs'],
  },
  {
    key: 'redux',
    category: 'tool',
    label: 'Redux',
    Component: SiRedux,
    color: '#764ABC',
    searchTerms: ['redux toolkit', 'rtk', 'state management'],
  },
  {
    key: 'mobx',
    category: 'tool',
    label: 'MobX',
    Component: SiMobx,
    color: '#FF9955',
    searchTerms: ['mobx-state-tree', 'mst'],
  },
  {
    key: 'zod',
    category: 'tool',
    label: 'Zod',
    Component: SiZod,
    color: '#3E67B1',
    searchTerms: ['schema', 'validation'],
  },
  {
    key: 'reactquery',
    category: 'tool',
    label: 'React Query',
    Component: SiReactquery,
    color: '#FF4154',
    searchTerms: ['tanstack query', 'tanstack-query', 'query'],
  },
  {
    key: 'axios',
    category: 'tool',
    label: 'Axios',
    Component: SiAxios,
    color: '#5A29E4',
    searchTerms: ['http client', 'fetch'],
  },
  {
    key: 'sass',
    category: 'tool',
    label: 'Sass',
    Component: SiSass,
    color: '#CC6699',
    searchTerms: ['scss', 'css preprocessor'],
  },
  {
    key: 'styledcomponents',
    category: 'tool',
    label: 'Styled Components',
    Component: SiStyledcomponents,
    color: '#DB7093',
    searchTerms: ['styled', 'css-in-js'],
  },
  {
    key: 'babel',
    category: 'tool',
    label: 'Babel',
    Component: SiBabel,
    color: '#F9DC3E',
    searchTerms: ['transpiler', 'compiler'],
  },
  {
    key: 'esbuild',
    category: 'tool',
    label: 'esbuild',
    Component: SiEsbuild,
    color: '#FFCF00',
    searchTerms: ['bundler'],
  },
  {
    key: 'swc',
    category: 'tool',
    label: 'SWC',
    Component: SiSwc,
    color: '#FFFFFF',
    searchTerms: ['compiler', 'bundler', 'rust'],
  },
  {
    key: 'slack',
    category: 'tool',
    label: 'Slack',
    Component: SiSlack,
    color: '#4A154B',
    searchTerms: ['chat', 'communication'],
  },
  {
    key: 'discord',
    category: 'tool',
    label: 'Discord',
    Component: SiDiscord,
    color: '#5865F2',
    searchTerms: ['chat', 'community'],
  },
  {
    key: 'trello',
    category: 'tool',
    label: 'Trello',
    Component: SiTrello,
    color: '#0052CC',
    searchTerms: ['project management', 'kanban'],
  },
  {
    key: 'asana',
    category: 'tool',
    label: 'Asana',
    Component: SiAsana,
    color: '#F06A6A',
    searchTerms: ['project management'],
  },
  {
    key: 'linear',
    category: 'tool',
    label: 'Linear',
    Component: SiLinear,
    color: '#5E6AD2',
    searchTerms: ['issue tracking', 'project management'],
  },
  {
    key: 'confluence',
    category: 'tool',
    label: 'Confluence',
    Component: SiConfluence,
    color: '#172B4D',
    searchTerms: ['wiki', 'docs', 'documentation'],
  },
  {
    key: 'auth0',
    category: 'tool',
    label: 'Auth0',
    Component: SiAuth0,
    color: '#EB5424',
    searchTerms: ['authentication', 'auth', 'okta'],
  },
  {
    key: 'okta',
    category: 'tool',
    label: 'Okta',
    Component: SiOkta,
    color: '#007DC1',
    searchTerms: ['authentication', 'identity', 'sso'],
  },
  {
    key: 'rollup',
    category: 'tool',
    label: 'Rollup',
    Component: SiRollupdotjs,
    color: '#EC4A3F',
    searchTerms: ['bundler', 'es modules'],
  },
];
